<?php
declare(strict_types=1);

// Especialidades de este hub: /{hub}/{slug}/. Una intencion de busqueda distinta a la del hub.
// 'related' son rutas completas. Sin precios, sin plazos fijos, sin datos inventados.
return [
    'duplex' => [
        'name' => 'Dúplex y casas de dos plantas',
        'title' => 'Construcción de dúplex en Paraguay | Obra',
        'description' => 'Construcción de dúplex y casas de dos plantas en Asunción y Gran Asunción: estructura, losa, escalera e instalaciones resueltas para aprovechar terrenos chicos.',
        'h1' => 'Construcción de dúplex y casas de dos plantas',
        'kicker' => 'Más metros en el mismo terreno',
        'intro' => [
            'Un dúplex resuelve un problema muy común en Asunción y Central: terrenos angostos o compartidos donde una casa de una planta no alcanza. Construimos dúplex para vivienda propia, para dos familias y como unidades para alquilar.',
            'La diferencia con una casa de una planta está en la estructura: losa, columnas, escalera y las instalaciones que suben. Eso se define en el proyecto, no en la obra, para que el presupuesto sea real desde el principio.',
            'Acá te contamos cómo se construye cada variante, qué conviene decidir antes de abrir la primera zanja y en qué se distingue un dúplex de un townhouse pensado para renta.',
        ],
        'includes' => ['Estructura de hormigón armado y losa', 'Escalera interior o exterior según el uso', 'Instalaciones independientes por unidad cuando son dos viviendas', 'Aislación acústica entre unidades', 'Cochera, acceso y medidores separados', 'Pared medianera entre unidades resuelta como muro doble'],
        'process' => [
            ['Visita y lectura del terreno', 'Vamos al lote, medimos los frentes, vemos los retiros y miramos cómo se relaciona con las casas vecinas. En un dúplex el ancho útil manda: define dónde cae la escalera y cómo se reparten los ambientes.'],
            ['Definición de unidades y accesos', 'Se decide si es una sola vivienda en dos plantas o dos unidades independientes, y por dónde entra cada una. De esa decisión salen los medidores, las cocheras y los recorridos de instalaciones.'],
            ['Presupuesto por rubro', 'Fundaciones, estructura, mampostería, losa, escalera, instalaciones, techo y terminaciones, cada rubro por separado y en guaraníes. Así ves qué parte corresponde a la planta baja y qué a la alta.'],
            ['Estructura y losa intermedia', 'Se levantan fundaciones, columnas y vigas, y se hormigona la losa que separa las plantas. Antes de colar se dejan pasos de caños, bajadas y el vacío de la escalera.'],
            ['Instalaciones, terminaciones y entrega', 'Se cierra mampostería, se corren las instalaciones de cada unidad, se terminan pisos, revestimientos y aberturas, y se recorre todo con vos antes de entregar.'],
        ],
        'materials' => [
            ['Fundaciones y columnas', 'La carga de dos plantas es mayor y el suelo arcilloso de la zona no perdona una fundación corta. Se dimensiona según el estudio del terreno y el proyecto estructural.'],
            ['Losa entre plantas', 'Hormigón armado en losa maciza o con viguetas, según la luz y el uso. Cambia el peso, el ruido que pasa de un piso a otro y la forma de armar el encofrado.'],
            ['Escalera', 'Hormigón revestido, con estructura metálica o mixta. Ubicarla adentro ahorra superficie de patio; afuera libera ambientes pero la expone al sol y a la lluvia.'],
            ['Cerramiento y techo', 'Ladrillo cerámico o de campo y techo inclinado o losa plana. En la planta alta el techo recibe más sol, así que la aislación térmica se piensa desde el inicio.'],
        ],
        'sections' => [
            ['Dúplex de vivienda o dúplex de renta', ['El primero suele ser una casa en dos plantas: planta baja social, planta alta de dormitorios. El segundo son dos unidades separadas, cada una con su entrada, su medidor y su cocina, pensadas para vivir en una y alquilar la otra, o para dos familias.', 'La diferencia se nota en la obra: las unidades independientes duplican instalaciones, requieren un muro divisorio que frene el ruido y obligan a resolver accesos separados desde la calle.']],
            ['Townhouse: dos unidades en un mismo terreno', ['Un townhouse es una vivienda entre medianeras con su propio acceso, y en una obra de dos unidades funciona como inversión: una para vivir y otra para alquilar, o las dos para renta. Se construye con la misma lógica que un dúplex, pero con fachada y acceso propios para cada una.', 'Para el inversor lo importante es que cada unidad sea autónoma: medidor, agua, desagües y cochera propios, así se alquila o se vende sin depender de la otra. Eso se resuelve en obra y conviene planearlo antes de empezar.']],
        ],
        'mistakes' => [
            ['Decidir la escalera al final', 'Es la pieza que más condiciona la planta. Se ubica desde el primer croquis, no cuando ya están las paredes.'],
            ['No prever el paso de instalaciones', 'Si los caños de la planta alta no bajan por un lugar pensado, después hay que romper. Se dejan los ductos marcados antes de hormigonar.'],
            ['Descuidar el ruido entre unidades', 'Un muro simple entre dos viviendas transmite todo. Se resuelve con doble pared y una buena junta.'],
            ['Olvidar el techo de la planta alta', 'Recibe todo el sol de la tarde. Sin aislación se convierte en horno; se define el sistema antes de cerrar.'],
        ],
        'ideal' => ['Tu terreno es angosto o querés dejar patio libre.', 'Querés dos unidades: una para vivir y otra para alquilar.', 'Construís sobre un terreno familiar compartido.', 'Buscás una inversión con dos unidades autónomas.'],
        'faqs' => [
            ['¿Un dúplex es más caro por metro cuadrado que una casa de una planta?', 'La estructura y la escalera suman costo, pero se ahorra en techo, fundaciones y terreno por metro construido. La comparación real sale del cómputo por rubro de cada proyecto.'],
            ['¿Puedo hacer dos unidades con medidores separados?', 'Sí. Se proyectan instalaciones independientes y se coordina la habilitación de medidores con las prestadoras.'],
            ['¿Se puede construir el dúplex por etapas?', 'Sí, siempre que la estructura de la segunda planta quede prevista desde la primera etapa.'],
            ['¿Cuál es la diferencia entre un dúplex y un townhouse?', 'Un dúplex suele ser una vivienda de dos plantas o dos unidades apiladas; un townhouse es una unidad con acceso propio entre medianeras. En obra se resuelven de manera parecida; cambia la organización de accesos e instalaciones.'],
            ['¿Sirve para alquilar una de las unidades?', 'Sí, si cada unidad tiene su entrada, su medidor y sus instalaciones independientes. Lo conversamos en la visita para que la obra quede lista para renta.'],
        ],
        'related' => ['/casas/minimalistas/', '/casas/etapas/', '/ampliaciones/planta-alta/', '/guias/costo-casa/'],
    ],
    'minimalistas' => [
        'name' => 'Casas modernas y minimalistas',
        'title' => 'Construcción de casas modernas y minimalistas en Paraguay | Obra',
        'description' => 'Construcción de casas modernas y minimalistas en Asunción y Gran Asunción: losa plana, ladrillo visto y aberturas grandes, con terminaciones limpias.',
        'summary' => 'Construcción de casas modernas y minimalistas en Asunción y Gran Asunción: losa plana, ladrillo visto, grandes aberturas y galería integrada, ejecutadas con terminaciones limpias.',
        'h1' => 'Construcción de casas modernas y minimalistas',
        'kicker' => 'Líneas simples, bien ejecutadas',
        'intro' => [
            'Una casa moderna se ve simple, pero construirla exige precisión. Losa plana, ladrillo visto, hormigón a la vista, aberturas grandes hacia el patio y galería como extensión de la casa: es un estilo que perdona poco, porque cada junta, cada encuentro y cada nivel queda expuesto.',
            'Por eso lo tratamos como una obra de terminación fina. Acá vas a leer cómo se ejecuta, qué detalles se cuidan en obra y por qué una casa de líneas limpias lleva más trabajo de lo que aparenta.',
        ],
        'includes' => ['Losa plana con aislación y pendientes de desagüe ocultas', 'Ladrillo visto o revoque fino según el proyecto', 'Aberturas de gran luz con dinteles y vigas calculadas', 'Desagües pluviales ocultos y babetas', 'Galería integrada con piso continuo', 'Detalles de terminación: bordes, zócalos y encuentros'],
        'process' => [
            ['Lectura del proyecto y de los detalles', 'Con los planos en mano revisamos cada encuentro que va a quedar a la vista: bordes de losa, remates de ladrillo, dinteles y desagües. Lo que no está resuelto en el papel se define antes de comprar el material.'],
            ['Presupuesto por rubro', 'Estructura, mampostería vista, losa e impermeabilización, aberturas, desagües y terminaciones, cada uno por separado y en guaraníes. Ahí se ve dónde está el mayor trabajo de mano de obra.'],
            ['Estructura y mampostería de precisión', 'Se hormigonan columnas y vigas con encofrados prolijos y se levanta la pared con ladrillo seleccionado, plomo y nivel controlados. Un error en la primera hilada se arrastra hasta el techo.'],
            ['Losa plana e impermeabilización', 'Se arma la losa con sus pendientes, se colocan los desagües y se aplica la membrana con sus remates. Se hace una prueba de agua antes de tapar.'],
            ['Terminaciones y entrega', 'Sellado del ladrillo, pintura, aberturas, pisos y encuentros. Recorremos la casa con vos con luz natural y luz rasante para detectar detalles antes de entregar.'],
        ],
        'materials' => [
            ['Losa plana con membrana', 'Pendiente mínima hacia los desagües, membrana continua, babetas en los bordes y protección superior. Es lo que evita que la casa filtre con las lluvias fuertes.'],
            ['Ladrillo visto', 'Requiere ladrillo parejo, juntas trabajadas y sellador. Cada lote cambia un poco de tono, así que conviene mezclar cajas al levantar la pared para que no se noten franjas.'],
            ['Hormigón a la vista', 'Pide encofrado limpio y buen vibrado. Sus defectos no se tapan con pintura, por eso se controla el colado y se define el acabado antes de empezar.'],
            ['Dinteles y vigas para grandes luces', 'Las aberturas amplias cargan la estructura. Se calculan vigas o dinteles armados que soporten el peso sin fisuras en la pared vecina.'],
            ['Desagües ocultos', 'Bajadas embutidas y canaletas ocultas. Se ven prolijas, pero exigen un trazado preciso y accesos para mantenimiento.'],
        ],
        'sections' => [
            ['Qué hace costosa a una casa minimalista de construir', ['El costo no viene de la cantidad de adornos sino de lo contrario: al no haber revoque grueso ni cornisas que oculten, todo tiene que salir bien a la primera. Hay más horas de mano de obra por metro cuadrado, materiales seleccionados y controles constantes.', 'También pesa la losa plana, que necesita impermeabilización cuidada, y las aberturas grandes, que piden estructura reforzada. Por eso el presupuesto por rubro te muestra dónde se va el esfuerzo y qué se puede ajustar sin perder el aspecto.']],
            ['Clima paraguayo y casa moderna', ['El calor y las lluvias fuertes mandan. Los aleros escasos o inexistentes se compensan con aislación en la losa, aberturas orientadas con criterio y galerías que den sombra. Lo pensamos junto con el proyectista para que la casa sea agradable todo el año.']],
        ],
        'mistakes' => [
            ['Improvisar los desagües', 'Una losa plana sin bajadas bien ubicadas retiene agua. Se marcan pendientes y desagües antes de hormigonar.'],
            ['Mezclar ladrillos de lotes distintos sin criterio', 'Aparecen franjas de color. Se pide todo junto y se mezcla al levantar.'],
            ['Tapar defectos con pintura', 'En hormigón o ladrillo visto no funciona. Se corrige en obra, no después.'],
            ['Subestimar las aberturas grandes', 'Sin viga adecuada aparecen fisuras y las hojas rozan. Se calcula la estructura primero y se cuelgan las aberturas después.'],
        ],
        'ideal' => ['Querés una casa de líneas limpias sin sobresaltos en la terminación.', 'Ya tenés un proyecto moderno y necesitás quien lo ejecute con precisión.', 'Buscás una casa con galería y patio integrados.'],
        'faqs' => [
            ['¿La losa plana da problemas de filtración?', 'Da problemas cuando está mal ejecutada. Con pendientes correctas, desagües bien ubicados, membrana y aislación térmica funciona bien en el clima paraguayo.'],
            ['¿El ladrillo visto necesita mantenimiento?', 'Necesita un sellado periódico y una buena ejecución de juntas desde el inicio. Lo incluimos en el alcance y te explicamos el mantenimiento al entregar.'],
            ['¿Hacen el proyecto también?', 'El diseño lo hace nuestro estudio en arq.com.py o el arquitecto que elijas. Nosotros construimos.'],
            ['¿Por qué una casa minimalista lleva tanta mano de obra?', 'Porque las terminaciones quedan a la vista y no hay revoque ni adornos que disimulen. Cada encuentro se ejecuta con cuidado y se controla más de una vez.'],
            ['¿Se puede hacer con techo inclinado en lugar de losa plana?', 'Sí. Un techo inclinado con cargas ocultas mantiene la línea limpia y simplifica el drenaje, aunque cambia la imagen de la casa. Lo hablamos con el proyectista.'],
        ],
        'related' => ['/casas/duplex/', '/patios/decks/', '/piscinas/desbordante/', '/guias/costo-casa/'],
        'link' => ['site' => 'arq', 'path' => '/minimalista/', 'text' => 'El diseño de una casa minimalista (planos, fachadas y renders) lo hace nuestro estudio en arq.com.py; acá nos ocupamos de construirla.'],
    ],
    'etapas' => [
        'name' => 'Construcción por etapas',
        'title' => 'Construcción de casas por etapas en Paraguay | Obra',
        'description' => 'Construcción de casas por etapas en Asunción y Gran Asunción: obra gruesa primero, terminaciones después, con un plan que evita rehacer y ordena el gasto.',
        'summary' => 'Construí tu casa por etapas en Asunción y Gran Asunción: obra gruesa primero, terminaciones después, con un plan que evita rehacer y mantiene el presupuesto controlado.',
        'h1' => 'Construcción de casas por etapas',
        'kicker' => 'Empezá con lo que tenés, sin cerrar puertas',
        'intro' => [
            'Muchas familias construyen a medida que pueden: primero la platea y la mampostería, después el techo, más adelante las terminaciones. Bien planificado funciona. Mal planificado se paga dos veces: se rompe lo hecho para pasar caños o se levantan paredes que después estorban.',
            'Nuestro trabajo es ordenar la secuencia técnica para que cada etapa deje la siguiente preparada, y que cada etapa tenga su propio presupuesto cerrado.',
            'Acá te explicamos cómo se corta una obra en etapas sin rehacer nada y cómo encaja ese orden con los desembolsos de un crédito.',
        ],
        'includes' => ['Plan de etapas con lo que debe quedar previsto en cada una', 'Etapa 1: fundaciones, mampostería y estructura', 'Etapa 2: techo, instalaciones embutidas y aberturas', 'Etapa 3: revestimientos, pisos, pintura y artefactos', 'Presupuesto independiente por etapa', 'Protección de lo ejecutado entre una etapa y la siguiente'],
        'process' => [
            ['Plano completo y plan de etapas', 'Aunque construyas de a poco, la casa se piensa entera. Se define cuántas etapas hacen falta y qué queda previsto en cada una: esperas de hierro, pases de caños y ubicación de ampliaciones.'],
            ['Presupuesto por etapa', 'Cada etapa tiene su propio presupuesto por rubro y en guaraníes, para que sepas cuánto necesitás juntar antes de arrancar y qué se hace con ese dinero.'],
            ['Obra gruesa', 'Fundaciones, platea o vigas, columnas, mampostería y losa o estructura de techo. Es la etapa que da forma a la casa y donde más importa que todo quede a nivel y a plomo.'],
            ['Techo y cerramiento', 'Con el techo puesto y las aberturas colocadas, la obra queda protegida de la lluvia y se puede trabajar adentro. Es el punto de corte más seguro para pausar.'],
            ['Terminaciones y habitabilidad', 'Instalaciones eléctricas y sanitarias terminadas, revoques, pisos, pintura y artefactos. Se entrega la casa con un detalle de lo ejecutado.'],
        ],
        'materials' => [
            ['Estructura completa desde el inicio', 'Aunque se haga por partes, las columnas y las fundaciones se calculan para la casa entera. Es más barato dejarlas listas que reforzar después.'],
            ['Esperas y pases de instalaciones', 'Caños de agua, desagüe y electricidad se dejan embutidos o con pases marcados para no romper paredes terminadas.'],
            ['Cubierta provisoria o definitiva', 'Un techo definitivo cuida lo ya construido. Si por fondos la etapa se corta antes, se protege la mampostería con una cubierta provisoria bien resuelta.'],
            ['Sistema de mampostería', 'Ladrillo de campo, cerámico o bloque. Se elige pensando en la casa final y en cómo se va a ampliar.'],
        ],
        'sections' => [
            ['Cómo dividir la obra para no rehacer nada', ['El orden lógico es el de la estructura: primero lo que sostiene, después lo que cubre, al final lo que viste. Conviene cortar la obra en puntos donde lo ejecutado quede protegido y no dependa de lo que falta.', 'Lo que sí hay que hacer desde la primera etapa es lo que después se vuelve carísimo de corregir: fundaciones, niveles, esperas de instalaciones y ubicación de escaleras o ampliaciones futuras.']],
            ['Etapas y desembolsos del crédito', ['Los créditos de construcción suelen liberar el dinero en tramos según el avance de la obra. Si las etapas se definen con criterio, cada desembolso corresponde a un rubro que se puede ver y medir: cimientos, estructura, techo, instalaciones.', 'Cada banco tiene su forma de verificar el avance y sus requisitos, por eso conviene consultar con tu banco antes de fijar el plan. Más información en la guía del crédito.']],
        ],
        'mistakes' => [
            ['Cortar la obra a mitad de camino sin techo', 'La lluvia daña la mampostería y las armaduras. El primer corte se hace con techo y aberturas.'],
            ['No dejar esperas de instalaciones', 'Después hay que romper para pasar caños. Se dejan pases marcados desde la primera etapa.'],
            ['Levantar paredes antes de definir la distribución', 'Si después cambia la planta, se demuelen. El plano completo se define primero.'],
            ['Mezclar etapas sin presupuesto propio', 'Los gastos se confunden y la obra se frena. Cada etapa tiene su cómputo por rubro.'],
            ['Elegir la etapa por lo que se ve', 'Empezar por lo lindo deja sin fondos lo importante. Se prioriza lo que protege y sostiene.'],
        ],
        'ideal' => ['Tenés terreno y fondos para arrancar, pero no para toda la casa.', 'Vas a combinar ahorro propio con un crédito más adelante.', 'Querés habitar una parte de la casa mientras se termina el resto.'],
        'faqs' => [
            ['¿Cuál es el orden correcto de las etapas?', 'Fundaciones y estructura, después techo y cerramiento, después instalaciones y terminaciones. Lo que nunca conviene es dejar la obra gruesa expuesta a la lluvia sin techo por mucho tiempo.'],
            ['¿Puedo cambiar de constructor entre etapas?', 'Podés. Por eso cada etapa se entrega con un detalle de lo ejecutado y de lo que quedó previsto para la siguiente.'],
            ['¿Se puede vivir en la casa entre etapas?', 'Sí, cuando una parte está habitable y la obra restante se aísla de forma segura.'],
            ['¿Cómo se relacionan las etapas con los desembolsos del banco?', 'Cada tramo del crédito suele corresponder a un avance verificable. Armar las etapas por rubros concretos ayuda a justificar cada desembolso. Consultá con tu banco cómo mide el avance.'],
            ['¿Qué se debe dejar previsto en la primera etapa?', 'Fundaciones para la casa completa, esperas de hierro para lo que se suma después, pases de caños y la ubicación de escaleras o ampliaciones.'],
        ],
        'related' => ['/credito/', '/guias/costo-casa/', '/ampliaciones/', '/guias/plazos/'],
    ],
    'prefabricadas' => [
        'name' => 'Casas prefabricadas vs construcción tradicional',
        'title' => 'Casas prefabricadas vs construcción tradicional | Obra',
        'description' => 'Casas prefabricadas y premoldeadas frente a la construcción tradicional en Paraguay: durabilidad, clima, financiación, reventa y en qué casos conviene cada una.',
        'h1' => 'Casas prefabricadas o construcción tradicional: qué conviene',
        'kicker' => 'Una comparación honesta antes de decidir',
        'intro' => [
            'Las casas prefabricadas y premoldeadas se presentan como la opción rápida y económica. En algunos casos lo son. Pero en Paraguay pesan tres cosas que conviene mirar antes: el calor, la humedad y la financiación bancaria.',
            'Obra construye con sistema tradicional (mampostería de ladrillo y estructura de hormigón). Acá te contamos sin vueltas cuándo una prefabricada puede convenirte más y cuándo no.',
        ],
        'includes' => ['Comportamiento térmico en el verano paraguayo', 'Durabilidad, mantenimiento y humedad', 'Qué acepta un banco o la AFD como garantía', 'Valor de reventa y ampliaciones futuras', 'Costo total: casa, platea, instalaciones y terreno preparado', 'Qué se puede hacer con cada sistema y qué no'],
        'process' => [
            ['Consulta y objetivo', 'Vemos qué necesitás: tamaño, uso, si financiás, si querés ampliar. Con eso te decimos si una prefabricada te sirve o si conviene la obra tradicional.'],
            ['Comparación del mismo alcance', 'Se comparan sistemas con lo mismo incluido: platea, instalaciones, conexiones, terminaciones y terreno preparado. Sin ese cuadro, la comparación de catálogo engaña.'],
            ['Presupuesto por rubro', 'Si se construye tradicional, cada rubro va por separado y en guaraníes, para que puedas ponerlo al lado de una oferta prefabricada.'],
            ['Construcción tradicional', 'Platea o fundaciones, mampostería, estructura de hormigón, techo, instalaciones y terminaciones, obra por obra y con control diario.'],
            ['Entrega y mantenimiento', 'Se recorre la casa, se entrega el detalle de lo ejecutado y se explica el mantenimiento básico.'],
        ],
        'materials' => [
            ['Casa prefabricada', 'Se fabrica en piezas o módulos y se monta en el terreno. Puede ser rápida de armar, pero necesita una platea o base bien ejecutada, y el aislamiento térmico y la humedad son puntos a revisar.'],
            ['Casa premoldeada', 'Usa paneles o piezas de hormigón hechas de antemano. Es más pesada y resistente que muchas prefabricadas livianas, pero exige una grúa para el montaje y buen acceso al terreno.'],
            ['Construcción tradicional', 'Ladrillo, hormigón armado y terminaciones en obra. Lleva más trabajo en sitio, pero admite cambios durante la obra, ampliaciones y es lo que suelen aceptar los bancos como garantía.'],
            ['Sistemas mixtos', 'Estructura de hormigón con cerramientos livianos, o mampostería con paneles. Sirven para lograr velocidad sin perder la posibilidad de ampliar, y se estudian caso por caso.'],
        ],
        'sections' => [
            ['Casas premoldeadas', ['Una casa premoldeada se arma con piezas de hormigón (paneles, vigas, losas) que se fabrican en un taller y se llevan a obra para montarlas con grúa. Tiene la solidez del hormigón, pero cada pieza viene con medidas definidas: lo que no está en la planta original es difícil de cambiar.', 'Las casas prefabricadas livianas, de madera o paneles ligeros, son otra cosa: se transportan y arman más fácil, pero su comportamiento frente al calor, la humedad y las termitas hay que evaluarlo con cuidado. Nosotros no las construimos, y por eso te lo decimos sin vueltas.']],
            ['Qué mirar antes de decidir', ['Preguntá qué incluye el precio: platea, transporte, montaje, instalaciones y conexión a servicios. Averiguá si tu banco financia el sistema. Pensá si vas a necesitar ampliar.', 'Y mirá el clima: una casa en Asunción en pleno verano necesita aislación real, no solo un revestimiento. Si algo de esto te genera dudas, la obra tradicional es la opción más previsible.']],
        ],
        'mistakes' => [
            ['Comparar solo el precio de catálogo', 'Deja afuera platea, instalaciones y terminaciones. Se compara siempre con el mismo alcance.'],
            ['Ignorar el terreno', 'Las bases y el acceso condicionan el sistema. Se revisa antes de firmar.'],
            ['Pasar por alto la financiación', 'Muchas líneas hipotecarias piden construcción tradicional o sistemas certificados. Se consulta con el banco antes.'],
            ['Subestimar el calor', 'Un sistema liviano sin aislación se recalienta. Se pregunta cómo resuelve el techo y las paredes al sol.'],
            ['No pensar en ampliaciones', 'Un sistema modular no siempre se une a la mampostería. Si vas a ampliar, se decide desde el principio.'],
        ],
        'ideal' => ['Estás comparando presupuestos de prefabricadas con los de obra tradicional.', 'Necesitás construir rápido y querés saber el costo real de esa velocidad.', 'Vas a financiar con crédito y no sabés qué acepta el banco.'],
        'faqs' => [
            ['¿Una casa prefabricada es más barata?', 'El precio de catálogo suele no incluir platea, instalaciones, conexiones ni terminaciones. Comparado el mismo alcance, la diferencia se achica y a veces se invierte.'],
            ['¿Los bancos financian casas prefabricadas?', 'Depende del sistema y de la entidad. Muchas líneas hipotecarias exigen construcción tradicional o sistemas certificados. Consultá antes de firmar.'],
            ['¿Se puede ampliar una prefabricada?', 'Es más difícil integrar una ampliación tradicional a un sistema modular. Con mampostería, ampliar es parte del oficio.'],
            ['¿Qué diferencia hay entre prefabricada y premoldeada?', 'La premoldeada usa piezas de hormigón hechas de antemano y se monta con grúa; la prefabricada, en general, es más liviana y se arma por módulos o paneles. Ninguna es igual a construir en obra.'],
            ['¿Ustedes construyen casas prefabricadas?', 'No: construimos con sistema tradicional. Preferimos decírtelo antes que venderte algo que no hacemos.'],
        ],
        'related' => ['/casas/etapas/', '/guias/costo-casa/', '/guias/ladrillo-bloque/', '/credito/'],
    ],
];
