<?php
declare(strict_types=1);

// Especialidades de este hub: /{hub}/{slug}/. Una intencion de busqueda distinta a la del hub.
// 'related' son rutas completas. Sin precios, sin plazos fijos, sin datos inventados.
return [
    'veredas' => [
        'name' => 'Veredas y contrapisos',
        'title' => 'Veredas, contrapisos y pisos exteriores en Paraguay | Obra',
        'description' => 'Veredas, contrapisos y pisos exteriores en Asunción y Gran Asunción: base compactada, hormigón, juntas y pendientes para que no se agrieten ni junten agua.',
        'summary' => 'Construcción de veredas, contrapisos y pisos exteriores en Asunción y Gran Asunción: base compactada, hormigón, juntas y pendientes para que no se agrieten ni junten agua.',
        'h1' => 'Veredas, contrapisos y pisos exteriores',
        'kicker' => 'Base bien hecha, piso que dura',
        'intro' => [
            'La vereda o el patio de hormigón que se agrieta o junta agua casi siempre falla por la base, no por la terminación. Suelo mal compactado, sin juntas y sin pendiente: el resultado se ve al primer año.',
            'Hacemos veredas, contrapisos y pisos exteriores con base compactada, malla, juntas de dilatación y pendientes hacia los desagües, listos para recibir cerámica, adoquín o piedra.',
        ],
        'includes' => ['Movimiento de suelo y compactación', 'Contrapiso de hormigón con malla y juntas', 'Pendientes y desagües pluviales', 'Terminación: cerámica, adoquín, piedra o alisado', 'Cordones, escalones y rampas'],
        'process' => [
            ['Visita y relevamiento', 'Miramos el terreno, los niveles, dónde escurre el agua y qué hay abajo: raíces, cañerías, tanques o instalaciones. Esa información define el trabajo de base.'],
            ['Propuesta de niveles y pendientes', 'Se acuerdan alturas respecto de la casa y la calle, y las pendientes hacia los desagües. Un desnivel mínimo evita que el agua vuelva hacia las paredes.'],
            ['Presupuesto por rubro', 'Movimiento de suelo, base compactada, malla, hormigón, juntas, terminación superficial y desagües, cada rubro por separado, para ver dónde va el esfuerzo.'],
            ['Base, encofrado y hormigonado', 'Se retira la tierra blanda, se compacta la base, se arma el encofrado y la malla y se hormigona respetando las juntas. Se cuida el curado del hormigón para que no se agriete.'],
            ['Terminación y entrega', 'Alisado, llaneado rugoso, cerámica, adoquín o piedra según lo acordado. Revisamos pendientes con agua y dejamos las juntas selladas.'],
        ],
        'materials' => [
            ['Base compactada', 'Es lo que sostiene todo. Un suelo arcilloso o con relleno mal asentado se mueve con las lluvias y rompe el piso. Se compacta por capas y se agrega material de aporte si hace falta.'],
            ['Contrapiso de hormigón', 'Con malla electrosoldada y el espesor que pide el uso: peatonal, cochera o vehículos pesados. La malla y las juntas evitan que aparezcan grietas grandes.'],
            ['Pisos exteriores', 'Alisado, rodillado, cerámica antideslizante, adoquín, lajas o porcelanato exterior. Cada uno cambia la textura, el calor al sol y la limpieza.'],
            ['Juntas y bordes', 'Juntas de dilatación selladas, cordones y bordes rectos. Cortan el hormigón en paños que se mueven sin romperse.'],
            ['Desagües y rejillas', 'Canaletas, rejillas y bocas de tormenta que llevan el agua a donde corresponde y no dejan charcos.'],
        ],
        'sections' => [
            ['Contrapiso: qué es y por qué importa', ['El contrapiso es la capa de hormigón que recibe la terminación. Si está mal nivelado o sin pendiente, todo lo que se coloque arriba queda torcido o junta agua. Por eso se controla el nivel antes de dejar que endurezca.', 'También cuenta la preparación previa: un buen film o base de piedra bajo el hormigón reduce la humedad que sube y da un apoyo uniforme.']],
            ['Raíces, árboles y suelos difíciles', ['Los árboles grandes cerca de la vereda levantan el piso con sus raíces. Se planifica la distancia, se corta lo necesario y a veces se deja un borde de tierra alrededor del tronco.', 'En terrenos arcillosos, típicos de muchas zonas de Central, el suelo se hincha y se contrae con la humedad. Ahí la compactación, la malla y las juntas son todavía más importantes.']],
        ],
        'mistakes' => [
            ['Hormigonar sobre tierra suelta', 'Se hunde y se parte con la primera lluvia fuerte. La base se compacta antes.'],
            ['Sin juntas de dilatación', 'El hormigón se mueve con el calor y se raja donde quiere. Con juntas, se raja donde se dejó cortado.'],
            ['Pendiente hacia la casa', 'El agua llega a la pared y la humedad sube. Siempre se da pendiente hacia afuera.'],
            ['Terminación lisa al sol', 'Un piso pulido resbala con la lluvia y quema. Conviene una textura rugosa y colores claros.'],
            ['Ignorar las raíces', 'Terminan levantando el paño. Se resuelven al inicio.'],
        ],
        'ideal' => ['Tu patio es de tierra o de un contrapiso roto.', 'Necesitás una vereda de acceso o perimetral.', 'Querés un piso para cochera o circulación de vehículos.'],
        'faqs' => [
            ['¿Por qué se agrietó mi contrapiso anterior?', 'Casi siempre por falta de compactación, de malla o de juntas. Un contrapiso bien hecho lleva las tres cosas.'],
            ['¿Qué terminación conviene para el sol?', 'Materiales claros y rugosos: se calientan menos y no resbalan. Lo vemos según el uso.'],
            ['¿Hacen pisos para vehículos pesados?', 'Sí, con espesor y armadura calculados para la carga.'],
            ['¿Cuándo se puede pisar o pasar un auto?', 'El hormigón necesita curado antes de recibir carga. Te indicamos cuándo se puede caminar y cuándo circular con vehículos en cada obra.'],
            ['¿Se puede hacer la vereda sobre un piso viejo?', 'A veces sí, si está firme y nivelado. Si está roto o hundido se demuele y se rehace desde la base.'],
            ['¿Qué pendiente lleva una vereda?', 'Una pendiente suave hacia el desagüe, suficiente para que el agua no se quede. La definimos en obra con el nivel.'],
        ],
        'related' => ['/patios/', '/muros/', '/tinglados/cocheras/', '/guias/costo-casa/'],
    ],
    'decks' => [
        'name' => 'Decks de madera y compuesto',
        'title' => 'Construcción de decks de madera y WPC en Paraguay | Obra',
        'description' => 'Construcción de decks de madera dura y compuesto (WPC) en Asunción y Gran Asunción, para piscina, galería o patio, con estructura ventilada y anclajes ocultos.',
        'h1' => 'Construcción de decks de madera y compuesto',
        'kicker' => 'Un piso cálido alrededor de la piscina o la galería',
        'intro' => [
            'El deck cambia un patio: es cálido a la vista, agradable para pisar descalzo y resuelve desniveles sin hormigón. El secreto está debajo: una estructura ventilada, anclajes que no oxidan y madera o compuesto elegidos según el uso.',
            'Construimos decks de madera dura tratada y de compuesto (WPC) alrededor de piscinas, en galerías y como terrazas elevadas.',
        ],
        'includes' => ['Estructura de apoyo ventilada y nivelada', 'Madera dura tratada o tablas de compuesto WPC', 'Anclajes ocultos y herrajes inoxidables', 'Bordes, escalones y encuentro con la piscina', 'Tratamiento y terminación'],
        'process' => [
            ['Visita y medición', 'Vemos el lugar, medimos el área, el desnivel y el estado del piso o suelo. Miramos también el sol y dónde se acumula el agua, porque de eso depende la ventilación.'],
            ['Elección del material y el diseño', 'Se define madera dura, compuesto o mixto, la dirección de las tablas, los bordes y los escalones. También si el deck va apoyado, elevado o sobre un piso existente.'],
            ['Presupuesto por rubro', 'Estructura de apoyo, tablas, fijaciones, tratamiento, bordes y escalones, cada rubro por separado, para ver qué pesa más en la decisión.'],
            ['Estructura y colocación', 'Se arma la estructura de vigas sobre apoyos nivelados, con separación del suelo y ventilación. Después se fijan las tablas con anclajes que no se ven, dejando junta para el desagüe.'],
            ['Terminación y entrega', 'Lijado, aceite o protector y remates en bordes y escalones. Te explicamos cada cuánto renovar la terminación.'],
        ],
        'materials' => [
            ['Maderas duras', 'Especies densas y resistentes, con veta cálida. Se lijan y se protegen con aceite para conservar el color, o se dejan envejecer y tomar tono plateado.'],
            ['Compuesto WPC', 'Tablas de madera y plástico, con color parejo y poco mantenimiento. Se calientan más al sol y no tienen la calidez de la madera natural.'],
            ['Estructura de apoyo', 'Vigas de madera tratada, metal galvanizado o pilares de mampostería que separan el deck del suelo y dejan pasar el aire.'],
            ['Fijaciones y herrajes', 'Tornillos inoxidables, clips ocultos o herrajes especiales. Los de acero común se oxidan y manchan.'],
            ['Alternativas al deck', 'Porcelanato exterior, hormigón alisado o piedra en el mismo lugar. Son opciones cuando el sol o el mantenimiento son un problema.'],
        ],
        'sections' => [
            ['Deck alrededor de la piscina', ['Junto al agua el deck se moja seguido, así que la estructura tiene que drenar y las tablas tienen que ser antideslizantes. Se deja una junta pequeña entre tablas y un borde que evite que el agua pase por debajo del piso hacia la pared.', 'Se prevé el encuentro con la piscina, los escalones y las cañerías del equipo, para que el deck se pueda abrir en un tramo si hace falta acceder a algo.']],
            ['Por qué el deck se separa del suelo', ['La madera que toca la tierra o queda sin aire se pudre. Por eso el deck lleva una cámara ventilada por debajo, con apoyos que no absorban agua y una pendiente suave que lleve la lluvia hacia afuera.', 'Con esa ventilación y un mantenimiento simple, un deck bien hecho dura mucho más que uno pegado al suelo.']],
        ],
        'mistakes' => [
            ['Apoyar la madera sobre la tierra', 'Se pudre en pocas temporadas. Siempre va elevada y ventilada.'],
            ['Tornillos comunes a la vista', 'Se oxidan y dejan marcas oscuras. Se usan fijaciones inoxidables u ocultas.'],
            ['Sin junta entre tablas', 'La madera se hincha con la humedad y se deforma. Se deja una separación para que respire.'],
            ['Deck sin desagüe', 'El agua se acumula y aparecen hongos. Se prevé pendiente y salida.'],
            ['Elegir el material solo por el aspecto', 'Sin pensar en sol y limpieza, después molesta. Se compara uso, calor y mantenimiento.'],
        ],
        'ideal' => ['Querés un piso agradable alrededor de la piscina.', 'Tenés un desnivel en el patio que el deck puede resolver.', 'Buscás renovar una galería sin obra húmeda.'],
        'faqs' => [
            ['¿Madera o compuesto?', 'La madera es más noble y necesita mantenimiento; el compuesto casi no lo necesita pero se calienta más al sol. Depende del uso y de cuánto lo querés cuidar.'],
            ['¿El deck aguanta el clima paraguayo?', 'Sí, con madera dura bien tratada o compuesto de calidad y una estructura ventilada que no acumule agua.'],
            ['¿Se puede hacer sobre un piso existente?', 'Sí, si el piso está nivelado y tiene desagüe. Es una forma rápida de renovar.'],
            ['¿Cada cuánto hay que renovar la madera?', 'Depende de cuánto sol y lluvia recibe. Un aceitado periódico mantiene el color y cierra la superficie; lo explicamos al entregar.'],
            ['¿Se puede hacer un deck elevado con escalera?', 'Sí. Se calcula la estructura para la altura y la carga, con barandas si corresponde.'],
            ['¿Qué conviene cerca de la piscina?', 'Cualquiera de los dos funciona si es antideslizante y drena. Lo importante es que no queme los pies y que la estructura respire.'],
        ],
        'related' => ['/piscinas/', '/patios/pergolas/', '/patios/', '/guias/costo-casa/'],
    ],
    'pergolas' => [
        'name' => 'Pérgolas y galerías livianas',
        'title' => 'Construcción de pérgolas en Paraguay | Obra',
        'description' => 'Pérgolas de madera, metal y hormigón en Asunción y Gran Asunción: sombra para el patio, cochera o piscina con cubierta de policarbonato, chapa o vegetal.',
        'h1' => 'Construcción de pérgolas y galerías livianas',
        'kicker' => 'Sombra sin cerrar el patio',
        'intro' => [
            'Una pérgola da sombra sin encerrar. Sirve para el sector de la piscina, el acceso, la cochera o una galería que no justifica un techo completo. Puede quedar abierta o llevar cubierta de policarbonato, chapa o enredadera.',
            'Construimos pérgolas de madera dura, metal y hormigón, con fundaciones que aguantan viento y una cubierta elegida según lo que querés: sombra, protección de lluvia o las dos.',
        ],
        'includes' => ['Fundaciones y columnas', 'Estructura de madera, metal o hormigón', 'Cubierta: abierta, policarbonato, chapa o vegetal', 'Desagües cuando la cubierta es cerrada', 'Iluminación y ventiladores'],
        'process' => [
            ['Visita y medición', 'Vemos el sector, medimos el ancho y el largo, la altura libre y la posición del sol. También revisamos la casa, el muro o la columna donde puede apoyarse.'],
            ['Definición de estructura y cubierta', 'Se elige el material de la estructura, la separación de las vigas y el tipo de cubierta: abierta, policarbonato, lona, chapa o vegetal.'],
            ['Presupuesto por rubro', 'Fundaciones, columnas, vigas, cubierta, desagües e iluminación, cada uno por separado, para que sepas qué implica cada decisión.'],
            ['Fundaciones y estructura', 'Se hacen las bases de hormigón para las columnas y se levanta la estructura con anclajes que resistan viento. Si va apoyada en la casa, se fija a un elemento resistente.'],
            ['Cubierta y terminación', 'Se coloca la cubierta, se remata con protección y pintura o aceite, y se conectan luces y ventiladores si están previstos.'],
        ],
        'materials' => [
            ['Madera dura', 'Cálida, con veta a la vista, pide tratamiento y una terminación que se renueva con los años. Se usa mucho junto a galerías y en el sector de la piscina.'],
            ['Metal', 'Perfiles de acero galvanizado o tubos pintados. Casi no necesitan mantenimiento y permiten luces grandes con secciones finas.'],
            ['Hormigón', 'Columnas y vigas premoldeadas o hormigonadas en obra. Es la solución más duradera y encaja con la arquitectura de la casa.'],
            ['Cubiertas cerradas', 'Policarbonato para dejar pasar luz, chapa para máxima protección o lona para una solución liviana. Todas necesitan pendiente y desagüe.'],
            ['Cubiertas naturales', 'Enredaderas y cañas dan sombra fresca. Requieren riego, poda y una estructura que soporte el peso de la planta.'],
        ],
        'sections' => [
            ['Anclajes y viento', ['La pérgola trabaja como una vela: el viento la empuja y también la levanta. Por eso las columnas se fundan sobre bases de hormigón y los anclajes se dimensionan para tirar y no solo para apoyar.', 'En zonas abiertas o con tormentas fuertes conviene reforzar las uniones y evitar cubiertas livianas sin sujeción.']],
            ['Pérgola, galería o quincho: cuándo conviene cada una', ['La pérgola filtra el sol y deja pasar el aire. Una galería cubierta protege de la lluvia con techo completo, y un quincho suma cerramiento y servicios. Si dudás entre una y otra, en la visita se ve qué resuelve tu caso.', 'Muchas pérgolas se transforman después en galería sumando una cubierta cerrada, por eso se prevé la estructura para esa posibilidad.']],
        ],
        'mistakes' => [
            ['Columnas sin fundación', 'El viento las mueve o las vuelca. Cada columna va sobre una base de hormigón.'],
            ['Cubierta cerrada sin desagüe', 'El agua se acumula o cae donde no debe. Se prevé pendiente y canaleta.'],
            ['Madera sin tratamiento', 'A la intemperie se agrieta y se ennegrece rápido. Se protege antes de colocar.'],
            ['Calcular la sombra mal', 'Sin mirar la posición del sol, la pérgola sombrea a las tres de la tarde y no a las cuatro. Se estudia orientación y separación de vigas.'],
            ['Apoyar en paredes que no aguantan', 'Se agrietan con el peso. Se verifica el muro o se usan columnas propias.'],
        ],
        'ideal' => ['Necesitás sombra en el patio o en la piscina.', 'Querés un acceso cubierto sin obra pesada.', 'Buscás una cochera liviana.'],
        'faqs' => [
            ['¿Una pérgola protege de la lluvia?', 'Solo si lleva cubierta cerrada (policarbonato o chapa) y desagües. Una pérgola abierta filtra el sol, no el agua.'],
            ['¿Qué material dura más?', 'Metal galvanizado y hormigón casi no necesitan mantenimiento; la madera necesita tratamiento periódico pero es más cálida.'],
            ['¿Necesita permiso?', 'Una pérgola abierta en general no. Con cubierta cerrada suma superficie y puede requerirlo. Lo revisamos.'],
            ['¿Se puede cubrir con plantas?', 'Sí, con enredaderas o cañas sobre una estructura resistente. Necesitan riego y poda, y tardan en cubrir.'],
            ['¿Se puede apoyar la pérgola en la pared de la casa?', 'Si el muro soporta la carga sí; si no, se hacen columnas propias. Se revisa en la visita.'],
            ['¿Qué diferencia hay con una galería?', 'La pérgola es liviana y abierta, o con cubierta parcial. La galería tiene techo completo y protege de la lluvia. Podemos hacer cualquiera.'],
        ],
        'related' => ['/patios/decks/', '/ampliaciones/galeria/', '/tinglados/cocheras/', '/guias/terreno/'],
    ],
];
