<?php
declare(strict_types=1);

// Especialidades de este hub: /{hub}/{slug}/. Una intencion de busqueda distinta a la del hub.
// 'related' son rutas completas. Sin precios, sin plazos fijos, sin datos inventados.
return [
    'chicas' => [
        'name' => 'Piscinas pequeñas para patios chicos',
        'title' => 'Piscinas pequeñas para patios chicos en Paraguay | Obra',
        'description' => 'Piscinas pequeñas de hormigón para patios chicos en Asunción y Gran Asunción: medidas a la medida del espacio, acceso de obra resuelto y vereda integrada.',
        'summary' => 'Construcción de piscinas pequeñas de hormigón para patios chicos en Asunción y Gran Asunción: medidas a la medida del espacio, acceso de obra resuelto y vereda integrada.',
        'h1' => 'Piscinas pequeñas para patios chicos',
        'kicker' => 'Una piscina real en pocos metros',
        'intro' => [
            'En Asunción, Fernando de la Mora, Luque o San Lorenzo los patios suelen ser chicos. Eso no impide tener una piscina de hormigón: cambia el diseño, no la calidad. Una piscina compacta bien ubicada aprovecha mejor el patio que una grande que no deja lugar para nada más.',
            'El desafío real en patios chicos es el acceso: por dónde entra la excavadora, dónde va la tierra, cómo se protege lo que ya existe. Lo resolvemos antes de cotizar.',
        ],
        'includes' => ['Diseño de medidas y forma según el patio real', 'Excavación manual o con máquina chica según el acceso', 'Estructura de hormigón armado y filtrado compacto', 'Vereda perimetral y unión con la galería', 'Iluminación y previsión de climatización'],
        'process' => [
            ['Visita y medición', 'Vamos al patio, medimos el espacio libre, los retiros a medianeras y la casa, y revisamos por dónde puede entrar un equipo. También miramos dónde caen el sol y la sombra a lo largo del día, porque eso define la ubicación más que la forma.'],
            ['Propuesta de medidas y ubicación', 'Con el relevamiento te proponemos una o dos alternativas de medidas, profundidad y forma, dibujadas sobre el plano real del patio. Ahí se ve cuánto espacio queda para vereda, reposeras, jardín o quincho.'],
            ['Presupuesto por rubro', 'Excavación y retiro de tierra, estructura, instalación hidráulica, equipo de filtrado, terminación interior, vereda e iluminación, cada uno por separado y en guaraníes. Así sabés qué cambia si achicás o agrandás algo.'],
            ['Excavación y estructura', 'Se excava con máquina chica o a mano según el acceso, se arma la estructura de hormigón y se dejan las cañerías previstas antes de hormigonar. En patios chicos se protege lo que ya existe: pisos, paredes y plantas.'],
            ['Terminaciones, prueba y entrega', 'Revestimiento interior, bordes, vereda y equipo. Se llena, se prueba la estanqueidad y el filtrado, y te explicamos el uso y el mantenimiento básico del equipo.'],
        ],
        'materials' => [
            ['Estructura de hormigón armado', 'Es la base de cualquier piscina que dure. En un patio chico conviene todavía más, porque la piscina queda cerca de paredes y medianeras y no admite movimientos.'],
            ['Terminación interior', 'Venecitas, cerámica para piscinas o revestimientos cementicios. Cambian el aspecto, la textura al pisar y el mantenimiento; te mostramos muestras antes de decidir.'],
            ['Bordes y vereda', 'Piedra, porcelanato antideslizante o cemento alisado. En poco espacio la vereda cumple doble función: circulación y lugar para sentarse, así que conviene elegir un material que no queme al sol.'],
            ['Filtrado compacto', 'Bomba y filtro dimensionados para el volumen real, en una casilla chica o un nicho junto a una pared. Se ubica donde no moleste por ruido y se pueda llegar para el mantenimiento.'],
            ['Opciones que suman', 'Escalón o banco interno para sentarse, iluminación sumergida y previsión de climatización para estirar la temporada. Se definen al principio para dejar las cañerías y la electricidad listas.'],
        ],
        'mistakes' => [
            ['Elegir la forma antes que el acceso', 'Si la máquina no entra, la excavación cambia de método y de ritmo. Por eso el acceso se resuelve en la visita, no el día que llega el equipo.'],
            ['Pegar la piscina a la medianera', 'Dejar poca distancia complica la estructura, el drenaje y la relación con el vecino. Se respeta un retiro y se prevé cómo escurre el agua de lluvia.'],
            ['Olvidar dónde va la tierra', 'Una excavación genera más volumen de tierra del que parece. Hay que prever dónde se acopia y cómo se retira sin trabar la calle ni el patio.'],
            ['Achicar la vereda al mínimo', 'Una piscina sin espacio alrededor se usa menos y ensucia más el agua. Mejor unos centímetros menos de espejo de agua y un borde cómodo.'],
            ['Dejar el equipo para después', 'Si no se define el lugar del filtro y las cañerías antes de hormigonar, después aparecen roturas y parches.'],
        ],
        'sections' => [
            ['Qué medidas tiene sentido considerar', ['No hay una medida única. Para refrescarse y jugar con chicos funciona una piscina compacta y poco profunda; para nadar unas brazadas conviene priorizar el largo sobre el ancho. En patios angostos, una forma rectangular alineada con el lado más largo del terreno suele aprovechar mejor el espacio que una forma curva.', 'También cuenta la profundidad: una parte baja con escalón y banco hace la piscina más usable para toda la familia, y una profundidad pareja simplifica la obra. Lo definimos con vos según quién la va a usar y cómo.']],
            ['Piscina chica y el resto del patio', ['En un patio chico la piscina no está sola: convive con la galería, el quincho, la parrilla, el tendedero o un sector de juego. Por eso la pensamos junto con los recorridos y las sombras, y si hace falta coordinamos en la misma obra la vereda, un deck o una pérgola para que todo quede resuelto de una vez.']],
        ],
        'ideal' => ['Tu patio tiene pocos metros y querés aprovecharlos.', 'La casa ya está construida y el acceso es angosto.', 'Querés piscina sin renunciar a un sector de quincho o jardín.'],
        'faqs' => [
            ['¿Cuál es la medida mínima razonable?', 'Depende del uso. Para refrescarse y jugar con chicos alcanza con medidas muy compactas; para nadar hace falta más largo. Lo definimos con vos sobre el plano del patio.'],
            ['¿Cómo entra la máquina si el pasillo es angosto?', 'Con equipos chicos o excavación manual. Es más lento pero habitual. El método se decide en la visita.'],
            ['¿Se puede hacer una piscina elevada?', 'Sí, cuando el suelo o el acceso lo justifican. Cambia la estructura y la terminación exterior.'],
            ['¿Una piscina chica necesita el mismo filtrado que una grande?', 'Necesita un equipo dimensionado para su volumen, que suele ser más chico y más fácil de ubicar. Lo importante es que el agua recircule bien; eso se define con la forma y la ubicación de las bocas.'],
            ['¿Se puede climatizar una piscina chica?', 'Sí, y en poco volumen de agua la climatización rinde más. Conviene dejar la previsión de cañerías y electricidad desde el principio, aunque el equipo se instale después.'],
        ],
        'related' => ['/piscinas/quinta/', '/patios/decks/', '/quinchos/'],
    ],
    'quinta' => [
        'name' => 'Piscinas para quintas',
        'title' => 'Construcción de piscinas para quintas en Paraguay | Obra',
        'description' => 'Piscinas de hormigón para quintas y casas de campo en Paraguay: mayor tamaño, agua de pozo, filtrado dimensionado y área de quincho y solárium integrada.',
        'h1' => 'Piscinas para quintas y casas de campo',
        'kicker' => 'Tamaño, agua propia y todo alrededor',
        'intro' => [
            'En una quinta la piscina es el centro del fin de semana. Suele ser más grande, se llena con agua de pozo y convive con quincho, galería y jardín. Eso cambia el filtrado, la vereda y la forma de cuidarla entre visita y visita.',
            'Proyectamos la piscina junto con el quincho y el solárium, y dimensionamos la instalación para agua de pozo y para períodos sin uso.',
        ],
        'includes' => ['Piscina de hormigón de mayor tamaño y profundidad variable', 'Filtrado dimensionado para agua de pozo y uso intermitente', 'Solárium, vereda amplia y ducha exterior', 'Unión con quincho y galería', 'Casilla de máquinas y previsión de climatización'],
        'process' => [
            ['Visita al terreno', 'Recorremos la quinta con vos: dónde van la casa y el quincho, por dónde entra un camión, dónde cae el sol durante el día y qué árboles hay cerca. En terreno abierto hay más libertad para ubicar la piscina, y por eso mismo más decisiones que tomar antes de excavar.'],
            ['Agua y suelo', 'Vemos de dónde va a salir el agua para el primer llenado y para las reposiciones, y cómo es el suelo. Un suelo arcilloso o una napa alta cambian la forma de excavar, de armar la estructura y de drenar.'],
            ['Presupuesto por rubro', 'Movimiento de tierra, estructura, hidráulica y filtrado, terminación interior, solárium, vereda e iluminación, cada uno por separado. Podés ajustar el alcance de un rubro sin rehacer toda la propuesta.'],
            ['Excavación y estructura', 'Se excava con máquina, se decide qué pasa con la tierra sobrante y se hormigona el vaso con las cañerías ya previstas. Se deja resuelto por dónde va a escurrir el agua de lluvia para que no entre en la piscina.'],
            ['Terminación, llenado y entrega', 'Revestimiento, bordes, solárium y casilla de máquinas. Se llena, se prueba el circuito de filtrado y te explicamos la rutina para los días en que no estás en la quinta.'],
        ],
        'materials' => [
            ['Estructura de hormigón armado', 'En una quinta la piscina es grande y queda en suelo abierto, donde el terreno se mueve con la lluvia. La estructura armada y bien apoyada es lo que evita fisuras con el tiempo.'],
            ['Terminación interior', 'Venecitas, cerámica para piscinas o revestimientos cementicios. Con agua de pozo y sol pleno conviene elegir una terminación fácil de limpiar; te mostramos muestras antes de decidir.'],
            ['Solárium y vereda amplia', 'Piedra, porcelanato antideslizante o cemento alisado. En una quinta se camina descalzo y con mucho sol, así que importa que el material no queme y que drene bien.'],
            ['Casilla de máquinas', 'Un cuarto o nicho para bomba, filtro y tablero, ventilado y con acceso cómodo. En la quinta se puede ubicar más lejos del sector de estar, para que el ruido no moleste.'],
        ],
        'sections' => [
            ['El agua de pozo y la piscina', ['Casi todas las quintas se llenan con agua de pozo, y no es un problema si se la conoce. Conviene hacer un análisis antes de llenar: el hierro puede manchar el revestimiento y la dureza deja sarro en bordes y equipos. Según el resultado se agrega un filtro previo o un tratamiento inicial.', 'También hay que pensar en la reposición. Una piscina grande pierde agua por evaporación y por uso, y el pozo tiene que poder acompañar.']],
            ['Camiones, tierra y drenaje en terreno abierto', ['Que la quinta sea grande no significa que todo sea fácil: los caminos internos pueden ser de tierra y con lluvia se ponen intransitables para un camión de hormigón. Coordinamos el acceso, el lugar donde se acopian materiales y el momento de cada entrega.', 'Lo otro es el agua de lluvia. En terreno abierto escurre con fuerza, y una piscina mal ubicada recibe barro y hojas. Se define el nivel del solárium, las pendientes de la vereda y un desagüe pluvial para que el agua se aleje del vaso.']],
            ['Una piscina para toda la familia', ['El uso de una quinta es distinto al de una casa de ciudad: llegan los abuelos, los chicos, los primos, y todos quieren estar al mismo tiempo. Por eso conviene pensar una parte baja con escalones amplios, una parte más profunda para nadar y sombra cerca para descansar.', 'La piscina se relaciona con el quincho, la parrilla y la galería. Si se piensa todo junto, se resuelven los niveles y los recorridos con pocas vueltas, y se evita que después haya que romper una vereda para pasar una cañería.']],
        ],
        'mistakes' => [
            ['Llenar sin conocer el agua', 'Un agua con hierro o mucha dureza mancha y arruina el revestimiento nuevo. Un análisis previo evita el problema y define el tratamiento.'],
            ['Ubicarla donde escurre toda la lluvia', 'Una piscina en el punto más bajo del terreno recibe barro y hojas cada vez que llueve. Se elige el lugar mirando pendientes y árboles.'],
            ['Olvidar el camino de los camiones', 'Si el acceso interno no aguanta un camión cargado, la obra se frena. Se revisa el camino y se prepara antes de la entrega.'],
        ],
        'ideal' => ['Tenés una quinta y querés la piscina como centro del espacio exterior.', 'Vas a llenar con agua de pozo.', 'Querés hacer piscina y quincho como una sola obra.'],
        'faqs' => [
            ['¿El agua de pozo sirve para la piscina?', 'Sí, con un análisis previo y un tratamiento adecuado. A veces hace falta un filtro adicional por hierro o dureza.'],
            ['¿Cómo se mantiene si voy solo los fines de semana?', 'Con un filtrado bien dimensionado, un temporizador y una rutina simple. Te dejamos el instructivo al entregar.'],
            ['¿Pueden hacer una piscina con zona para chicos?', 'Sí. Se proyecta con un sector de baja profundidad o escalones amplios.'],
            ['¿Se puede hacer la piscina antes que la casa?', 'Sí, es una secuencia común. Se deja prevista la conexión eléctrica y de agua, y se cuida que la obra posterior no dañe la vereda ni el vaso.'],
            ['¿Qué tan grande puede ser una piscina de quinta?', 'Tanto como permita el terreno y el uso. Un vaso más grande suma volumen de agua, equipo de filtrado y superficie de vereda. Lo vemos en la visita, sobre el terreno real.'],
        ],
        'related' => ['/quintas/', '/quinchos/', '/piscinas/desbordante/', '/guias/terreno/'],
    ],
    'desbordante' => [
        'name' => 'Piscinas desbordantes',
        'title' => 'Piscinas desbordantes e infinity en Paraguay | Obra',
        'description' => 'Piscinas desbordantes (infinity) en Paraguay: borde perdido, canaleta, tanque de compensación y estructura calculada para que el efecto no filtre.',
        'summary' => 'Construcción de piscinas desbordantes (infinity) en Paraguay: borde perdido, canaleta, tanque de compensación y estructura calculada para el efecto sin filtraciones.',
        'h1' => 'Piscinas desbordantes e infinity',
        'kicker' => 'El borde perdido bien resuelto',
        'intro' => [
            'Una piscina desbordante se ve simple y es técnicamente la más exigente: el agua tiene que pasar el borde de forma pareja, caer a una canaleta y volver desde un tanque de compensación. Un desnivel de milímetros en el borde se nota.',
            'Ejecutamos piscinas desbordantes de uno o varios lados, con la nivelación del borde controlada y la instalación hidráulica dimensionada para el caudal real.',
        ],
        'includes' => ['Estructura con muro de desborde y canaleta', 'Tanque de compensación y bombas dimensionadas', 'Nivelación de precisión del borde', 'Revestimiento continuo y borde de terminación', 'Iluminación y automatización de nivel'],
        'process' => [
            ['Visita y análisis del terreno', 'Vemos el desnivel, la vista, el suelo y el acceso. Una desbordante necesita una base firme y controlada: si el terreno tiene pendiente, se define cómo se contiene la tierra y hacia qué lado cae el agua.'],
            ['Definición del borde y del tanque', 'Se decide cuántos lados desbordan, dónde va la canaleta y dónde se ubica el tanque de compensación. El tanque tiene que caber, tener acceso para mantenimiento y quedar a un nivel que permita el retorno del agua.'],
            ['Presupuesto por rubro', 'Estructura del vaso y del muro de desborde, canaleta, tanque, bombas y cañerías, revestimiento, iluminación y automatización de nivel. Cada rubro por separado, para ver qué pesa más en tu caso.'],
            ['Estructura y nivelación', 'Se hormigona el vaso, el muro y la canaleta con instrumentos de nivel. El borde del desborde se controla en varias etapas, porque de eso depende que el agua caiga pareja en todo su largo.'],
            ['Pruebas y entrega', 'Se llena, se ajusta el caudal hasta que la lámina de agua sea uniforme, se prueban bombas y niveles y se verifica que no haya pérdidas en la canaleta ni en el tanque. Te mostramos cómo se opera el sistema.'],
        ],
        'materials' => [
            ['Muro de desborde y canaleta', 'Es la parte crítica: una estructura de hormigón armado con el borde perfectamente horizontal y una canaleta con pendiente hacia el tanque. Las juntas se sellan con cuidado.'],
            ['Tanque de compensación', 'Un depósito enterrado o semienterrado que recibe el agua que cae y la devuelve al vaso. Se dimensiona según el volumen de la piscina y la longitud del borde.'],
            ['Revestimiento del borde', 'Venecitas, cerámica o piedra en el labio de desborde. Un material continuo y bien colocado ayuda a que el agua escurra pareja y no se marque.'],
            ['Bombas y automatización', 'Bombas de recirculación separadas para el filtrado y el retorno, y un control de nivel que mantiene el tanque en el rango correcto sin que tengas que estar pendiente.'],
        ],
        'sections' => [
            ['Cómo funciona el sistema de desborde', ['El agua sube hasta el borde y lo pasa en una lámina fina, cae a una canaleta y baja al tanque de compensación. Desde ahí una bomba la devuelve al vaso pasando por el filtro. El tanque además absorbe el volumen que se desplaza cuando entra gente a la piscina.', 'Como todo depende de que el borde esté a un mismo nivel, el trabajo se hace con instrumentos y se revisa antes de revestir. Un error pequeño en un lado se traduce en una lámina que corre de un solo lado.']],
            ['Terreno con desnivel o patio plano', ['Con barranca o pendiente, el borde perdido aprovecha la vista y el muro de contención hace doble función. Ahí lo importante es la estabilidad del suelo y el drenaje detrás del muro, sobre todo con las lluvias fuertes de la zona.', 'En un patio plano se construye un vaso elevado o semielevado que genera el mismo efecto. Cambia la estructura y la terminación exterior, pero el sistema hidráulico es el mismo.']],
        ],
        'mistakes' => [
            ['Tratar el borde como un detalle de terminación', 'El borde es estructura. Si no queda a nivel desde el hormigón, ningún revestimiento lo corrige después.'],
            ['Subdimensionar el tanque', 'Un tanque chico se vacía o se desborda con el uso normal. Se calcula con el volumen del vaso y la cantidad de bordes.'],
            ['Olvidar el acceso al tanque', 'Si queda enterrado sin tapa ni paso, el mantenimiento se vuelve una rotura. Se deja registro y espacio de trabajo.'],
            ['No prever la evaporación', 'En días de calor y viento el agua baja más rápido. El control de nivel y la reposición automática lo compensan.'],
        ],
        'ideal' => ['Tu terreno tiene desnivel o vista y querés aprovecharlos.', 'Buscás una piscina de diseño con terminación de alto nivel.', 'Ya tenés un proyecto de arquitectura con piscina desbordante.'],
        'faqs' => [
            ['¿Una desbordante gasta más agua?', 'Pierde algo más por evaporación y salpicadura, pero el tanque de compensación recupera el agua del desborde. Con una instalación bien hecha, el consumo es razonable.'],
            ['¿Se puede hacer en un patio plano?', 'Sí. El efecto de borde perdido funciona con un desnivel construido; no hace falta una barranca.'],
            ['¿Es mucho más cara que una piscina común?', 'Suma estructura, tanque y bombas. Cuánto más depende del tamaño y de cuántos lados desbordan. Se ve en el cómputo por rubro.'],
            ['¿Cuántos lados pueden desbordar?', 'Uno, dos o los cuatro, según el proyecto y el terreno. Cuantos más lados, más largo de borde para nivelar, más canaleta y un tanque mayor.'],
            ['¿Requiere mantenimiento especial?', 'El de cualquier piscina más la limpieza de la canaleta y la revisión del nivel del tanque. Con una rutina simple no da trabajo extra.'],
            ['¿Se puede convertir una piscina común en desbordante?', 'En general implica cambiar el borde y sumar canaleta y tanque, casi como rehacer la estructura. Se evalúa caso por caso.'],
        ],
        'related' => ['/piscinas/quinta/', '/casas/minimalistas/', '/patios/decks/', '/guias/costo-casa/'],
    ],
    'renovacion' => [
        'name' => 'Renovación y reparación de piscinas',
        'title' => 'Renovación y reparación de piscinas en Paraguay | Obra',
        'description' => 'Renovación de piscinas en Asunción y Gran Asunción: pérdidas de agua, revestimiento, vereda, filtrado e iluminación renovados sin construir de nuevo.',
        'h1' => 'Renovación y reparación de piscinas',
        'kicker' => 'Recuperá la piscina que ya tenés',
        'intro' => [
            'Una piscina de hormigón vieja casi siempre se puede recuperar: se detecta la pérdida, se repara la estructura o la cañería, se cambia el revestimiento y se renueva el filtrado. Sale mucho menos que hacer una nueva.',
            'Empezamos con una prueba de pérdida y una revisión de la instalación. Con eso sabemos si el problema es de estructura, de cañería o de equipos, y cotizamos lo que corresponde.',
        ],
        'includes' => ['Detección de pérdidas en vaso y cañerías', 'Reparación estructural y sellado', 'Cambio de revestimiento: venecitas, cerámica o pintura', 'Renovación de filtro, bomba e iluminación', 'Vereda nueva y bordes'],
        'process' => [
            ['Visita y diagnóstico', 'Vemos el estado del vaso, del revestimiento, de la vereda y de los equipos, y te preguntamos desde cuándo notás el problema. Con eso decidimos qué pruebas hacen falta.'],
            ['Prueba de pérdida', 'Se marca el nivel del agua con el filtrado apagado y con el circuito funcionando, y se presurizan las cañerías. Así se distingue si el agua se va por una fisura, por una pieza o por una cañería.'],
            ['Alcance y presupuesto por rubro', 'Reparación estructural, revestimiento, equipos, vereda e iluminación, cada uno por separado. Podés decidir qué se hace ahora y qué queda para más adelante.'],
            ['Reparación y terminación', 'Se vacía la piscina, se abren y sellan las fisuras, se repara lo que corresponde y se revoca o revistiene el interior. Se cambian las piezas que fallan y se renuevan bordes y vereda si hace falta.'],
            ['Llenado, prueba y entrega', 'Se llena, se verifica que no haya pérdidas, se arranca el equipo y te explicamos cómo cuidar lo nuevo.'],
        ],
        'materials' => [
            ['Revestimiento interior', 'Venecitas, cerámica para piscinas, revestimiento cementicio o pintura especial. Cambia la durabilidad, el aspecto y la textura; se elige según el estado de la base.'],
            ['Sellado y reparación estructural', 'Fisuras y juntas se tratan con morteros y selladores específicos para inmersión permanente. No sirve cualquier masilla.'],
            ['Equipo de filtrado', 'Filtro, bomba y cañerías nuevas o solo lo que falla. Si el equipo es de otra época, cambiarlo suele bajar el consumo y mejorar el agua.'],
            ['Vereda y bordes', 'Reemplazo de la vereda rota o resbalosa, con material antideslizante y pendiente hacia el desagüe.'],
        ],
        'sections' => [
            ['Señales de que la piscina tiene una pérdida', ['El nivel baja más de lo que explicaría el calor, aparece humedad o una zona hundida junto al vaso, la bomba trabaja sin parar o hay que reponer agua con frecuencia. A veces el problema es una pieza de succión o una cañería enterrada y no el hormigón.', 'Conviene no seguir reponiendo agua sin averiguar por qué. Cuanto más tiempo pasa, más suelo se lava alrededor y más grande se vuelve la reparación.']],
            ['Reparar o rehacer', ['Si la estructura está sana y las fisuras son localizadas, casi siempre se repara. Si hay un vaso deformado, una losa fracturada o el suelo cedió, hay que evaluar una intervención mayor.', 'La decisión se toma con el diagnóstico y con lo que querés lograr: recuperar la piscina como estaba o aprovechar para cambiar escalones, profundidad o vereda. No se decide antes de medir la pérdida.']],
        ],
        'mistakes' => [
            ['Pintar sobre una pérdida', 'La pintura tapa un problema que sigue creciendo. Primero se encuentra y se sella la causa.'],
            ['Cambiar el revestimiento sin revisar la base', 'Si el fondo está flojo, el revestimiento nuevo se despega. Se repara la base antes de revestir.'],
            ['Renovar los equipos y dejar cañerías viejas', 'Un filtro nuevo con cañerías con pérdidas no resuelve nada. Se revisa el circuito completo.'],
            ['Vaciar sin considerar la napa', 'Una piscina vacía con napa alta puede flotar o levantarse. Se planifica cómo y cuándo vaciarla.'],
        ],
        'ideal' => ['La piscina pierde agua y no sabés por dónde.', 'El revestimiento está roto o manchado.', 'Compraste una casa con piscina en mal estado.'],
        'faqs' => [
            ['¿Cómo saben si pierde por la estructura o por la cañería?', 'Con pruebas de nivel con y sin el circuito de filtrado, y presurizando las cañerías. Es el primer paso antes de cotizar.'],
            ['¿Se puede cambiar la forma de una piscina existente?', 'Dentro de ciertos límites: reducir profundidad, agregar escalones o un sector para chicos. Ampliar el vaso es más complejo.'],
            ['¿Cuánto tiempo queda sin uso?', 'Depende del alcance. Un cambio de revestimiento es distinto a una reparación estructural. Lo detallamos en la propuesta.'],
            ['¿Es normal que una piscina pierda algo de agua?', 'Baja por evaporación y uso, sobre todo en verano. Una pérdida real se nota porque el nivel sigue bajando aun con el filtrado apagado y con clima fresco.'],
            ['¿Se puede reparar sin vaciar la piscina?', 'Algunas cañerías o piezas sí. Las fisuras del vaso y el revestimiento requieren vaciarla. Lo definimos con el diagnóstico.'],
            ['¿Cuándo conviene consultar?', 'Antes del calor, para tener tiempo de diagnosticar y reparar sin apuro. Igual trabajamos todo el año.'],
        ],
        'related' => ['/piscinas/', '/quintas/refaccion/', '/patios/veredas/', '/guias/costo-casa/'],
    ],
];
