<?php
declare(strict_types=1);

// Especialidades de este hub: /{hub}/{slug}/. Una intencion de busqueda distinta a la del hub.
// 'related' son rutas completas. Sin precios, sin plazos fijos, sin datos inventados.
return [
    'cerrados' => [
        'name' => 'Quinchos cerrados',
        'title' => 'Construcción de quinchos cerrados en Paraguay | Obra',
        'description' => 'Quinchos cerrados con aberturas, aire acondicionado y baño en Asunción y Gran Asunción: para usarlos en verano con calor y en invierno con frío.',
        'h1' => 'Construcción de quinchos cerrados',
        'kicker' => 'Un ambiente más, todo el año',
        'intro' => [
            'El quincho cerrado se convirtió en el ambiente más usado de muchas casas: comedor de fin de semana, sala de juegos, lugar para recibir. Cerrarlo bien exige resolver el humo de la parrilla, la ventilación y la climatización.',
            'Construimos quinchos cerrados con aberturas corredizas para abrirlos en los días lindos, extracción de humo dimensionada y previsión de aire acondicionado.',
        ],
        'includes' => ['Cerramiento con aberturas corredizas de aluminio o PVC', 'Campana y extracción de humo dimensionadas', 'Previsión de aire acondicionado e instalación eléctrica', 'Baño y kitchenette', 'Aislación térmica en el techo'],
        'process' => [
            ['Visita y relevamiento', 'Miramos el quincho o el lugar donde va, cómo pega el sol de la tarde, hacia dónde sopla el viento y cuánta gente lo va a usar a la vez. Con eso se decide dónde va la parrilla, dónde la cocina y dónde el baño.'],
            ['Definición de ventilación y humo', 'Antes de cerrar nada se resuelve por dónde entra el aire y por dónde sale el humo. Es la decisión que más condiciona el resto: la altura del techo, el tamaño de la campana y la posición de las aberturas dependen de ella.'],
            ['Presupuesto por rubro', 'Mampostería, estructura y techo, instalación eléctrica y sanitaria, campana y ducto, colocación de aberturas y terminaciones, cada rubro por separado. Así podés comparar y ajustar sin perder de vista el conjunto.'],
            ['Obra civil y cerramiento', 'Se levantan paredes, se prepara el piso y se deja lista la instalación: desagües del baño y la cocina, caños del aire acondicionado, tomas y luces. Después se colocan las aberturas sobre vanos ya nivelados.'],
            ['Terminaciones y entrega', 'Revoques, pintura, revestimientos y mesadas. Probamos la extracción con fuego real, revisamos que las aberturas cierren bien y te explicamos cómo limpiar el ducto y la campana.'],
        ],
        'materials' => [
            ['Paredes y cerramiento', 'Mampostería de ladrillo o bloque para los sectores macizos y grandes paños vidriados o corredizos para abrir el quincho al patio. La mezcla depende de cuánto querés que el ambiente se sienta jardín y cuánto sala.'],
            ['Aberturas', 'Corredizas de aluminio o PVC, con o sin vidrio doble. Nosotros preparamos los vanos, colocamos y sellamos para que no entre agua ni polvo.'],
            ['Piso interior', 'Porcelanato o cerámica antideslizante, fáciles de limpiar después de un asado. En el sector de la parrilla conviene un material que resista grasa y calor.'],
            ['Techo y aislación', 'Tejas con cielorraso, chapa con aislación o estructura de madera con machimbre. El techo es lo que más pesa en el confort de un quincho cerrado en verano.'],
            ['Climatización', 'Previsión para equipos split, ventiladores de techo o ambos. Dejamos cañerías, desagües y electricidad listos aunque el equipo se compre después.'],
        ],
        'sections' => [
            ['Humo, campana y ventilación en un quincho cerrado', ['El humo es el punto débil de un quincho cerrado. La campana tiene que cubrir la parrilla con margen, el ducto tiene que subir con recorrido corto y sin codos innecesarios, y el aire que sale tiene que reponerse por otro lado: una rejilla baja o una abertura que se pueda dejar entreabierta.', 'Con la parrilla prendida y todo cerrado, el ambiente se llena de humo aunque la campana sea grande, porque no tiene de dónde tomar aire. Por eso el aire de reposición se diseña junto con la extracción y no después.']],
            ['Baño, cocina y confort todo el año', ['Un quincho cerrado suele sumar baño y kitchenette para no cruzar la casa con las manos llenas. Se ubican del lado por donde pasan las cañerías existentes y lejos del calor de la parrilla, con ventilación propia.', 'Para el calor de Asunción y Central cuentan más el techo aislado, los aleros y el cruce de ventilación que el aire acondicionado solo. Para el frío de invierno ayudan las aberturas bien selladas y la posibilidad de cerrar sin dejar rendijas.']],
        ],
        'mistakes' => [
            ['Cerrar y después pensar el humo', 'Sumar una campana a un quincho ya cerrado obliga a romper techo y paredes. Se define antes de levantar las aberturas.'],
            ['Aberturas que no dejan respirar', 'Un quincho todo vidriado y fijo es un invernadero. Conviene combinar paños corredizos con sectores que se abran del todo.'],
            ['Sin desagüe para el baño o la bacha', 'Los desagües se pasan antes del contrapiso. Después, cualquier corrección es rotura de piso.'],
            ['Techo sin aislación', 'Con chapa o teja sin cielorraso ni aislante, el quincho cerrado se vuelve inusable en la siesta de verano.'],
            ['No considerar la superficie cubierta', 'Cerrar suma metros que pueden requerir trámite en el municipio. Se consulta al principio, no cuando llega la inspección.'],
        ],
        'ideal' => ['Usás el quincho todo el año y el calor o el frío lo limitan.', 'Querés un ambiente de recepción separado de la casa.', 'Tenés un quincho abierto y querés cerrarlo.'],
        'faqs' => [
            ['¿La parrilla funciona bien en un quincho cerrado?', 'Sí, con una campana correcta, un ducto bien dimensionado y una entrada de aire. Sin eso, el humo se queda adentro.'],
            ['¿Se puede cerrar un quincho existente?', 'Sí. Revisamos la estructura, el techo y el piso y proponemos el cerramiento que corresponde.'],
            ['¿Necesita permiso municipal?', 'Un quincho cerrado suma superficie cubierta. Lo revisamos y coordinamos la documentación si corresponde.'],
            ['¿Cuánta ventilación necesita un quincho cerrado con parrilla?', 'Lo suficiente para reponer el aire que sale por la campana. Se resuelve con rejillas o aberturas superiores e inferiores que se puedan dejar abiertas mientras se cocina.'],
            ['¿Se puede usar carbón y leña adentro?', 'Sí, si el ducto, la campana y la entrada de aire están bien dimensionados. Es justamente el punto que revisamos primero en la visita.'],
            ['¿Conviene aire acondicionado o alcanza con ventiladores?', 'Depende del tamaño y de cuánto uses el quincho en verano. Dejamos la previsión para equipo split y ventiladores de techo, y vos decidís qué instalar.'],
        ],
        'related' => ['/quinchos/parrillas/', '/quinchos/techo-madera/', '/ampliaciones/galeria/', '/guias/costo-casa/'],
        'link' => ['site' => 'carpinteria', 'path' => '/aberturas/', 'text' => 'Las aberturas de aluminio, el blindex y las puertas del quincho cerrado las fabrica carpinteria.com.py, del mismo grupo; la obra civil y la colocación quedan a nuestro cargo.'],
    ],
    'parrillas' => [
        'name' => 'Parrillas y asadores',
        'title' => 'Construcción de parrillas y asadores en Paraguay | Obra',
        'description' => 'Construcción de parrillas de ladrillo, asadores y hornos en Asunción y Gran Asunción: tiro correcto, mesada, bacha y fogón a la altura justa.',
        'h1' => 'Construcción de parrillas y asadores',
        'kicker' => 'El corazón del quincho',
        'intro' => [
            'Una parrilla que tira mal arruina el quincho. El tiro, la altura del fogón, el ancho de la boca y la campana se calculan, no se improvisan. Construimos parrillas de ladrillo refractario con mesada, bacha y espacio para leña o carbón.',
            'Podemos hacer la parrilla sola, dentro de un quincho existente, o como parte de un quincho nuevo.',
        ],
        'includes' => ['Parrilla de ladrillo refractario con tiro calculado', 'Campana y chimenea', 'Mesada de granito u hormigón con bacha', 'Horno de barro o de ladrillo opcional', 'Leñero y espacio de guardado'],
        'process' => [
            ['Visita y ubicación', 'Miramos dónde va la parrilla, hacia dónde sopla el viento, qué hay arriba (techo, aleros, árboles) y cómo llega el humo a los vecinos. Una parrilla mal ubicada molesta aunque esté bien construida.'],
            ['Definición de medidas y tipo', 'Se acuerda el largo de la parrilla, la altura del fogón, si lleva horno, fogón lateral o asador de cordero, y cuánta mesada querés a cada lado. Se dibuja sobre el lugar real para que se vea qué queda libre.'],
            ['Presupuesto por rubro', 'Base y estructura, refractarios, campana y chimenea, mesada con bacha, revestimientos e instalación de gas si corresponde. Cada rubro por separado para poder ajustar.'],
            ['Construcción', 'Se levanta la base, se arma el fogón con ladrillo refractario, se monta la boca y la campana y se sube la chimenea. La mesada y la bacha se hacen con las cañerías ya previstas.'],
            ['Curado y entrega', 'Los refractarios necesitan un primer encendido suave para que sequen sin fisurarse. Te lo explicamos, probamos el tiro con fuego y dejamos todo limpio.'],
        ],
        'materials' => [
            ['Ladrillo refractario', 'Es el que soporta el calor directo del fuego sin agrietarse. El ladrillo común se raja con la temperatura y no sirve en el fogón.'],
            ['Parrilla y accesorios', 'Parrillas de hierro con altura regulable, chapa para asar y sistema para subir o bajar la brasa. Se elige según el tipo de asado que hacés habitualmente.'],
            ['Campana y chimenea', 'De chapa, de mampostería o revestida, con la sección y la altura que necesita el tiro. La terminación exterior se hace para que no entre agua de lluvia por arriba.'],
            ['Mesada y bacha', 'Granito, hormigón alisado o piedra, con bacha y grifería. Conviene que resista grasa y calor y que sea fácil de limpiar.'],
            ['Horno y opciones', 'Horno de barro o de ladrillo, fogón para leña, leñero y espacio para guardar carbón. Se definen al inicio, porque cambian la base.'],
        ],
        'sections' => [
            ['Cómo tiene que tirar una parrilla de obra', ['El tiro depende de tres cosas que funcionan juntas: el tamaño de la boca, la campana y la chimenea. Si la campana es chica el humo se escapa por los costados; si la chimenea es corta o tiene curvas, no jala; si la boca es alta, entra más aire del que el ducto puede sacar.', 'Por eso se calculan juntas y se prueban con fuego antes de dar la obra por terminada. Cuando una parrilla existente tira mal, casi siempre se corrige tocando una de esas tres piezas, sin rehacerla entera.']],
            ['Parrilla a leña, carbón o gas', ['La parrilla tradicional de obra trabaja con leña o carbón y necesita chimenea. Si preferís gas, preparamos la obra civil: nicho para el equipo, ventilación obligatoria, caño de alimentación y campana. El artefacto lo elegís vos.', 'Algunas familias combinan: una parrilla a leña para los asados largos y un anafe o cocina a gas en la mesada para lo cotidiano. Se puede prever desde el inicio y así no hay que romper después.']],
        ],
        'mistakes' => [
            ['Usar ladrillo común en el fogón', 'Se agrieta con el calor. El refractario se usa donde llega el fuego y el común queda para el resto.'],
            ['Chimenea baja o con muchos codos', 'Frena el humo. Conviene un recorrido recto y una altura que supere el techo.'],
            ['Parrilla demasiado alta o demasiado baja', 'Se usa incómoda o se pierde control del fuego. La altura se prueba con quien hace el asado antes de definirla.'],
            ['Dejar la mesada para después', 'Sin espacio al lado, el asado se vuelve un malabar. La mesada y la bacha se planean con la parrilla.'],
            ['Prender a pleno el primer día', 'El refractario nuevo necesita curarse con fuego suave. Sin eso puede fisurarse.'],
        ],
        'ideal' => ['Tu parrilla actual llena el quincho de humo.', 'Querés sumar una parrilla a una galería existente.', 'Buscás una parrilla con horno y mesada integrada.'],
        'faqs' => [
            ['¿Por qué mi parrilla tira mal?', 'Casi siempre por una campana mal proporcionada, una chimenea corta o sin salida libre, o una boca demasiado alta. Se puede corregir.'],
            ['¿Hacen parrillas a gas o eléctricas?', 'Preparamos la obra civil y las instalaciones para equipos a gas; el equipo lo elegís vos.'],
            ['¿Cuánto tarda construir una parrilla?', 'Es una obra corta comparada con un quincho completo. El plazo se define con el alcance y el secado de los materiales refractarios.'],
            ['¿Se puede hacer una parrilla dentro de un quincho ya construido?', 'Sí. Se revisa el techo, la ventilación y el piso, y se define dónde puede ir la chimenea sin cortar la estructura.'],
            ['¿Qué es un asador y en qué se diferencia de una parrilla?', 'El asador es un fogón abierto donde la carne se cocina cerca de la brasa o inclinada frente al fuego; la parrilla usa rejilla horizontal. Se pueden combinar en una misma obra.'],
            ['¿Necesita mantenimiento?', 'Limpiar hollín y cenizas de la chimenea de vez en cuando y revisar el estado del refractario. Lo explicamos al entregar.'],
        ],
        'related' => ['/quinchos/', '/quinchos/cerrados/', '/patios/pergolas/', '/guias/ladrillo-bloque/'],
    ],
    'techo-madera' => [
        'name' => 'Quinchos con techo de madera',
        'title' => 'Quinchos con techo de madera y machimbre en Paraguay | Obra',
        'description' => 'Quinchos con techo de madera y machimbre en Asunción y Gran Asunción: estructura, cielorraso de machimbre y tejas construidos de principio a fin.',
        'summary' => 'Construcción de quinchos con estructura de madera, cielorraso de machimbre y tejas en Asunción y Gran Asunción, con la madera y la obra civil a cargo del mismo equipo.',
        'h1' => 'Quinchos con techo de madera y machimbre',
        'kicker' => 'Madera vista, bien tratada',
        'intro' => [
            'El techo de madera con machimbre es el clásico del quincho paraguayo: cálido, fresco y con un olor que ningún otro material da. Requiere madera bien estacionada, tratamiento contra insectos y humedad, y una estructura calculada para el peso de la teja.',
            'La estructura de madera, el machimbre y la cubierta los resolvemos dentro de la misma obra, junto con la obra civil del quincho: un solo responsable para todo el techo, desde los apoyos hasta la última tabla, y una sola conversación para coordinar medidas, madera y terminaciones.',
        ],
        'includes' => ['Estructura de madera dura: tijeras, cabriadas o vigas vistas', 'Cielorraso de machimbre con aislación', 'Cubierta de teja colonial, francesa o chapa', 'Tratamiento y terminación de la madera', 'Columnas de mampostería o madera'],
        'process' => [
            ['Visita y medición', 'Vemos el quincho, la galería o la casa donde va el techo, medimos luces y apoyos y revisamos el estado de las paredes o columnas que van a cargarlo.'],
            ['Elección de madera y cubierta', 'Se define la especie, el tipo de estructura (cabriadas, tijeras, vigas vistas), el machimbre del cielorraso y la cubierta de teja o chapa. También cuánta altura libre querés y si el techo queda a la vista.'],
            ['Presupuesto por rubro', 'Estructura, machimbre, aislación, cubierta y tratamiento de la madera, cada uno por separado. Así ves dónde pesa la decisión de especie o de teja.'],
            ['Estructura, machimbre y cubierta', 'Se apoyan y fijan las vigas, se arma el entablado, se coloca la aislación y se termina la cubierta. El machimbre va después de que el techo esté cerrado, para que no se moje.'],
            ['Tratamiento y entrega', 'Se aplica el protector y la terminación, se revisan encuentros y aleros y te dejamos un plan de mantenimiento simple.'],
        ],
        'materials' => [
            ['Especies de madera dura', 'Se eligen según disponibilidad, estabilidad y aspecto: lapacho, curupay o similares. Cada especie se comporta distinto con el sol y la humedad, y conviene que la madera llegue seca.'],
            ['Machimbre del cielorraso', 'Tablas con unión macho y hembra que forman un cielorraso continuo. Pueden ir de madera nativa o de especies más claras, con barniz, aceite o teñido.'],
            ['Aislación bajo teja o chapa', 'Entre la cubierta y el machimbre va un aislante térmico y una barrera contra el agua. Sin esa capa, el techo de madera no protege del calor de la tarde.'],
            ['Cubierta', 'Teja colonial o francesa para el aspecto clásico, chapa para una solución liviana. La pendiente y la fijación dependen del material elegido.'],
            ['Tratamiento y terminación', 'Protección contra insectos y hongos, y una terminación al agua o al aceite que se renueva con los años. La madera cerca de la intemperie pide más cuidado.'],
        ],
        'sections' => [
            ['Techo de machimbre en el quincho, la galería y la casa', ['El machimbre no es solo para quinchos. Se usa en galerías, aleros, dormitorios y livings con techo a dos aguas, donde la madera a la vista da calidez y suma aislación. La técnica es la misma: estructura resistente, cielorraso bien fijado y una cubierta que proteja de la lluvia.', 'En una casa nueva se planifica con el resto de la obra. En una casa existente se puede reemplazar un cielorraso deteriorado o sumar madera vista en un ambiente sin tocar toda la estructura.']],
            ['Cómo se cuida un techo de madera en Paraguay', ['Con lluvias fuertes, calor y humedad, la madera pide una revisión periódica: mirar los aleros, los encuentros con la pared y las juntas del machimbre, y renovar el barniz o el aceite cuando se ve opaco. Un techo cuidado dura mucho más.', 'Los insectos xilófagos son un tema real: por eso el tratamiento no se saltea y se usan maderas que llegan preparadas. Si aparece aserrín fino o pequeños orificios, conviene revisar rápido.']],
        ],
        'mistakes' => [
            ['Madera sin estacionar', 'Se tuerce y se abre en el primer verano. Se pide madera seca y se deja aclimatar antes de colocar.'],
            ['Cubierta sin aislación', 'El machimbre se ve bien pero el calor pasa igual. Siempre se coloca un aislante entre la cubierta y la madera.'],
            ['Aleros demasiado cortos', 'La lluvia oblicua moja la estructura. Se prevé un alero generoso o un cerramiento que la proteja.'],
            ['Saltear el tratamiento', 'La madera sin protección sufre insectos y hongos. El tratamiento va antes del machimbre, no después.'],
            ['Estructura subdimensionada', 'La teja pesa más de lo que parece. Las secciones se calculan para la carga real, no por costumbre.'],
        ],
        'ideal' => ['Querés un quincho de estilo tradicional con madera a la vista.', 'Buscás un techo fresco para el verano.', 'Preferís coordinar carpintería y obra con un solo responsable.'],
        'faqs' => [
            ['¿Qué madera conviene para el techo?', 'Maderas duras bien estacionadas. Te asesoramos sobre las especies disponibles y cómo se comportan con el calor y la humedad.'],
            ['¿El machimbre necesita mantenimiento?', 'Un barnizado o aceitado periódico. Lo explicamos al entregar.'],
            ['¿Se puede combinar madera con chapa?', 'Sí. Estructura y cielorraso de madera con cubierta de chapa aislada es una combinación habitual y económica.'],
            ['¿Se puede poner machimbre en una galería o en un dormitorio?', 'Sí. Se coloca sobre listones bien nivelados, con aislación arriba, y funciona en cualquier ambiente con techo que lo soporte.'],
            ['¿Cómo se protege la madera de los insectos?', 'Con un tratamiento antes de instalarla, madera seca y una revisión periódica. El detalle se explica al entregar.'],
            ['¿Se puede reemplazar el techo de un quincho existente?', 'Sí. Se revisa la estructura y las columnas, y se propone reemplazar todo o solo el cielorraso y la cubierta.'],
        ],
        'related' => ['/quinchos/', '/patios/pergolas/', '/quintas/casa-campo/', '/guias/terreno/'],
    ],
];
