<?php
declare(strict_types=1);

// Especialidades de este hub: /{hub}/{slug}/. Una intencion de busqueda distinta a la del hub.
// 'related' son rutas completas. Sin precios, sin plazos fijos, sin datos inventados.
return [
    'cocinas' => [
        'name' => 'Remodelación de cocinas',
        'title' => 'Remodelación de cocinas en Paraguay | Obra',
        'description' => 'Remodelación de cocinas en Asunción y Gran Asunción: obra civil con demolición, instalaciones de agua, gas y electricidad, y revestimientos.',
        'summary' => 'Remodelación de cocinas en Asunción y Gran Asunción: distribución, instalaciones de agua, gas y electricidad, revestimientos, mesadas y muebles coordinados en una sola obra.',
        'h1' => 'Remodelación de cocinas',
        'kicker' => 'Distribución, instalaciones y terminación en una sola obra',
        'intro' => [
            'Remodelar la cocina es la reforma con más gremios por metro cuadrado: albañil, plomero, electricista, gasista, mueblero, marmolero. Cuando cada uno viene por su lado, el resultado se nota en los encuentros y en los tiempos.',
            'Nosotros coordinamos todo el proceso, desde la demolición hasta la instalación de la mesada y los artefactos, con una secuencia definida antes de empezar.',
        ],
        'includes' => ['Nueva distribución y demoliciones', 'Instalación de agua, desagüe, gas y electricidad', 'Revestimientos, pisos y cielorraso', 'Coordinación de muebles, mesadas y griferías', 'Iluminación y tomas donde se usan'],
        'process' => [
            ['Visita y relevamiento', 'Vamos a la casa y miramos la cocina como está: dónde entran el agua y el gas, por dónde sale el desagüe, qué paredes se pueden tocar y cómo circula la familia. También anotamos qué artefactos vas a usar, porque de eso depende dónde van las tomas y la campana.'],
            ['Alcance y presupuesto por rubro', 'Con lo relevado armamos el alcance: demolición y retiro, albañilería, instalaciones, revestimientos, pisos y cielorraso, cada uno por separado. Así ves qué pesa en cada parte y qué podés decidir después sin frenar la obra.'],
            ['Demolición y retiro', 'Se protege el resto de la casa, se retiran revestimientos, mesada y muebles viejos y se separan los escombros. Lo primero que se hace es cortar y ordenar agua, gas y electricidad para trabajar seguros.'],
            ['Instalaciones y revestimientos', 'Con las paredes abiertas se pasan las cañerías y los cables nuevos, se prueban y recién ahí se cierran. Después vienen contrapiso, revoque, revestimiento de pared y piso, y el cielorraso.'],
            ['Apoyos, mesada y entrega', 'Se dejan listos los apoyos para muebles y mesada, las tomas, las salidas de agua y de gas, y la iluminación. Con la cocina limpia y las instalaciones probadas, entran el mueblero y el marmolero y se conectan los artefactos.'],
        ],
        'materials' => [
            ['Revestimientos de pared', 'Cerámica, porcelanato o revestimientos de pared para la zona de mesada y cocción. Conviene un material fácil de limpiar y resistente al vapor y a la grasa; lo vemos con muestras.'],
            ['Pisos', 'Porcelanato, cerámica o cemento alisado. En cocina se prefiere una superficie que no resbale con agua o aceite y que soporte que se arrastren sillas y bancos.'],
            ['Cañerías y gas', 'Cañerías de agua y desagüe en material adecuado, y una instalación de gas con sus llaves de paso y ventilación. Se ejecuta con criterio de seguridad y se prueba antes de cerrar la pared.'],
            ['Apoyo de mesada', 'La mesada de piedra pesa y necesita un apoyo firme. Si va sobre muebles se coordina la altura con el fabricante; si va sobre muros bajos de mampostería, los levantamos nosotros.'],
        ],
        'sections' => [
            ['Cocina cerrada o integrada al comedor', ['Integrar la cocina con el comedor es una de las consultas más frecuentes. Se puede abrir una pared si no es portante, y para saberlo hay que revisar qué carga lleva. Cuando hace falta una viga o un refuerzo, se resuelve antes de demoler.', 'Al abrir el ambiente también cambian la ventilación y los olores: una campana bien ubicada y una salida de aire correcta pesan tanto como el mueble.']],
            ['Gas, agua y electricidad en una cocina nueva', ['La cocina concentra la mayor cantidad de instalaciones de la casa. Conviene definir antes de empezar dónde van la cocina, la heladera, el lavavajillas y el horno eléctrico, para dejar tomas independientes y la capacidad de los cables acorde al uso.', 'Si movés el lugar de la pileta o de la cocina, los desagües y el gas tienen que llegar con la pendiente y las ventilaciones correspondientes. Ese recorrido se dibuja en la visita, no en el medio de la obra.']],
        ],
        'mistakes' => [
            ['Comprar los artefactos después', 'Si no se conocen las medidas de la cocina, el horno y la heladera, los nichos quedan mal. Pedí las medidas reales antes de cerrar la albañilería.'],
            ['Ocultar cañerías sin probarlas', 'Cerrar la pared y descubrir una pérdida obliga a romper de nuevo. Se prueba la instalación antes de revestir.'],
            ['Pocas tomas y mal ubicadas', 'La cocina moderna usa varios artefactos a la vez. Se prevén tomas suficientes sobre la mesada y una línea propia para los equipos más exigentes.'],
            ['Coordinar mal los tiempos del mueblero y del marmolero', 'Cuando el mueble llega antes de que las paredes estén terminadas, hay golpes y retrabajos. Ordenamos la secuencia para que cada oficio entre a su tiempo.'],
        ],
        'ideal' => ['Tu cocina tiene una distribución que ya no funciona.', 'Querés integrar cocina y comedor.', 'Vas a renovar muebles y necesitás mover instalaciones.'],
        'faqs' => [
            ['¿Cuánto tiempo queda sin cocina?', 'Depende del alcance y de los tiempos de fabricación de muebles y mesadas. Lo secuenciamos para reducir los días sin uso.'],
            ['¿Incluyen los muebles?', 'Podemos coordinarlos con nuestra carpintería o con el proveedor que elijas. Lo que sí hacemos siempre es dejar la obra lista para su instalación.'],
            ['¿Puedo mover la cocina a otro ambiente?', 'Sí, si los desagües y la ventilación lo permiten. Lo verificamos en el relevamiento.'],
            ['¿Se puede vivir en la casa durante la remodelación?', 'Sí, con orden. Se aísla el sector con protección y se acuerda un rincón provisorio para cocinar, con una conexión eléctrica aparte si hace falta.'],
            ['¿Qué se hace primero, la obra civil o los muebles?', 'Primero la obra civil: instalaciones, revestimientos y piso. Los muebles se toman a medida sobre paredes ya terminadas, porque cualquier desvío de escuadra se nota en la puerta del mueble.'],
        ],
        'related' => ['/reformas/banos/', '/reformas/', '/ampliaciones/', '/guias/permisos/'],
        'link' => ['site' => 'carpinteria', 'path' => '/cocinas/', 'text' => 'Los muebles de cocina a medida los fabrica carpinteria.com.py; nosotros hacemos la demolición, las instalaciones y los revestimientos para que lleguen a una cocina lista.'],
    ],
    'banos' => [
        'name' => 'Remodelación de baños',
        'title' => 'Remodelación de baños en Paraguay | Obra',
        'description' => 'Remodelación de baños en Asunción y Gran Asunción: impermeabilización, instalaciones, revestimientos, ducha a nivel y sanitarios nuevos con un solo responsable.',
        'h1' => 'Remodelación de baños',
        'kicker' => 'Sin humedades y con la ducha bien resuelta',
        'intro' => [
            'Un baño mal remodelado se descubre a los meses: humedad en la pared del vecino, ducha que no drena, azulejos que se sueltan. La diferencia está en lo que no se ve: impermeabilización, pendientes y cañerías.',
            'Remodelamos baños completos o parciales, con ducha a nivel del piso, revestimientos grandes y sanitarios nuevos, cuidando la parte técnica antes que la estética.',
        ],
        'includes' => ['Demolición y retiro de revestimientos', 'Cañerías de agua y desagüe nuevas', 'Impermeabilización y pendientes de ducha', 'Revestimientos, piso y cielorraso', 'Sanitarios, grifería, mampara y accesorios'],
        'process' => [
            ['Visita y relevamiento', 'Miramos el baño y lo que hay detrás: humedades en paredes vecinas, olores, desagües lentos, ventilación y el estado del piso. Si hay pérdidas, buscamos el origen antes de proponer nada, porque cubrir sin corregir la causa repite el problema.'],
            ['Alcance y presupuesto por rubro', 'Se separan demolición, cañerías, impermeabilización, revestimientos, sanitarios y grifería, mampara y accesorios. Vos elegís sanitarios y revestimientos y nosotros ordenamos la obra alrededor de esas elecciones.'],
            ['Demolición y cañerías', 'Se retiran revestimientos y piso, se corrigen o reemplazan las cañerías y se define el nivel del desagüe. Es la etapa más sucia y se organiza para molestar lo menos posible al resto de la casa.'],
            ['Impermeabilización y pendientes', 'Antes de revestir se aplica la impermeabilización en piso y en la parte baja de las paredes, y se arma la pendiente hacia el desagüe. Se prueba con agua antes de continuar.'],
            ['Revestimiento, sanitarios y entrega', 'Se colocan revestimientos y piso, luego sanitarios, grifería, mampara y accesorios. Se revisan el desagüe, la ventilación y las juntas antes de entregarlo.'],
        ],
        'materials' => [
            ['Impermeabilización', 'Membranas o pinturas impermeabilizantes según el caso. En la ducha y en las paredes que la rodean se trata con más cuidado que en el resto, y la elección depende de si el piso es nuevo o existente.'],
            ['Revestimientos y juntas', 'Porcelanato o cerámica, de formato grande para tener menos juntas o chico si buscás más agarre en la ducha. Se cuida la calidad de la pastina, porque es la que sufre con la humedad.'],
            ['Desagües y rejillas', 'Desagüe puntual o lineal (canaleta), con la pendiente adecuada. Los lineales dan un aspecto más limpio y se combinan bien con la ducha a nivel.'],
            ['Ventilación', 'Ventana, extractor o ambas. Un baño sin ventilación acumula humedad, y por eso se decide junto con la distribución.'],
        ],
        'sections' => [
            ['Ducha a nivel del piso y baño adaptado', ['La ducha a nivel obliga a rehacer el piso: se baja el nivel del desagüe, se arma la pendiente y se impermeabiliza en continuidad con el resto del baño. No es solo un cambio de bañera por receptáculo, es una obra de piso.', 'Para un baño adaptado a una persona mayor se agrega el ancho de paso, el espacio para girar, los barrales en los lugares donde se usan y una grifería fácil de operar. Lo definimos con quien lo va a usar.']],
            ['Hacer el baño con la casa en uso', ['Cuando la casa tiene un solo baño, la obra se planifica en etapas para dejarlo funcional cuanto antes: primero lo que no se puede usar, después las terminaciones. Si hay otro baño, se trabaja con más calma.', 'Se protegen los pisos del recorrido, se cierra la puerta con lona y se retiran los escombros por partes, para que el polvo y el ruido molesten lo menos posible.']],
        ],
        'mistakes' => [
            ['Revestir sin impermeabilizar', 'La humedad aparece meses después, con la pared del vecino o del cuarto de al lado manchada. La impermeabilización va siempre antes del revestimiento.'],
            ['Pendiente insuficiente', 'Si el agua no escurre hacia el desagüe, el piso queda mojado y se ensucia más. La pendiente se traza y se controla antes de colocar el piso.'],
            ['Cambiar los sanitarios sin revisar las cañerías', 'Un sanitario nuevo sobre una cañería vieja repite las pérdidas. Se revisa y se cambia lo que haga falta.'],
            ['Olvidar la ventilación', 'Un baño cerrado acumula humedad y hongos. Se prevé ventana o extractor desde la distribución.'],
        ],
        'ideal' => ['El baño tiene humedad o pérdidas.', 'Querés una ducha a nivel del piso, más segura y moderna.', 'Vas a hacer un baño adaptado para una persona mayor.'],
        'faqs' => [
            ['¿Se puede cambiar la bañera por ducha a nivel?', 'Sí. Es una de las reformas más pedidas. Requiere rehacer el desagüe y la pendiente del piso.'],
            ['¿Cuántos días queda sin baño?', 'Depende del alcance. Si hay otro baño en la casa, la obra se organiza sin apuro; si es el único, priorizamos dejarlo usable cuanto antes.'],
            ['¿Hacen baños adaptados?', 'Sí: sin escalones, barrales, espacio de giro y grifería accesible.'],
            ['¿Sirve reformar solo el revestimiento?', 'A veces sí, si el piso y las cañerías están sanos. Si hay humedad o pérdidas, conviene abrir y corregir la causa; de lo contrario el revestimiento nuevo se estropea otra vez.'],
            ['¿Qué pasa con el baño del vecino o el departamento de abajo?', 'Si hay filtraciones, se revisa la impermeabilización y el desagüe en la visita. Con una buena impermeabilización, el agua no debería pasar a otros ambientes.'],
        ],
        'related' => ['/reformas/cocinas/', '/ampliaciones/dormitorio/', '/reformas/', '/guias/costo-casa/'],
    ],
    'fachadas' => [
        'name' => 'Renovación de fachadas',
        'title' => 'Renovación de fachadas de casas en Paraguay | Obra',
        'description' => 'Renovación de fachadas en Asunción y Gran Asunción: revoque, revestimientos, aberturas y muro frontal para cambiar la cara de la casa sin tocar adentro.',
        'summary' => 'Renovación de fachadas en Asunción y Gran Asunción: revoque, revestimientos, aberturas, techo de acceso y muro frontal para cambiar la cara de la casa sin tocar el interior.',
        'h1' => 'Renovación de fachadas',
        'kicker' => 'Otra casa desde la calle',
        'intro' => [
            'La fachada es lo primero que se ve y lo último que se renueva. Cambiar revoque, aberturas, el techo del acceso y el muro frontal transforma la casa sin tocar el interior, y suma valor si pensás vender o alquilar.',
            'Trabajamos la fachada como una obra completa: humedades, revoques, revestimientos, aberturas, iluminación y muro de frente, con andamios y protección de la vereda.',
        ],
        'includes' => ['Reparación de humedades y revoques', 'Revestimientos: piedra, ladrillo visto o texturas', 'Cambio de aberturas de frente', 'Techo o pérgola de acceso y cochera', 'Muro frontal, portón e iluminación'],
        'process' => [
            ['Visita y relevamiento', 'Recorremos la fachada de cerca: fisuras, humedad ascendente, revoques sueltos, aberturas desajustadas y el estado del techo de acceso. También vemos cómo se puede armar el andamio y qué hay que proteger en la vereda y en el jardín.'],
            ['Alcance y presupuesto por rubro', 'Separamos preparación de superficies, revoque, revestimientos, aberturas, pintura, muro frontal e iluminación. Podés arrancar con lo que más urge y dejar el resto para una segunda etapa.'],
            ['Andamios y preparación', 'Se arma el andamio, se protegen aberturas y pisos, y se retiran los revoques flojos. Se abren las fisuras para tratarlas y se corrige la humedad antes de tapar nada.'],
            ['Revoque, revestimiento y aberturas', 'Se repara el revoque, se coloca el revestimiento elegido y se ajustan o reemplazan las aberturas del frente. El orden importa: primero lo que ensucia, después lo que se ve.'],
            ['Pintura, iluminación y entrega', 'Se pinta, se instalan luminarias y se retira el andamio. Se limpia la vereda y se revisa el resultado con luz de día para detectar retoques.'],
        ],
        'materials' => [
            ['Revoques y morteros', 'Revoque nuevo o reparación parcial, según el estado. Un buen revoque de base es lo que después permite pintar o revestir sin que aparezcan fisuras.'],
            ['Revestimientos', 'Piedra, ladrillo visto, cerámicos exteriores o texturas. Cada uno tiene su mantenimiento: la piedra pide sellado, el ladrillo visto necesita buena impermeabilización y las texturas se retocan con más facilidad.'],
            ['Pinturas exteriores', 'Látex para exterior o pinturas texturadas. La elección depende del sol que recibe la fachada y de cuánta humedad hay en la pared.'],
            ['Techo de acceso y muro frontal', 'Se hacen en hormigón, mampostería, chapa o madera, según el conjunto. La pérgola o la cochera cubierta de frente son parte de nuestra obra.'],
        ],
        'sections' => [
            ['Humedad y fisuras: qué se trata antes de embellecer', ['Pintar sobre una pared húmeda o con fisuras vivas deja la fachada linda por poco tiempo. Por eso empezamos por entender por qué se ensucia o se pela: capilaridad desde el suelo, techo sin canaleta, grietas por movimiento o revoque de mala calidad.', 'Cuando corresponde se corrige el origen (una canaleta, una junta, una membrana) y recién ahí se vuelve a revocar. La terminación se ve, pero el resultado se sostiene en lo que quedó abajo.']],
            ['Trabajar con andamios y la casa habitada', ['La fachada se hace desde afuera y la casa sigue funcionando, pero hay que cuidar las entradas, el auto y el jardín. Coordinamos con vos por qué lado se entra y por dónde se dejan los materiales, y cerramos o protegemos la vereda si hace falta.', 'El clima cuenta: con lluvia no se revoca ni se pinta, así que la obra se ordena por tramos y se cubre lo que quedó abierto.']],
        ],
        'mistakes' => [
            ['Pintar sin corregir la humedad', 'El color se levanta y aparecen manchas a los pocos meses. Se trata el origen antes de la terminación.'],
            ['Revestir sin impermeabilizar las juntas', 'El agua se mete detrás del revestimiento y lo suelta. Se sella y se prevén goteros y remates.'],
            ['Cambiar aberturas sin ajustar el marco', 'Una abertura nueva sobre un vano desnivelado filtra aire y agua. Se revisa el vano antes de colocar.'],
            ['Decidir la iluminación al final', 'Los cables de luz exterior van por dentro de la pared. Si no se prevén antes de revocar, hay que romper después.'],
        ],
        'ideal' => ['La casa está bien adentro pero se ve vieja desde afuera.', 'Vas a vender o alquilar y querés que impacte.', 'Querés sumar cochera cubierta y portón nuevo.'],
        'faqs' => [
            ['¿Puedo cambiar la fachada sin permiso?', 'Cambios de terminación no suelen requerirlo; cambios estructurales o de superficie cubierta sí. Lo revisamos.'],
            ['¿Cuánto dura una obra de fachada?', 'Depende del alcance y del clima, porque gran parte se hace a la intemperie. Se define en la propuesta.'],
            ['¿Incluyen la pintura?', 'Sí, cuando forma parte del alcance. Recomendamos definirla junto con el revestimiento.'],
            ['¿Se puede renovar solo una parte de la fachada?', 'Sí, por ejemplo el frente sobre la calle o la entrada. Se cuida que la parte nueva quede en continuidad con el resto, para que no parezca un parche.'],
            ['¿Qué pasa con el jardín y las plantas del frente?', 'Se protegen durante la obra y se acuerda por dónde se acopian los materiales. Si hay algo que estorba al andamio, se mueve con cuidado y se vuelve a ubicar al final.'],
        ],
        'related' => ['/muros/portones/', '/tinglados/cocheras/', '/reformas/', '/guias/plazos/'],
        'link' => ['site' => 'arq', 'path' => '/estilos/', 'text' => 'Si todavía no está definido el diseño de la nueva fachada, el proyecto lo prepara nuestro estudio en arq.com.py y nosotros lo ejecutamos en obra.'],
    ],
    'techos' => [
        'name' => 'Cambio y reparación de techos',
        'title' => 'Cambio y reparación de techos en Paraguay | Obra',
        'description' => 'Reparación y cambio de techos de tejas, chapa y losa en Asunción y Gran Asunción: filtraciones, estructura, aislación térmica y canaletas resueltas de raíz.',
        'h1' => 'Cambio y reparación de techos',
        'kicker' => 'Filtraciones resueltas de raíz',
        'intro' => [
            'Una filtración se parcha una vez. La segunda vez conviene entender la causa: tejas rotas, pendiente insuficiente, estructura vencida, canaletas tapadas o una losa sin membrana. Cada caso tiene una solución distinta.',
            'Reparamos y cambiamos techos completos: estructura, cubierta, aislación térmica, cielorraso y canaletas, con protección de la casa mientras dura la obra.',
        ],
        'includes' => ['Diagnóstico de la causa de la filtración', 'Cambio de tejas, chapa o membrana de losa', 'Refuerzo o reemplazo de estructura', 'Aislación térmica y cielorraso', 'Canaletas, bajadas y desagües'],
        'process' => [
            ['Visita y diagnóstico', 'Subimos al techo, vemos la cubierta, la estructura y los puntos donde entra el agua, y del lado de adentro miramos manchas, cielorraso y encuentros con paredes. El objetivo es entender la causa, no solo dónde gotea.'],
            ['Opciones y presupuesto por rubro', 'Presentamos la reparación puntual y, cuando corresponde, el cambio completo, con estructura, cubierta, aislación, cielorraso y canaletas por separado. Así comparás alcance y no solo un total.'],
            ['Protección y retiro', 'Se cubre la casa por dentro, se retiran las tejas, chapas o la membrana dañadas y se desmonta lo que no sirve. Se trabaja por sectores para que la casa no quede abierta.'],
            ['Estructura y nueva cubierta', 'Se refuerza o reemplaza la estructura, se corrige la pendiente y se coloca la cubierta nueva con sus remates, cumbreras y encuentros con paredes, que es donde más se filtra.'],
            ['Canaletas, cielorraso y entrega', 'Se colocan canaletas y bajadas, se repara el cielorraso y se hace una prueba con agua. Se limpia y se retiran los restos.'],
        ],
        'materials' => [
            ['Tejas', 'Cerámicas o de hormigón. Son duraderas y se comportan bien con el calor, pero pesan y necesitan estructura preparada. Se puede reutilizar parte si están sanas.'],
            ['Chapas', 'Chapa trapezoidal o termoacústica. Es liviana y rápida de colocar; la versión aislada baja el calor dentro de la casa. Lo importante son las fijaciones y los solapes.'],
            ['Losa con membrana', 'Se impermeabiliza con membranas asfálticas u otros sistemas y se cuida la pendiente hacia las bajadas. Es la solución habitual para terrazas y techos planos.'],
            ['Techos de madera y machimbre', 'Estructura de madera con cielorraso de machimbre. Lo ejecutamos nosotros: se trata la madera, se ventila el entretecho y se cuida que el agua no la castigue.'],
        ],
        'sections' => [
            ['Impermeabilización y humedad en el techo', ['Impermeabilizar no es pintar el techo. Depende de qué techo es: en una losa se trabaja con membrana, con pendiente y con babetas en los encuentros con paredes; en un techo de chapa o teja, con solapes correctos, fijaciones selladas y canaletas limpias.', 'La humedad que aparece adentro no siempre viene de un agujero. Puede ser condensación en un techo sin aislación, una bajada tapada o una pared que absorbe agua desde arriba. Diagnosticar primero evita gastar dos veces.']],
            ['Calor, aislación y canaletas', ['En verano un techo sin aislación transmite el calor al interior. Placas aislantes, chapa termoacústica o cámaras de aire bajan la temperatura y ayudan también con el ruido de la lluvia.', 'Las canaletas y las bajadas cierran el trabajo: si el agua se junta o sale mal, vuelve a entrar por las paredes. Se dimensionan según la superficie y se dejan limpiables.']],
        ],
        'mistakes' => [
            ['Parchar sin buscar la causa', 'La gotera reaparece al lado. Se sigue el recorrido del agua hasta el origen.'],
            ['Cambiar la cubierta sin revisar la estructura', 'Una chapa nueva sobre madera podrida dura poco. Se evalúa la estructura antes de cubrir.'],
            ['Olvidar los encuentros y remates', 'Cumbreras, babetas y encuentros con paredes concentran las filtraciones. Se ejecutan con más cuidado que el resto.'],
            ['Ignorar la pendiente', 'Con poca pendiente el agua se acumula. Se verifica y se corrige antes de colocar la cubierta.'],
        ],
        'ideal' => ['El techo filtra y ya lo parchaste varias veces.', 'La casa es muy calurosa y el techo no tiene aislación.', 'Querés cambiar teja por chapa aislada o al revés.'],
        'faqs' => [
            ['¿Conviene reparar o cambiar todo el techo?', 'Depende del estado de la estructura y de cuánta cubierta está dañada. Lo evaluamos y te damos las dos opciones cuando existen.'],
            ['¿Se puede hacer con la casa habitada?', 'Sí. Trabajamos por sectores y protegemos con lonas cada tramo abierto.'],
            ['¿Qué aislación recomiendan?', 'Depende del tipo de cubierta y del presupuesto. Lo importante es que exista y esté bien colocada.'],
            ['¿Cómo sé si la humedad viene del techo o de otro lado?', 'Se sigue el recorrido: manchas que aparecen tras la lluvia y cerca de encuentros con paredes suelen venir del techo; las que suben desde el piso son otra causa. Lo verificamos en la visita.'],
            ['¿Se puede impermeabilizar una losa sin cambiar todo?', 'Muchas veces sí, si la losa está sana. Se limpia, se corrige la pendiente y se coloca una membrana nueva; si hay daños en el hormigón se reparan antes.'],
        ],
        'related' => ['/reformas/', '/tinglados/', '/quintas/refaccion/', '/guias/costo-casa/'],
    ],
];
