<?php
declare(strict_types=1);

// Subpaginas de cada servicio: /{servicio}/{slug}/. Cada una ataca una intencion de busqueda
// distinta a la del hub (tipo de obra, situacion o variante), sin repetir el texto del padre.
// 'related' son rutas completas. Sin precios, sin plazos fijos, sin datos inventados.
return [
    'casas' => [
        'duplex' => [
            'name' => 'Dúplex y casas de dos plantas',
            'title' => 'Construcción de dúplex en Paraguay | Obra',
            'description' => 'Construcción de dúplex y casas de dos plantas en Asunción y Gran Asunción: estructura, losa, escalera e instalaciones resueltas para aprovechar terrenos chicos.',
            'h1' => 'Construcción de dúplex y casas de dos plantas',
            'kicker' => 'Más metros en el mismo terreno',
            'intro' => [
                'Un dúplex resuelve un problema muy común en Asunción y Central: terrenos angostos o compartidos donde una casa de una planta no alcanza. Construimos dúplex para vivienda propia, para dos familias y como unidades para alquilar.',
                'La diferencia con una casa de una planta está en la estructura: losa, columnas, escalera y las instalaciones que suben. Eso se define en el proyecto, no en la obra, para que el presupuesto sea real desde el principio.',
            ],
            'includes' => ['Estructura de hormigón armado y losa', 'Escalera interior o exterior según el uso', 'Instalaciones independientes por unidad cuando son dos viviendas', 'Aislación acústica entre unidades', 'Cochera, acceso y medidores separados'],
            'ideal' => ['Tu terreno es angosto o querés dejar patio libre.', 'Querés dos unidades: una para vivir y otra para alquilar.', 'Construís sobre un terreno familiar compartido.'],
            'faqs' => [
                ['¿Un dúplex es más caro por metro cuadrado que una casa de una planta?', 'La estructura y la escalera suman costo, pero se ahorra en techo, fundaciones y terreno por metro construido. La comparación real sale del cómputo por rubro de cada proyecto.'],
                ['¿Puedo hacer dos unidades con medidores separados?', 'Sí. Se proyectan instalaciones independientes y se coordina la habilitación de medidores con las prestadoras.'],
                ['¿Se puede construir el dúplex por etapas?', 'Sí, siempre que la estructura de la segunda planta quede prevista desde la primera etapa.'],
            ],
            'related' => ['/casas/minimalistas/', '/casas/etapas/', '/ampliaciones/planta-alta/'],
        ],
        'minimalistas' => [
            'name' => 'Casas modernas y minimalistas',
            'title' => 'Construcción de casas modernas y minimalistas en Paraguay | Obra',
            'description' => 'Construcción de casas modernas y minimalistas en Asunción y Gran Asunción: losa plana, ladrillo visto, grandes aberturas y galería integrada, ejecutadas con terminaciones limpias.',
            'h1' => 'Construcción de casas modernas y minimalistas',
            'kicker' => 'Líneas simples, bien ejecutadas',
            'intro' => [
                'El estilo moderno paraguayo tiene códigos claros: losa plana o techo oculto, ladrillo visto, hormigón a la vista, aberturas grandes hacia el patio y galería como extensión de la casa. Es un estilo que perdona poco: cada junta, cada encuentro y cada nivel se ve.',
                'Por eso lo tratamos como una obra de precisión. Definimos con vos y con el proyectista qué terminaciones quedan a la vista, qué materiales las logran y cómo se protegen del calor y la lluvia.',
            ],
            'includes' => ['Losa plana con aislación y pendientes de desagüe ocultas', 'Ladrillo visto o revoque fino según el proyecto', 'Aberturas de gran luz con dinteles y vigas calculadas', 'Galería integrada con piso continuo', 'Detalles de terminación: bordes, zócalos y encuentros'],
            'ideal' => ['Querés una casa de líneas limpias sin sobresaltos en la terminación.', 'Ya tenés un proyecto moderno y necesitás quien lo ejecute con precisión.', 'Buscás una casa con galería y patio integrados.'],
            'faqs' => [
                ['¿La losa plana da problemas de filtración?', 'Da problemas cuando está mal ejecutada. Con pendientes correctas, desagües bien ubicados, membrana y aislación térmica funciona bien en el clima paraguayo.'],
                ['¿El ladrillo visto necesita mantenimiento?', 'Necesita un sellado periódico y una buena ejecución de juntas desde el inicio. Lo incluimos en el alcance y te explicamos el mantenimiento al entregar.'],
                ['¿Hacen el proyecto también?', 'El diseño lo hace nuestro estudio en arq.com.py o el arquitecto que elijas. Nosotros construimos.'],
            ],
            'related' => ['/casas/duplex/', '/patios/decks/', '/piscinas/desbordante/'],
        ],
        'etapas' => [
            'name' => 'Construcción por etapas',
            'title' => 'Construcción de casas por etapas en Paraguay | Obra',
            'description' => 'Construí tu casa por etapas en Asunción y Gran Asunción: obra gruesa primero, terminaciones después, con un plan que evita rehacer y mantiene el presupuesto controlado.',
            'h1' => 'Construcción de casas por etapas',
            'kicker' => 'Empezá con lo que tenés, sin cerrar puertas',
            'intro' => [
                'Muchas familias construyen a medida que pueden: primero la platea y la mampostería, después el techo, más adelante las terminaciones. Bien planificado funciona. Mal planificado se paga dos veces: se rompe lo hecho para pasar caños o se levantan paredes que después estorban.',
                'Nuestro trabajo es ordenar la secuencia técnica para que cada etapa deje la siguiente preparada, y que cada etapa tenga su propio presupuesto cerrado.',
            ],
            'includes' => ['Plan de etapas con lo que debe quedar previsto en cada una', 'Etapa 1: fundaciones, mampostería y estructura', 'Etapa 2: techo, instalaciones embutidas y aberturas', 'Etapa 3: revestimientos, pisos, pintura y artefactos', 'Presupuesto independiente por etapa'],
            'ideal' => ['Tenés terreno y fondos para arrancar, pero no para toda la casa.', 'Vas a combinar ahorro propio con un crédito más adelante.', 'Querés habitar una parte de la casa mientras se termina el resto.'],
            'faqs' => [
                ['¿Cuál es el orden correcto de las etapas?', 'Fundaciones y estructura, después techo y cerramiento, después instalaciones y terminaciones. Lo que nunca conviene es dejar la obra gruesa expuesta a la lluvia sin techo por mucho tiempo.'],
                ['¿Puedo cambiar de constructor entre etapas?', 'Podés. Por eso cada etapa se entrega con un detalle de lo ejecutado y de lo que quedó previsto para la siguiente.'],
                ['¿Se puede vivir en la casa entre etapas?', 'Sí, cuando una parte está habitable y la obra restante se aísla de forma segura.'],
            ],
            'related' => ['/credito/', '/guias/costo-casa/', '/ampliaciones/'],
        ],
        'prefabricadas' => [
            'name' => 'Casas prefabricadas vs construcción tradicional',
            'title' => 'Casas prefabricadas vs construcción tradicional | Obra',
            'description' => 'Casas prefabricadas y premoldeadas frente a la construcción tradicional en Paraguay: durabilidad, clima, financiación, reventa y en qué casos conviene cada una.',
            'h1' => 'Casas prefabricadas o construcción tradicional: qué conviene',
            'kicker' => 'Una comparación honesta antes de decidir',
            'intro' => [
                'Las casas prefabricadas y premoldeadas se venden como la opción rápida y económica. En algunos casos lo son. Pero en Paraguay pesan tres cosas que conviene mirar antes: el calor, la humedad y la financiación bancaria.',
                'Obra construye con sistema tradicional (mampostería de ladrillo y estructura de hormigón). Acá te contamos sin vueltas cuándo una prefabricada puede ser mejor para vos y cuándo no.',
            ],
            'includes' => ['Comportamiento térmico en el verano paraguayo', 'Durabilidad, mantenimiento y humedad', 'Qué acepta un banco o la AFD como garantía', 'Valor de reventa y ampliaciones futuras', 'Costo total: casa, platea, instalaciones y terreno preparado'],
            'ideal' => ['Estás comparando presupuestos de prefabricadas con los de obra tradicional.', 'Necesitás construir rápido y querés saber el costo real de esa velocidad.', 'Vas a financiar con crédito y no sabés qué acepta el banco.'],
            'faqs' => [
                ['¿Una casa prefabricada es más barata?', 'El precio de catálogo suele no incluir platea, instalaciones, conexiones ni terminaciones. Comparado el mismo alcance, la diferencia se achica y a veces se invierte.'],
                ['¿Los bancos financian casas prefabricadas?', 'Depende del sistema y de la entidad. Muchas líneas hipotecarias exigen construcción tradicional o sistemas certificados. Consultá antes de firmar.'],
                ['¿Se puede ampliar una prefabricada?', 'Es más difícil integrar una ampliación tradicional a un sistema modular. Con mampostería, ampliar es parte del oficio.'],
            ],
            'related' => ['/casas/etapas/', '/guias/costo-casa/', '/guias/ladrillo-bloque/'],
        ],
    ],
    'quintas' => [
        'refaccion' => [
            'name' => 'Refacción de quintas',
            'title' => 'Refacción y puesta a punto de quintas en Paraguay | Obra',
            'description' => 'Refacción de quintas en Paraguay: techos, instalaciones, piscina, quincho y cerramiento renovados con un solo responsable y un plan por sectores.',
            'h1' => 'Refacción y puesta a punto de quintas',
            'kicker' => 'Recuperar lo que ya está construido',
            'intro' => [
                'Comprar una quinta usada casi siempre significa heredar problemas: techos con filtraciones, instalaciones viejas, piscina con pérdidas, muros caídos. Refaccionar bien es más barato que demoler, pero solo si se relevan los problemas antes de presupuestar.',
                'Hacemos un relevamiento por sectores (casa, exteriores, agua, electricidad, perímetro) y armamos un plan de intervención con prioridades: primero lo que protege la construcción, después lo que la mejora.',
            ],
            'includes' => ['Relevamiento del estado por sector con fotos', 'Techos, cielorrasos y humedades', 'Renovación de instalaciones eléctricas y sanitarias', 'Recuperación de piscina, quincho y galerías', 'Muros, portones y accesos'],
            'ideal' => ['Compraste una quinta y no sabés por dónde empezar.', 'La quinta familiar quedó abandonada varios años.', 'Querés alquilarla y necesita estar en condiciones.'],
            'faqs' => [
                ['¿Conviene refaccionar o demoler?', 'Depende del estado de la estructura y las fundaciones. Si están sanas, refaccionar suele ser más económico. Lo evaluamos en el relevamiento.'],
                ['¿Pueden trabajar por prioridades?', 'Sí. Ordenamos la obra para que lo urgente (techo, agua, electricidad) vaya primero y el resto se programe según presupuesto.'],
                ['¿Trabajan en quintas lejos de Asunción?', 'Evaluamos cada caso según distancia, tamaño de la obra y logística de materiales.'],
            ],
            'related' => ['/quintas/casa-campo/', '/piscinas/renovacion/', '/reformas/techos/'],
        ],
        'casa-campo' => [
            'name' => 'Casas de campo',
            'title' => 'Construcción de casas de campo en Paraguay | Obra',
            'description' => 'Construcción de casas de campo en Paraguay: galerías amplias, techos altos, materiales que aguantan el clima y servicios propios de agua y electricidad.',
            'h1' => 'Construcción de casas de campo',
            'kicker' => 'Pensada para el calor, la lluvia y el fin de semana',
            'intro' => [
                'Una casa de campo no es una casa de ciudad puesta en una quinta. Tiene otra lógica: galería grande porque la vida pasa afuera, techos altos y aleros para el calor, materiales que no necesitan cuidado semanal y servicios que funcionan sin red pública.',
                'Construimos casas de campo con esa lógica desde el proyecto, coordinando agua (pozo, bomba, tanque), electricidad, desagües y accesos como parte de la misma obra.',
            ],
            'includes' => ['Implantación según sombra, viento y accesos', 'Galería perimetral y techos con aleros', 'Pozo, tanque elevado y presión de agua', 'Pozo ciego o cámara séptica según el terreno', 'Materiales de bajo mantenimiento'],
            'ideal' => ['Tenés una quinta sin construir y querés una casa para usar todo el año.', 'Querés una casa de descanso con galería y quincho integrados.', 'El terreno no tiene agua ni cloaca y hay que resolverlo.'],
            'faqs' => [
                ['¿Qué materiales convienen para una casa de campo?', 'Los que aguantan sin mantenimiento constante: ladrillo visto o revoque, techos de teja o chapa con aislación, aberturas de aluminio o madera dura tratada.'],
                ['¿Pueden resolver el agua si no hay red?', 'Sí. Coordinamos la perforación del pozo, la bomba, el tanque y la instalación interna como parte de la obra.'],
                ['¿Se puede empezar por el quincho y después la casa?', 'Sí. Es una secuencia habitual en quintas: quincho con baño primero, casa principal después, con servicios previstos para ambos.'],
            ],
            'related' => ['/quintas/refaccion/', '/quinchos/', '/piscinas/quinta/'],
        ],
    ],
    'piscinas' => [
        'chicas' => [
            'name' => 'Piscinas pequeñas para patios chicos',
            'title' => 'Piscinas pequeñas para patios chicos en Paraguay | Obra',
            'description' => 'Construcción de piscinas pequeñas de hormigón para patios chicos en Asunción y Gran Asunción: medidas a la medida del espacio, acceso de obra resuelto y vereda integrada.',
            'h1' => 'Piscinas pequeñas para patios chicos',
            'kicker' => 'Una piscina real en pocos metros',
            'intro' => [
                'En Asunción, Fernando de la Mora, Luque o San Lorenzo los patios suelen ser chicos. Eso no impide tener una piscina de hormigón: cambia el diseño, no la calidad. Una piscina compacta bien ubicada aprovecha mejor el patio que una grande que no deja lugar para nada más.',
                'El desafío real en patios chicos es el acceso: por dónde entra la excavadora, dónde va la tierra, cómo se protege lo que ya existe. Lo resolvemos antes de cotizar.',
            ],
            'includes' => ['Diseño de medidas y forma según el patio real', 'Excavación manual o con máquina chica según el acceso', 'Estructura de hormigón armado y filtrado compacto', 'Vereda perimetral y unión con la galería', 'Iluminación y previsión de climatización'],
            'ideal' => ['Tu patio tiene pocos metros y querés aprovecharlos.', 'La casa ya está construida y el acceso es angosto.', 'Querés piscina sin renunciar a un sector de quincho o jardín.'],
            'faqs' => [
                ['¿Cuál es la medida mínima razonable?', 'Depende del uso. Para refrescarse y jugar con chicos alcanza con medidas muy compactas; para nadar hace falta más largo. Lo definimos con vos sobre el plano del patio.'],
                ['¿Cómo entra la máquina si el pasillo es angosto?', 'Con equipos chicos o excavación manual. Es más lento pero habitual. El método se decide en la visita.'],
                ['¿Se puede hacer una piscina elevada?', 'Sí, cuando el suelo o el acceso lo justifican. Cambia la estructura y la terminación exterior.'],
            ],
            'related' => ['/piscinas/quinta/', '/patios/decks/', '/quinchos/'],
        ],
        'quinta' => [
            'name' => 'Piscinas para quintas',
            'title' => 'Construcción de piscinas para quintas en Paraguay | Obra',
            'description' => 'Piscinas de hormigón para quintas y casas de campo en Paraguay: mayor tamaño, agua de pozo, filtrado dimensionado y área de quincho y solárium integrada.',
            'h1' => 'Piscinas para quintas y casas de campo',
            'kicker' => 'Tamaño, agua propia y todo alrededor',
            'intro' => [
                'En una quinta la piscina es el centro del fin de semana. Suele ser más grande, se llena con agua de pozo y convive con quincho, galería y jardín. Eso cambia el filtrado, la vereda y la forma de cuidarla entre visita y visita.',
                'Proyectamos la piscina junto con el quincho y el solárium, y dimensionamos la instalación para agua de pozo y para períodos sin uso.',
            ],
            'includes' => ['Piscina de hormigón de mayor tamaño y profundidad variable', 'Filtrado dimensionado para agua de pozo y uso intermitente', 'Solárium, vereda amplia y ducha exterior', 'Unión con quincho y galería', 'Casilla de máquinas y previsión de climatización'],
            'ideal' => ['Tenés una quinta y querés la piscina como centro del espacio exterior.', 'Vas a llenar con agua de pozo.', 'Querés hacer piscina y quincho como una sola obra.'],
            'faqs' => [
                ['¿El agua de pozo sirve para la piscina?', 'Sí, con un análisis previo y un tratamiento adecuado. A veces hace falta un filtro adicional por hierro o dureza.'],
                ['¿Cómo se mantiene si voy solo los fines de semana?', 'Con un filtrado bien dimensionado, un temporizador y una rutina simple. Te dejamos el instructivo al entregar.'],
                ['¿Pueden hacer una piscina con zona para chicos?', 'Sí. Se proyecta con un sector de baja profundidad o escalones amplios.'],
            ],
            'related' => ['/quintas/', '/quinchos/', '/piscinas/desbordante/'],
        ],
        'desbordante' => [
            'name' => 'Piscinas desbordantes',
            'title' => 'Piscinas desbordantes e infinity en Paraguay | Obra',
            'description' => 'Construcción de piscinas desbordantes (infinity) en Paraguay: borde perdido, canaleta, tanque de compensación y estructura calculada para el efecto sin filtraciones.',
            'h1' => 'Piscinas desbordantes e infinity',
            'kicker' => 'El borde perdido bien resuelto',
            'intro' => [
                'Una piscina desbordante se ve simple y es técnicamente la más exigente: el agua tiene que pasar el borde de forma pareja, caer a una canaleta y volver desde un tanque de compensación. Un desnivel de milímetros en el borde se nota.',
                'Ejecutamos piscinas desbordantes de uno o varios lados, con la nivelación del borde controlada y la instalación hidráulica dimensionada para el caudal real.',
            ],
            'includes' => ['Estructura con muro de desborde y canaleta', 'Tanque de compensación y bombas dimensionadas', 'Nivelación de precisión del borde', 'Revestimiento continuo y borde de terminación', 'Iluminación y automatización de nivel'],
            'ideal' => ['Tu terreno tiene desnivel o vista y querés aprovecharlos.', 'Buscás una piscina de diseño con terminación de alto nivel.', 'Ya tenés un proyecto de arquitectura con piscina desbordante.'],
            'faqs' => [
                ['¿Una desbordante gasta más agua?', 'Pierde algo más por evaporación y salpicadura, pero el tanque de compensación recupera el agua del desborde. Con una instalación bien hecha, el consumo es razonable.'],
                ['¿Se puede hacer en un patio plano?', 'Sí. El efecto de borde perdido funciona con un desnivel construido; no hace falta una barranca.'],
                ['¿Es mucho más cara que una piscina común?', 'Suma estructura, tanque y bombas. Cuánto más depende del tamaño y de cuántos lados desbordan. Se ve en el cómputo por rubro.'],
            ],
            'related' => ['/piscinas/quinta/', '/casas/minimalistas/', '/patios/decks/'],
        ],
        'renovacion' => [
            'name' => 'Renovación y reparación de piscinas',
            'title' => 'Renovación y reparación de piscinas en Paraguay | Obra',
            'description' => 'Renovación de piscinas en Asunción y Gran Asunción: pérdidas de agua, revestimiento, vereda, filtrado e iluminación renovados sin construir de nuevo.',
            'h1' => 'Renovación y reparación de piscinas',
            'kicker' => 'Recuperá la piscina que ya tenés',
            'intro' => [
                'Una piscina de hormigón vieja casi siempre se puede recuperar: se detecta la pérdida, se repara la estructura o la cañería, se cambia el revestimiento y se renueva el filtrado. Sale mucho menos que hacer una nueva.',
                'Empezamos con una prueba de pérdida y una revisión de la instalación. Con eso sabemos si el problema es de estructura, de cañería o de equipos, y cotizamos lo que corresponde.',
            ],
            'includes' => ['Detección de pérdidas en vaso y cañerías', 'Reparación estructural y sellado', 'Cambio de revestimiento: venecitas, cerámica o pintura', 'Renovación de filtro, bomba e iluminación', 'Vereda nueva y bordes'],
            'ideal' => ['La piscina pierde agua y no sabés por dónde.', 'El revestimiento está roto o manchado.', 'Compraste una casa con piscina en mal estado.'],
            'faqs' => [
                ['¿Cómo saben si pierde por la estructura o por la cañería?', 'Con pruebas de nivel con y sin el circuito de filtrado, y presurizando las cañerías. Es el primer paso antes de cotizar.'],
                ['¿Se puede cambiar la forma de una piscina existente?', 'Dentro de ciertos límites: reducir profundidad, agregar escalones o un sector para chicos. Ampliar el vaso es más complejo.'],
                ['¿Cuánto tiempo queda sin uso?', 'Depende del alcance. Un cambio de revestimiento es distinto a una reparación estructural. Lo detallamos en la propuesta.'],
            ],
            'related' => ['/piscinas/', '/quintas/refaccion/', '/patios/veredas/'],
        ],
    ],
    'quinchos' => [
        'cerrados' => [
            'name' => 'Quinchos cerrados',
            'title' => 'Construcción de quinchos cerrados en Paraguay | Obra',
            'description' => 'Quinchos cerrados con aberturas, aire acondicionado y baño en Asunción y Gran Asunción: para usarlos en verano con calor y en invierno con frío.',
            'h1' => 'Construcción de quinchos cerrados',
            'kicker' => 'Un ambiente más, todo el año',
            'intro' => [
                'El quincho cerrado se convirtió en el ambiente más usado de muchas casas: comedor de fin de semana, sala de juegos, lugar para recibir. Cerrarlo bien exige resolver el humo de la parrilla, la ventilación y la climatización.',
                'Construimos quinchos cerrados con aberturas corredizas para abrirlos en los días lindos, extracción de humo dimensionada y previsión de aire acondicionado.',
            ],
            'includes' => ['Cerramiento con aberturas corredizas de aluminio o PVC', 'Campana y extracción de humo dimensionadas', 'Previsión de aire acondicionado e instalación eléctrica', 'Baño y kitchenette', 'Aislación térmica en el techo'],
            'ideal' => ['Usás el quincho todo el año y el calor o el frío lo limitan.', 'Querés un ambiente de recepción separado de la casa.', 'Tenés un quincho abierto y querés cerrarlo.'],
            'faqs' => [
                ['¿La parrilla funciona bien en un quincho cerrado?', 'Sí, con una campana correcta, un ducto bien dimensionado y una entrada de aire. Sin eso, el humo se queda adentro.'],
                ['¿Se puede cerrar un quincho existente?', 'Sí. Revisamos la estructura, el techo y el piso y proponemos el cerramiento que corresponde.'],
                ['¿Necesita permiso municipal?', 'Un quincho cerrado suma superficie cubierta. Lo revisamos y coordinamos la documentación si corresponde.'],
            ],
            'related' => ['/quinchos/parrillas/', '/quinchos/techo-madera/', '/ampliaciones/galeria/'],
        ],
        'parrillas' => [
            'name' => 'Parrillas y asadores',
            'title' => 'Construcción de parrillas y asadores en Paraguay | Obra',
            'description' => 'Construcción de parrillas de ladrillo, asadores y hornos en Asunción y Gran Asunción: tiro correcto, mesada, bacha y fogón a la altura justa.',
            'h1' => 'Construcción de parrillas y asadores',
            'kicker' => 'El corazón del quincho',
            'intro' => [
                'Una parrilla que tira mal arruina el quincho. El tiro, la altura del fogón, el ancho de la boca y la campana se calculan, no se improvisan. Construimos parrillas de ladrillo refractario con mesada, bacha y espacio para leña o carbón.',
                'Podemos hacer la parrilla sola, dentro de un quincho existente, o como parte de un quincho nuevo.',
            ],
            'includes' => ['Parrilla de ladrillo refractario con tiro calculado', 'Campana y chimenea', 'Mesada de granito u hormigón con bacha', 'Horno de barro o de ladrillo opcional', 'Leñero y espacio de guardado'],
            'ideal' => ['Tu parrilla actual llena el quincho de humo.', 'Querés sumar una parrilla a una galería existente.', 'Buscás una parrilla con horno y mesada integrada.'],
            'faqs' => [
                ['¿Por qué mi parrilla tira mal?', 'Casi siempre por una campana mal proporcionada, una chimenea corta o sin salida libre, o una boca demasiado alta. Se puede corregir.'],
                ['¿Hacen parrillas a gas o eléctricas?', 'Preparamos la obra civil y las instalaciones para equipos a gas; el equipo lo elegís vos.'],
                ['¿Cuánto tarda construir una parrilla?', 'Es una obra corta comparada con un quincho completo. El plazo se define con el alcance y el secado de los materiales refractarios.'],
            ],
            'related' => ['/quinchos/', '/quinchos/cerrados/', '/patios/pergolas/'],
        ],
        'techo-madera' => [
            'name' => 'Quinchos con techo de madera',
            'title' => 'Quinchos con techo de madera y machimbre en Paraguay | Obra',
            'description' => 'Construcción de quinchos con estructura de madera, cielorraso de machimbre y tejas en Asunción y Gran Asunción, con la carpintería fabricada dentro del mismo grupo.',
            'h1' => 'Quinchos con techo de madera y machimbre',
            'kicker' => 'Madera vista, bien tratada',
            'intro' => [
                'El techo de madera con machimbre es el clásico del quincho paraguayo: cálido, fresco y con un olor que ningún otro material da. Requiere madera bien estacionada, tratamiento contra insectos y humedad, y una estructura calculada para el peso de la teja.',
                'La carpintería la fabrica carpinteria.com.py, del mismo grupo, y la obra civil la hacemos nosotros. Un solo responsable para las dos partes.',
            ],
            'includes' => ['Estructura de madera dura: tijeras, cabriadas o vigas vistas', 'Cielorraso de machimbre con aislación', 'Cubierta de teja colonial, francesa o chapa', 'Tratamiento y terminación de la madera', 'Columnas de mampostería o madera'],
            'ideal' => ['Querés un quincho de estilo tradicional con madera a la vista.', 'Buscás un techo fresco para el verano.', 'Preferís coordinar carpintería y obra con un solo responsable.'],
            'faqs' => [
                ['¿Qué madera conviene para el techo?', 'Maderas duras bien estacionadas. Nuestra carpintería te asesora sobre especies disponibles y su comportamiento.'],
                ['¿El machimbre necesita mantenimiento?', 'Un barnizado o aceitado periódico. Lo explicamos al entregar.'],
                ['¿Se puede combinar madera con chapa?', 'Sí. Estructura y cielorraso de madera con cubierta de chapa aislada es una combinación habitual y económica.'],
            ],
            'related' => ['/quinchos/', '/patios/pergolas/', '/quintas/casa-campo/'],
            'link' => ['site' => 'carpinteria', 'text' => 'Estructuras de madera, machimbre y aberturas se fabrican en carpinteria.com.py.'],
        ],
    ],
    'reformas' => [
        'cocinas' => [
            'name' => 'Remodelación de cocinas',
            'title' => 'Remodelación de cocinas en Paraguay | Obra',
            'description' => 'Remodelación de cocinas en Asunción y Gran Asunción: distribución, instalaciones de agua, gas y electricidad, revestimientos, mesadas y muebles coordinados en una sola obra.',
            'h1' => 'Remodelación de cocinas',
            'kicker' => 'Distribución, instalaciones y terminación en una sola obra',
            'intro' => [
                'Remodelar la cocina es la reforma con más gremios por metro cuadrado: albañil, plomero, electricista, gasista, mueblero, marmolero. Cuando cada uno viene por su lado, el resultado se nota en los encuentros y en los tiempos.',
                'Nosotros coordinamos todo el proceso, desde la demolición hasta la instalación de la mesada y los artefactos, con una secuencia definida antes de empezar.',
            ],
            'includes' => ['Nueva distribución y demoliciones', 'Instalación de agua, desagüe, gas y electricidad', 'Revestimientos, pisos y cielorraso', 'Coordinación de muebles, mesadas y griferías', 'Iluminación y tomas donde se usan'],
            'ideal' => ['Tu cocina tiene una distribución que ya no funciona.', 'Querés integrar cocina y comedor.', 'Vas a renovar muebles y necesitás mover instalaciones.'],
            'faqs' => [
                ['¿Cuánto tiempo queda sin cocina?', 'Depende del alcance y de los tiempos de fabricación de muebles y mesadas. Lo secuenciamos para reducir los días sin uso.'],
                ['¿Incluyen los muebles?', 'Podemos coordinarlos con nuestra carpintería o con el proveedor que elijas. Lo que sí hacemos siempre es dejar la obra lista para su instalación.'],
                ['¿Puedo mover la cocina a otro ambiente?', 'Sí, si los desagües y la ventilación lo permiten. Lo verificamos en el relevamiento.'],
            ],
            'related' => ['/reformas/banos/', '/reformas/', '/ampliaciones/'],
        ],
        'banos' => [
            'name' => 'Remodelación de baños',
            'title' => 'Remodelación de baños en Paraguay | Obra',
            'description' => 'Remodelación de baños en Asunción y Gran Asunción: impermeabilización, instalaciones, revestimientos, ducha a nivel y sanitarios nuevos con un solo responsable.',
            'h1' => 'Remodelación de baños',
            'kicker' => 'Sin humedades y con la ducha bien resuelta',
            'intro' => [
                'Un baño mal remodelado se descubre a los meses: humedad en la pared del vecino, ducha que no drena, azulejos que se sueltan. La diferencia está en lo que no se ve: impermeabilización, pendientes y cañerías.',
                'Remodelamos baños completos o parciales, con ducha a nivel del piso, revestimientos grandes y sanitarios nuevos, cuidando la parte técnica antes que la estética.',
            ],
            'includes' => ['Demolición y retiro de revestimientos', 'Cañerías de agua y desagüe nuevas', 'Impermeabilización y pendientes de ducha', 'Revestimientos, piso y cielorraso', 'Sanitarios, grifería, mampara y accesorios'],
            'ideal' => ['El baño tiene humedad o pérdidas.', 'Querés una ducha a nivel del piso, más segura y moderna.', 'Vas a hacer un baño adaptado para una persona mayor.'],
            'faqs' => [
                ['¿Se puede cambiar la bañera por ducha a nivel?', 'Sí. Es una de las reformas más pedidas. Requiere rehacer el desagüe y la pendiente del piso.'],
                ['¿Cuántos días queda sin baño?', 'Depende del alcance. Si hay otro baño en la casa, la obra se organiza sin apuro; si es el único, priorizamos dejarlo usable cuanto antes.'],
                ['¿Hacen baños adaptados?', 'Sí: sin escalones, barrales, espacio de giro y grifería accesible.'],
            ],
            'related' => ['/reformas/cocinas/', '/ampliaciones/dormitorio/', '/reformas/'],
        ],
        'fachadas' => [
            'name' => 'Renovación de fachadas',
            'title' => 'Renovación de fachadas de casas en Paraguay | Obra',
            'description' => 'Renovación de fachadas en Asunción y Gran Asunción: revoque, revestimientos, aberturas, techo de acceso y muro frontal para cambiar la cara de la casa sin tocar el interior.',
            'h1' => 'Renovación de fachadas',
            'kicker' => 'Otra casa desde la calle',
            'intro' => [
                'La fachada es lo primero que se ve y lo último que se renueva. Cambiar revoque, aberturas, el techo del acceso y el muro frontal transforma la casa sin tocar el interior, y suma valor si pensás vender o alquilar.',
                'Trabajamos la fachada como una obra completa: humedades, revoques, revestimientos, aberturas, iluminación y muro de frente, con andamios y protección de la vereda.',
            ],
            'includes' => ['Reparación de humedades y revoques', 'Revestimientos: piedra, ladrillo visto o texturas', 'Cambio de aberturas de frente', 'Techo o pérgola de acceso y cochera', 'Muro frontal, portón e iluminación'],
            'ideal' => ['La casa está bien adentro pero se ve vieja desde afuera.', 'Vas a vender o alquilar y querés que impacte.', 'Querés sumar cochera cubierta y portón nuevo.'],
            'faqs' => [
                ['¿Puedo cambiar la fachada sin permiso?', 'Cambios de terminación no suelen requerirlo; cambios estructurales o de superficie cubierta sí. Lo revisamos.'],
                ['¿Cuánto dura una obra de fachada?', 'Depende del alcance y del clima, porque gran parte se hace a la intemperie. Se define en la propuesta.'],
                ['¿Incluyen la pintura?', 'Sí, cuando forma parte del alcance. Recomendamos definirla junto con el revestimiento.'],
            ],
            'related' => ['/muros/portones/', '/tinglados/cocheras/', '/reformas/'],
        ],
        'techos' => [
            'name' => 'Cambio y reparación de techos',
            'title' => 'Cambio y reparación de techos en Paraguay | Obra',
            'description' => 'Reparación y cambio de techos de tejas, chapa y losa en Asunción y Gran Asunción: filtraciones, estructura, aislación térmica y canaletas resueltas de raíz.',
            'h1' => 'Cambio y reparación de techos',
            'kicker' => 'Filtraciones resueltas de raíz',
            'intro' => [
                'Una filtración se parcha una vez. La segunda vez conviene entender la causa: tejas rotas, pendiente insuficiente, estructura vencida, canaletas tapadas o una losa sin membrana. Cada caso tiene una solución distinta.',
                'Reparamos y cambiamos techos completos: estructura, cubierta, aislación térmica, cielorraso y canaletas, con protección de la casa mientras dura la obra.',
            ],
            'includes' => ['Diagnóstico de la causa de la filtración', 'Cambio de tejas, chapa o membrana de losa', 'Refuerzo o reemplazo de estructura', 'Aislación térmica y cielorraso', 'Canaletas, bajadas y desagües'],
            'ideal' => ['El techo filtra y ya lo parchaste varias veces.', 'La casa es muy calurosa y el techo no tiene aislación.', 'Querés cambiar teja por chapa aislada o al revés.'],
            'faqs' => [
                ['¿Conviene reparar o cambiar todo el techo?', 'Depende del estado de la estructura y de cuánta cubierta está dañada. Lo evaluamos y te damos las dos opciones cuando existen.'],
                ['¿Se puede hacer con la casa habitada?', 'Sí. Trabajamos por sectores y protegemos con lonas cada tramo abierto.'],
                ['¿Qué aislación recomiendan?', 'Depende del tipo de cubierta y del presupuesto. Lo importante es que exista y esté bien colocada.'],
            ],
            'related' => ['/reformas/', '/tinglados/', '/quintas/refaccion/'],
        ],
    ],
    'ampliaciones' => [
        'planta-alta' => [
            'name' => 'Ampliación en planta alta',
            'title' => 'Ampliación en planta alta en Paraguay | Obra',
            'description' => 'Ampliación de casas en planta alta en Asunción y Gran Asunción: verificación de estructura, losa, escalera e instalaciones para sumar un piso sin perder el patio.',
            'h1' => 'Ampliación en planta alta',
            'kicker' => 'Crecer hacia arriba cuando el terreno no da más',
            'intro' => [
                'Construir un piso arriba es la ampliación más deseada en terrenos chicos y la que más verificación técnica exige. La pregunta no es si se puede, sino qué aguanta la estructura existente y qué hay que reforzar.',
                'Verificamos fundaciones, columnas y losa antes de proponer una solución. Después proyectamos la escalera, las instalaciones que suben y la forma de trabajar con la casa habitada.',
            ],
            'includes' => ['Verificación estructural de lo existente', 'Refuerzos de columnas o fundaciones si hacen falta', 'Losa nueva, escalera e instalaciones', 'Techo nuevo y aislación', 'Terminaciones y protección de la planta baja durante la obra'],
            'ideal' => ['Tu terreno es chico y necesitás más ambientes.', 'Querés un dormitorio en suite o un estudio arriba.', 'Preferís no perder el patio ni la cochera.'],
            'faqs' => [
                ['¿Cómo saben si mi casa aguanta un piso más?', 'Con un relevamiento de la estructura existente y, si hace falta, cateos en fundaciones. Con eso el ingeniero define refuerzos o confirma que se puede construir.'],
                ['¿Puedo seguir viviendo abajo?', 'En general sí. La planta baja se protege y se programa la obra para las etapas más invasivas.'],
                ['¿Necesito planos?', 'Sí. Una planta alta requiere proyecto y aprobación municipal. Lo incluimos en el alcance.'],
            ],
            'related' => ['/casas/duplex/', '/ampliaciones/dormitorio/', '/ampliaciones/'],
        ],
        'dormitorio' => [
            'name' => 'Ampliación de dormitorio y baño',
            'title' => 'Ampliación de dormitorio y baño en Paraguay | Obra',
            'description' => 'Ampliación de un dormitorio con baño en Asunción y Gran Asunción: la ampliación más común, resuelta con fundaciones, techo e instalaciones empalmadas a la casa.',
            'h1' => 'Ampliación de dormitorio y baño',
            'kicker' => 'La ampliación más pedida, bien hecha',
            'intro' => [
                'La familia crece, llega un familiar mayor o hace falta un espacio propio: un dormitorio con baño es la ampliación más común en Paraguay. Parece chica, pero toca todo: fundaciones, techo, desagües y electricidad.',
                'La hacemos como una obra completa, con el empalme al techo existente resuelto para que no filtre y las instalaciones conectadas correctamente.',
            ],
            'includes' => ['Fundaciones y mampostería del sector nuevo', 'Empalme de techos sin filtraciones', 'Baño con instalaciones conectadas a las existentes', 'Aberturas y terminaciones a tono con la casa', 'Protección y limpieza del sector habitado'],
            'ideal' => ['Necesitás un dormitorio más.', 'Va a vivir con ustedes un familiar mayor.', 'Querés una suite independiente con acceso propio.'],
            'faqs' => [
                ['¿Se puede conectar el baño nuevo a la instalación existente?', 'En general sí, respetando pendientes y ventilación. Lo verificamos en el relevamiento.'],
                ['¿Cuánto dura una ampliación de dormitorio?', 'Es una obra de pocas semanas comparada con una casa completa. El plazo se define con el alcance cerrado.'],
                ['¿Puedo hacerla independiente para alquilar?', 'Sí. Se proyecta con acceso propio, kitchenette y medidor separado si corresponde.'],
            ],
            'related' => ['/ampliaciones/', '/reformas/banos/', '/ampliaciones/galeria/'],
        ],
        'galeria' => [
            'name' => 'Galerías cubiertas',
            'title' => 'Construcción de galerías cubiertas en Paraguay | Obra',
            'description' => 'Construcción de galerías cubiertas en Asunción y Gran Asunción: la ampliación que más se usa, con techo, piso y conexión a la casa y al patio.',
            'h1' => 'Construcción de galerías cubiertas',
            'kicker' => 'El ambiente que más se usa en Paraguay',
            'intro' => [
                'En Paraguay se vive en la galería: es donde se toma tereré, donde comen los chicos, donde se recibe. Una galería bien hecha suma metros útiles a un costo mucho menor que un ambiente cerrado.',
                'Construimos galerías con techo de teja, chapa o losa, piso continuo con el interior, iluminación y previsión de ventilador o parrilla.',
            ],
            'includes' => ['Columnas y estructura del techo', 'Cubierta con aislación y canaletas', 'Piso exterior continuo o deck', 'Iluminación, tomas y ventiladores', 'Unión con la casa: aberturas y niveles'],
            'ideal' => ['Tu casa no tiene un espacio exterior cubierto.', 'Querés conectar el living con el patio.', 'Buscás un lugar para la parrilla sin construir un quincho completo.'],
            'faqs' => [
                ['¿Necesita fundaciones?', 'Sí, para las columnas y el contrapiso. Son menores que las de un ambiente cerrado, pero necesarias.'],
                ['¿Se puede cerrar después?', 'Sí, si se prevé desde el inicio. Una galería bien pensada se convierte en quincho cerrado más adelante.'],
                ['¿Qué techo conviene?', 'Depende del techo de la casa y del presupuesto. Teja para continuidad estética, chapa aislada por economía, losa para diseño moderno.'],
            ],
            'related' => ['/patios/pergolas/', '/quinchos/', '/ampliaciones/'],
        ],
    ],
    'patios' => [
        'veredas' => [
            'name' => 'Veredas y contrapisos',
            'title' => 'Veredas, contrapisos y pisos exteriores en Paraguay | Obra',
            'description' => 'Construcción de veredas, contrapisos y pisos exteriores en Asunción y Gran Asunción: base compactada, hormigón, juntas y pendientes para que no se agrieten ni junten agua.',
            'h1' => 'Veredas, contrapisos y pisos exteriores',
            'kicker' => 'Base bien hecha, piso que dura',
            'intro' => [
                'La vereda o el patio de hormigón que se agrieta o junta agua casi siempre falla por la base, no por la terminación. Suelo mal compactado, sin juntas y sin pendiente: el resultado se ve al primer año.',
                'Hacemos veredas, contrapisos y pisos exteriores con base compactada, malla, juntas de dilatación y pendientes hacia los desagües, listos para recibir cerámica, adoquín o piedra.',
            ],
            'includes' => ['Movimiento de suelo y compactación', 'Contrapiso de hormigón con malla y juntas', 'Pendientes y desagües pluviales', 'Terminación: cerámica, adoquín, piedra o alisado', 'Cordones, escalones y rampas'],
            'ideal' => ['Tu patio es de tierra o de un contrapiso roto.', 'Necesitás una vereda de acceso o perimetral.', 'Querés un piso para cochera o circulación de vehículos.'],
            'faqs' => [
                ['¿Por qué se agrietó mi contrapiso anterior?', 'Casi siempre por falta de compactación, de malla o de juntas. Un contrapiso bien hecho lleva las tres cosas.'],
                ['¿Qué terminación conviene para el sol?', 'Materiales claros y rugosos: se calientan menos y no resbalan. Lo vemos según el uso.'],
                ['¿Hacen pisos para vehículos pesados?', 'Sí, con espesor y armadura calculados para la carga.'],
            ],
            'related' => ['/patios/', '/muros/', '/tinglados/cocheras/'],
        ],
        'decks' => [
            'name' => 'Decks de madera y compuesto',
            'title' => 'Construcción de decks de madera y WPC en Paraguay | Obra',
            'description' => 'Construcción de decks de madera dura y compuesto (WPC) en Asunción y Gran Asunción, para piscina, galería o patio, con estructura ventilada y anclajes ocultos.',
            'h1' => 'Construcción de decks de madera y compuesto',
            'kicker' => 'Un piso cálido alrededor de la piscina o la galería',
            'intro' => [
                'El deck cambia un patio: es cálido a la vista, agradable para pisar descalzo y resuelve desniveles sin hormigón. El secreto está debajo: una estructura ventilada, anclajes que no oxidan y madera o compuesto elegidos según el uso.',
                'Construimos decks de madera dura tratada y de compuesto (WPC) alrededor de piscinas, en galerías y como terrazas elevadas.',
            ],
            'includes' => ['Estructura de apoyo ventilada y nivelada', 'Madera dura tratada o tablas de compuesto WPC', 'Anclajes ocultos y herrajes inoxidables', 'Bordes, escalones y encuentro con la piscina', 'Tratamiento y terminación'],
            'ideal' => ['Querés un piso agradable alrededor de la piscina.', 'Tenés un desnivel en el patio que el deck puede resolver.', 'Buscás renovar una galería sin obra húmeda.'],
            'faqs' => [
                ['¿Madera o compuesto?', 'La madera es más noble y necesita mantenimiento; el compuesto casi no lo necesita pero se calienta más al sol. Depende del uso y de cuánto lo querés cuidar.'],
                ['¿El deck aguanta el clima paraguayo?', 'Sí, con madera dura bien tratada o compuesto de calidad y una estructura ventilada que no acumule agua.'],
                ['¿Se puede hacer sobre un piso existente?', 'Sí, si el piso está nivelado y tiene desagüe. Es una forma rápida de renovar.'],
            ],
            'related' => ['/piscinas/', '/patios/pergolas/', '/patios/'],
        ],
        'pergolas' => [
            'name' => 'Pérgolas y galerías livianas',
            'title' => 'Construcción de pérgolas en Paraguay | Obra',
            'description' => 'Pérgolas de madera, metal y hormigón en Asunción y Gran Asunción: sombra para el patio, cochera o piscina con cubierta de policarbonato, chapa o vegetal.',
            'h1' => 'Construcción de pérgolas y galerías livianas',
            'kicker' => 'Sombra sin cerrar el patio',
            'intro' => [
                'Una pérgola da sombra sin encerrar. Sirve para el sector de la piscina, el acceso, la cochera o una galería que no justifica un techo completo. Puede quedar abierta o llevar cubierta de policarbonato, chapa o enredadera.',
                'Construimos pérgolas de madera dura, metal y hormigón, con fundaciones que aguantan viento y una cubierta elegida según lo que querés: sombra, protección de lluvia o las dos.',
            ],
            'includes' => ['Fundaciones y columnas', 'Estructura de madera, metal o hormigón', 'Cubierta: abierta, policarbonato, chapa o vegetal', 'Desagües cuando la cubierta es cerrada', 'Iluminación y ventiladores'],
            'ideal' => ['Necesitás sombra en el patio o en la piscina.', 'Querés un acceso cubierto sin obra pesada.', 'Buscás una cochera liviana.'],
            'faqs' => [
                ['¿Una pérgola protege de la lluvia?', 'Solo si lleva cubierta cerrada (policarbonato o chapa) y desagües. Una pérgola abierta filtra el sol, no el agua.'],
                ['¿Qué material dura más?', 'Metal galvanizado y hormigón casi no necesitan mantenimiento; la madera necesita tratamiento periódico pero es más cálida.'],
                ['¿Necesita permiso?', 'Una pérgola abierta en general no. Con cubierta cerrada suma superficie y puede requerirlo. Lo revisamos.'],
            ],
            'related' => ['/patios/decks/', '/ampliaciones/galeria/', '/tinglados/cocheras/'],
        ],
    ],
    'tinglados' => [
        'galpones' => [
            'name' => 'Galpones y depósitos',
            'title' => 'Construcción de galpones y depósitos en Paraguay | Obra',
            'description' => 'Construcción de galpones industriales y depósitos en Gran Asunción: estructura metálica de gran luz, piso para carga, portones y oficinas anexas.',
            'h1' => 'Construcción de galpones y depósitos',
            'kicker' => 'Área cubierta para operar',
            'intro' => [
                'Un galpón se proyecta por lo que va a pasar adentro: qué se guarda, qué vehículos entran, cuánta altura hace falta y cuánta carga soporta el piso. Con eso se define la luz de la estructura, el piso y los accesos.',
                'Construimos galpones y depósitos para comercios, logística y producción liviana, con oficinas, baños y áreas de carga integradas.',
            ],
            'includes' => ['Fundaciones y piso de hormigón para carga', 'Estructura metálica de gran luz', 'Cubierta y cerramientos laterales', 'Portones, muelles y accesos', 'Oficinas, baños e instalaciones'],
            'ideal' => ['Tu negocio necesita depósito propio.', 'Alquilás un galpón y querés construir el tuyo.', 'Necesitás un espacio de producción o taller.'],
            'faqs' => [
                ['¿Qué altura conviene?', 'Depende de lo que se almacena y de las maquinarias. Se define con vos antes de proyectar la estructura.'],
                ['¿El piso aguanta montacargas?', 'Se calcula para la carga real: espesor, armadura y juntas. Es uno de los puntos más importantes del galpón.'],
                ['¿Trabajan con fecha de operación?', 'Sí. La fecha objetivo entra en la planificación y las etapas se ordenan para cumplirla.'],
            ],
            'related' => ['/tinglados/', '/comerciales/', '/tinglados/cocheras/'],
        ],
        'cocheras' => [
            'name' => 'Cocheras y techos para autos',
            'title' => 'Construcción de cocheras y techos para autos en Paraguay | Obra',
            'description' => 'Cocheras cubiertas y techos para autos en Asunción y Gran Asunción: estructura metálica o de hormigón, cubierta aislada, piso y portón integrados al frente de la casa.',
            'h1' => 'Cocheras y techos para autos',
            'kicker' => 'El auto a la sombra, el frente mejor',
            'intro' => [
                'El sol paraguayo castiga los autos y las cocheras improvisadas afean el frente. Una cochera bien hecha protege el vehículo y mejora la fachada: se proyecta con el portón, el muro y el acceso como un conjunto.',
                'Construimos cocheras con estructura metálica o de hormigón, cubierta de chapa aislada, teja o losa, piso de hormigón o adoquines y portón integrado.',
            ],
            'includes' => ['Estructura metálica, de hormigón o mixta', 'Cubierta aislada con canaletas', 'Piso de hormigón o adoquines para vehículos', 'Portón manual o automatizado', 'Iluminación y previsión de cargador eléctrico'],
            'ideal' => ['Tu auto queda al sol o a la lluvia.', 'Querés renovar el frente junto con la cochera.', 'Necesitás cochera para dos o más vehículos.'],
            'faqs' => [
                ['¿Chapa, teja o losa?', 'Chapa aislada es la más económica, teja continúa el estilo de la casa, losa permite usar el espacio arriba. Depende del proyecto.'],
                ['¿Pueden automatizar el portón?', 'Sí. Dejamos la instalación eléctrica y coordinamos el equipo de automatización.'],
                ['¿Se puede hacer una cochera sin columnas al frente?', 'Sí, con una estructura en voladizo calculada. Es más costosa pero deja el acceso libre.'],
            ],
            'related' => ['/muros/portones/', '/reformas/fachadas/', '/tinglados/'],
        ],
    ],
    'muros' => [
        'portones' => [
            'name' => 'Portones y accesos',
            'title' => 'Construcción de portones y accesos en Paraguay | Obra',
            'description' => 'Portones corredizos, batientes y automatizados con su obra civil en Asunción y Gran Asunción: columnas, guías, fundaciones, muro de frente y acceso vehicular.',
            'h1' => 'Construcción de portones y accesos',
            'kicker' => 'La obra civil que hace funcionar el portón',
            'intro' => [
                'Un portón que se traba o se descuelga casi nunca falla por el portón: falla la columna, la guía o la fundación. La obra civil del acceso es tan importante como el herraje.',
                'Hacemos columnas, fundaciones, guías, muro de frente y rampas de acceso, y coordinamos la herrería y la automatización para que el conjunto funcione desde el primer día.',
            ],
            'includes' => ['Fundaciones y columnas de mampostería u hormigón', 'Guía y contrapeso para portones corredizos', 'Rampa y piso de acceso vehicular', 'Muro de frente y pilares con iluminación', 'Coordinación de herrería y automatización'],
            'ideal' => ['Tu portón se traba o la columna se movió.', 'Querés cambiar un portón batiente por corredizo.', 'Estás haciendo el muro de frente y querés resolver el acceso a la vez.'],
            'faqs' => [
                ['¿Hacen el portón de hierro también?', 'Coordinamos la herrería con talleres que conocemos. Nosotros hacemos la obra civil y la integración.'],
                ['¿Cuánto espacio necesita un portón corredizo?', 'El ancho del vano más un tramo libre lateral por donde corre la hoja. Lo verificamos sobre tu frente.'],
                ['¿La automatización se puede agregar después?', 'Sí, si se dejó la instalación eléctrica prevista. Lo hacemos siempre.'],
            ],
            'related' => ['/muros/', '/tinglados/cocheras/', '/reformas/fachadas/'],
        ],
    ],
    'comerciales' => [
        'locales' => [
            'name' => 'Adecuación de locales comerciales',
            'title' => 'Adecuación de locales comerciales en Paraguay | Obra',
            'description' => 'Adecuación de locales comerciales en Asunción y Gran Asunción: obra civil, instalaciones, vidriera, baños y terminaciones con fecha de apertura comprometida.',
            'h1' => 'Adecuación de locales comerciales',
            'kicker' => 'Del local vacío a la apertura',
            'intro' => [
                'Un local alquilado empieza a costar desde el primer día. Por eso la adecuación se planifica con la fecha de apertura como meta: qué permisos hacen falta, qué instalaciones exige el rubro, qué se puede fabricar mientras se hace la obra.',
                'Adecuamos locales de gastronomía, retail, salud y servicios: divisiones, instalaciones, vidriera, baños, pisos, cielorrasos e iluminación.',
            ],
            'includes' => ['Relevamiento del local y del contrato de alquiler', 'Demoliciones, divisiones y obra civil', 'Instalaciones eléctricas, sanitarias, datos y climatización', 'Vidriera, fachada y cartelería (obra civil)', 'Pisos, cielorrasos e iluminación'],
            'ideal' => ['Firmaste el alquiler y tenés fecha de apertura.', 'El local necesita baños o cocina que no tiene.', 'Querés un solo responsable para no coordinar diez proveedores.'],
            'faqs' => [
                ['¿Pueden cumplir una fecha de apertura?', 'Sí, cuando el alcance se cierra a tiempo y las decisiones se toman en fecha. La planificación se hace hacia atrás desde la apertura.'],
                ['¿Trabajan de noche o fines de semana?', 'Se acuerda según el edificio, los vecinos y la seguridad. No lo damos por hecho.'],
                ['¿Hacen locales gastronómicos?', 'Sí. Coordinamos extracción, gas, desagües con interceptor de grasa y las instalaciones que exige el rubro.'],
            ],
            'related' => ['/comerciales/oficinas/', '/comerciales/', '/tinglados/galpones/'],
        ],
        'oficinas' => [
            'name' => 'Oficinas y consultorios',
            'title' => 'Remodelación de oficinas y consultorios en Paraguay | Obra',
            'description' => 'Remodelación y adecuación de oficinas y consultorios en Asunción: divisiones, cableado de datos, climatización, baños y terminaciones con mínima interrupción de la actividad.',
            'h1' => 'Remodelación de oficinas y consultorios',
            'kicker' => 'Un lugar listo para trabajar y atender',
            'intro' => [
                'Oficinas y consultorios tienen exigencias propias: privacidad acústica, cableado de datos, climatización por ambiente, baños accesibles y, en salud, requisitos de habilitación.',
                'Remodelamos y adecuamos oficinas y consultorios, muchas veces con la actividad en marcha, organizando la obra por sectores y horarios.',
            ],
            'includes' => ['Divisiones con aislación acústica', 'Cableado eléctrico y de datos', 'Climatización por ambiente', 'Baños y sala de espera', 'Pisos, cielorrasos e iluminación de trabajo'],
            'ideal' => ['Alquilaste una oficina y hay que dividirla.', 'Vas a abrir un consultorio y necesitás cumplir requisitos.', 'Querés remodelar sin cerrar la oficina.'],
            'faqs' => [
                ['¿Pueden trabajar con la oficina funcionando?', 'Sí, por sectores y fuera del horario más crítico. Lo planificamos con vos.'],
                ['¿Conocen los requisitos para consultorios?', 'Relevamos los requisitos del rubro y de la habilitación local y los incorporamos al proyecto.'],
                ['¿Incluyen el mobiliario?', 'Podemos coordinarlo con nuestra carpintería. La propuesta aclara qué provee Obra y qué contratás vos.'],
            ],
            'related' => ['/comerciales/locales/', '/comerciales/', '/reformas/'],
        ],
    ],
    'supervision' => [
        'direccion' => [
            'name' => 'Dirección técnica de obra',
            'title' => 'Dirección técnica de obra en Paraguay | Obra',
            'description' => 'Dirección técnica y profesional responsable de obra en Asunción y Gran Asunción: ingeniero a cargo de la ejecución, certificaciones y responsabilidad ante el municipio y el banco.',
            'h1' => 'Dirección técnica de obra',
            'kicker' => 'Un profesional responsable de tu obra',
            'intro' => [
                'La dirección técnica es más que supervisar: el profesional toma las decisiones de ejecución, firma como responsable ante el municipio y certifica avances para el banco. Es lo que exigen muchos permisos y la mayoría de los créditos de construcción.',
                'Ofrecemos dirección técnica para obras que ejecuta otro constructor o un maestro de obra, con visitas programadas, informes y certificaciones.',
            ],
            'includes' => ['Profesional responsable ante el municipio', 'Decisiones técnicas de ejecución en obra', 'Certificaciones de avance para desembolsos', 'Informes con fotos y observaciones', 'Recepción final y documentación'],
            'ideal' => ['El municipio o el banco te piden un profesional responsable.', 'Contrataste un maestro de obra y querés dirección técnica.', 'Necesitás certificaciones para los desembolsos del crédito.'],
            'faqs' => [
                ['¿Qué diferencia hay con la supervisión?', 'La supervisión controla; la dirección técnica decide y asume la responsabilidad profesional. Muchas veces hace falta la segunda por exigencia legal o bancaria.'],
                ['¿Pueden dirigir una obra con planos de otro arquitecto?', 'Sí. Revisamos el proyecto y dirigimos su ejecución.'],
                ['¿Qué pasa si la obra ya empezó sin dirección?', 'Hacemos un relevamiento del estado y asumimos la dirección desde ese punto, documentando lo previo.'],
            ],
            'related' => ['/supervision/', '/presupuesto/', '/credito/'],
        ],
    ],
];
