<?php
declare(strict_types=1);

// Contenido editorial del sitio. Slugs cortos de un nivel (regla: <=15 caracteres, aptos para
// la ruta visible de Google Ads). El orden define la prioridad en home, footer y sitemap.
// 'link' = un solo enlace contextual por pagina hacia otro sitio del grupo (ver config partner_sites).
return [
    'services' => [
        'casas' => [
            'name' => 'Casas llave en mano',
            'short' => 'Planos, obra gruesa, instalaciones y terminaciones en una sola contratación.',
            'title' => 'Construcción de casas llave en mano en Paraguay | Obra',
            'description' => 'Casas llave en mano en Asunción y Gran Asunción: platea, mampostería, techo, instalaciones y terminaciones con un responsable. Pedí evaluar tu terreno.',
            'h1' => 'Construcción de casas llave en mano en Paraguay',
            'kicker' => 'De un terreno a una casa lista para habitar',
            'image' => 'hero-casa.webp',
            'image_alt' => 'Casa contemporánea de ladrillo visto con galería y jardín, estilo paraguayo moderno',
            'includes' => ['Revisión del terreno, niveles y accesos', 'Planos y aprobación municipal dentro del alcance', 'Platea, mampostería y estructura', 'Techo, instalaciones eléctricas y sanitarias', 'Aberturas, revestimientos y terminaciones', 'Entrega con recorrido final y detalle de lo ejecutado'],
            'ideal' => ['Tenés un terreno y querés una sola empresa a cargo de toda la obra.', 'Querés construir desde cero sin coordinar albañil, electricista y plomero por separado.', 'Necesitás definir etapas y alcance antes de cotizar.', 'Querés comparar propuestas con el mismo alcance y las mismas terminaciones.'],
            'faqs' => [
                ['¿Qué incluye una casa llave en mano?', 'Todo lo necesario para entregarte la casa lista para habitar: planos y aprobación, platea, mampostería, techo, instalaciones, aberturas y terminaciones. La propuesta detalla por escrito qué queda incluido y qué no.'],
                ['¿Cuánto cuesta construir una casa en Paraguay?', 'Depende de los metros cuadrados, el terreno, el sistema constructivo, las instalaciones y el nivel de terminación. Primero relevamos esos datos y después preparamos un presupuesto por rubro en guaraníes.'],
                ['¿Cuánto tarda la obra?', 'El plazo se define con el alcance cerrado y se detalla en la propuesta por etapas. No damos plazos antes de conocer el terreno y el proyecto.'],
                ['¿Puedo construir con crédito bancario o AFD?', 'Sí. Muchos clientes construyen con crédito. Te indicamos qué documentación de obra suele pedir el banco y ajustamos el cronograma a los desembolsos.'],
                ['¿Trabajan con un plano que ya tengo?', 'Sí. Revisamos la documentación existente, definimos qué falta y presupuestamos la ejecución sobre ese proyecto.'],
            ],
            'related' => ['quintas', 'piscinas', 'muros'],
            'link' => ['site' => 'arq', 'text' => 'Si solo necesitás el proyecto, los renders o la carpeta municipal, ese trabajo lo hace nuestro estudio en arq.com.py.'],
        ],
        'quintas' => [
            'name' => 'Quintas y casas de campo',
            'short' => 'Casa, quincho, piscina, pozo y cerramiento coordinados por una sola empresa.',
            'title' => 'Construcción de quintas y casas de campo en Paraguay | Obra',
            'description' => 'Construcción y refacción de quintas en Paraguay: casa de campo, quincho, piscina, accesos, pozo y muro perimetral coordinados en un solo proyecto.',
            'h1' => 'Construcción de quintas y casas de campo en Paraguay',
            'kicker' => 'Un conjunto completo, no obras sueltas',
            'image' => 'hero-casa.webp',
            'image_alt' => 'Casa de una planta con galería amplia y jardín arbolado',
            'includes' => ['Plan general de intervención por sectores', 'Casa principal o casa de campo', 'Quincho, galería y áreas exteriores', 'Piscina y circulaciones', 'Muro perimetral, portón y accesos', 'Coordinación de pozo, agua y electricidad'],
            'ideal' => ['Compraste una quinta que necesita una puesta a punto integral.', 'Querés construir una casa de campo desde cero.', 'Tenés varias obras que comparten terreno, agua y electricidad.', 'Querés ejecutar por etapas con una visión completa.'],
            'faqs' => [
                ['¿Pueden encargarse de toda la quinta?', 'Sí. Coordinamos casa, quincho, piscina, exteriores, pozo y cerramientos dentro de un alcance general definido antes de empezar.'],
                ['¿Y si la quinta no tiene agua corriente?', 'Coordinamos la perforación del pozo y la instalación de bomba y tanque como parte del proyecto, para que la obra no dependa de un proveedor suelto.'],
                ['¿Se puede refaccionar una construcción existente?', 'Sí. Primero revisamos el estado visible y la documentación disponible para definir qué evaluación adicional hace falta.'],
                ['¿Cómo se cotiza una quinta completa?', 'Por sectores y rubros. Así entendés prioridades, dependencias y alternativas antes de contratar.'],
            ],
            'related' => ['casas', 'piscinas', 'quinchos'],
            'link' => ['site' => 'pozo', 'text' => 'Si la quinta necesita agua propia, la perforación de pozo artesiano la coordinamos con pozo.com.py.'],
        ],
        'piscinas' => [
            'name' => 'Piscinas de hormigón',
            'short' => 'Piscinas de hormigón armado con vereda, filtrado e iluminación.',
            'title' => 'Construcción de piscinas de hormigón en Paraguay | Obra',
            'description' => 'Construcción de piscinas de hormigón en Asunción y Gran Asunción: excavación, estructura, vereda, filtrado e iluminación. Consultá por tu patio o quinta.',
            'h1' => 'Construcción de piscinas de hormigón en Paraguay',
            'kicker' => 'Una piscina pensada como parte del patio',
            'image' => 'servicio-piscina.webp',
            'image_alt' => 'Piscina de hormigón con vereda clara y vegetación tropical',
            'includes' => ['Evaluación del espacio y acceso para la excavación', 'Excavación y estructura de hormigón armado', 'Instalación hidráulica y sistema de filtrado', 'Terminación interior y bordes', 'Vereda, iluminación y área inmediata'],
            'ideal' => ['Querés una piscina nueva para tu casa o quinta.', 'Necesitás integrar piscina, quincho y circulación exterior.', 'Tu patio tiene accesos o medidas que condicionan la obra.', 'Querés definir equipos y terminaciones antes de ejecutar.'],
            'faqs' => [
                ['¿Cuánto cuesta una piscina de hormigón?', 'Cambia por medidas, profundidad, acceso para excavación, tipo de suelo, terminación, filtrado y obras complementarias. Cotizamos después de conocer el lugar y el alcance.'],
                ['¿Cuándo conviene empezar?', 'La temporada de uso arranca con el calor, así que conviene consultar antes de septiembre para tenerla lista para el verano. Igual construimos todo el año.'],
                ['¿La piscina incluye filtro e iluminación?', 'Sí, podemos integrarlos en el alcance. Cada propuesta especifica equipos, conexiones y terminaciones incluidas.'],
                ['¿Pueden construir piscina y quincho juntos?', 'Sí. Coordinar ambos desde el inicio resuelve niveles, instalaciones, circulación y drenaje como un solo conjunto.'],
            ],
            'related' => ['quinchos', 'quintas', 'patios'],
        ],
        'quinchos' => [
            'name' => 'Quinchos con parrilla',
            'short' => 'Parrilla, mesada, bacha, techo e iluminación integrados a tu patio.',
            'title' => 'Construcción de quinchos con parrilla en Paraguay | Obra',
            'description' => 'Construcción de quinchos con parrilla en Asunción y Gran Asunción: estructura, techo, parrilla, mesada, bacha e instalaciones en una sola obra.',
            'h1' => 'Construcción de quinchos con parrilla en Paraguay',
            'kicker' => 'Donde la casa se encuentra con el patio',
            'image' => 'servicio-quincho.webp',
            'image_alt' => 'Quincho abierto con parrilla de ladrillo, mesa y jardín',
            'includes' => ['Definición de tamaño, ubicación y estilo', 'Estructura y techo (tejas, chapa o madera)', 'Parrilla, mesada y bacha', 'Instalación eléctrica e hidráulica', 'Pisos, iluminación y terminaciones'],
            'ideal' => ['Querés sumar un área de asado a una casa existente.', 'Buscás conectar cocina, galería y patio.', 'Necesitás un quincho para una quinta o casa de fin de semana.', 'Querés hacer quincho y piscina en una misma obra.'],
            'faqs' => [
                ['¿Cuánto cuesta construir un quincho?', 'Depende de las medidas, el tipo de techo, la estructura, la parrilla, las instalaciones y las terminaciones. Con esos datos armamos el presupuesto.'],
                ['¿Puede incluir baño y depósito?', 'Sí. Se pueden sumar ambientes complementarios según espacio, instalaciones y alcance.'],
                ['¿Construyen quinchos en casas ya habitadas?', 'Sí. Planificamos accesos, protección de las áreas existentes y la secuencia de trabajo según el lugar.'],
                ['¿Puedo pedir solamente techo y parrilla?', 'Sí. El alcance puede ajustarse a una intervención puntual siempre que la solución sea técnicamente viable.'],
            ],
            'related' => ['piscinas', 'patios', 'quintas'],
            'link' => ['site' => 'carpinteria', 'path' => '/aluminio/', 'text' => 'Si querés cerrar el quincho con aberturas de aluminio o blindex, esas piezas las fabrica carpinteria.com.py y las colocamos dentro de la misma obra.'],
        ],
        'reformas' => [
            'name' => 'Reformas y remodelaciones',
            'short' => 'Reorganizá ambientes, renová instalaciones y terminaciones sobre lo que ya tenés.',
            'title' => 'Reformas y remodelación de casas en Paraguay | Obra',
            'description' => 'Reformas y remodelación de casas en Asunción y Gran Asunción: demoliciones, albañilería, instalaciones y terminaciones con alcance claro y un responsable.',
            'h1' => 'Reformas y remodelación de casas en Paraguay',
            'kicker' => 'Hacé que la casa acompañe una nueva etapa',
            'image' => 'hero-casa.webp',
            'image_alt' => 'Vivienda contemporánea renovada con galería y jardín',
            'includes' => ['Relevamiento de lo existente', 'Demoliciones y retiro de escombros', 'Albañilería e instalaciones nuevas', 'Revestimientos, pisos y pintura', 'Plan de trabajo para reducir molestias si la casa está habitada'],
            'ideal' => ['La distribución actual ya no funciona para tu familia.', 'Querés integrar ambientes o abrir la casa hacia el patio.', 'Compraste una casa y querés renovarla antes de mudarte.', 'Querés poner en valor una casa antes de alquilarla o venderla.'],
            'faqs' => [
                ['¿Cuánto cuesta remodelar una casa?', 'Depende del sector, el estado de la estructura y las instalaciones, las demoliciones y el nivel de terminación. Una visita inicial permite definir el alcance y presupuestar por rubro.'],
                ['¿Se puede remodelar sin salir de la casa?', 'Muchas veces sí, por etapas y aislando sectores. Algunas intervenciones requieren desocupar áreas temporalmente por seguridad.'],
                ['¿Hacen demoliciones y retiro de escombros?', 'Sí, cuando forman parte de la reforma. Quedan detallados en la propuesta.'],
                ['¿Necesito planos para una reforma?', 'Para cambios estructurales o de fachada suele hacer falta documentación municipal. Lo revisamos en el relevamiento y te decimos qué corresponde.'],
            ],
            'related' => ['ampliaciones', 'patios', 'casas'],
            'link' => ['site' => 'arq', 'path' => '/regularizacion/', 'text' => 'Si la construcción existente no tiene planos aprobados, la regularización la hace nuestro estudio en arq.com.py antes o durante la reforma.'],
        ],
        'ampliaciones' => [
            'name' => 'Ampliaciones de vivienda',
            'short' => 'Un dormitorio, una planta alta o un área social nueva sobre la casa actual.',
            'title' => 'Ampliación de casas en Paraguay | Obra',
            'description' => 'Ampliación de casas en Asunción y Gran Asunción: dormitorios, planta alta, galerías y áreas sociales sumados a lo existente, con estructura resuelta.',
            'h1' => 'Ampliación de casas en Paraguay',
            'kicker' => 'Más metros sin mudarte',
            'image' => 'hero-casa.webp',
            'image_alt' => 'Casa ampliada hacia una galería cubierta y jardín',
            'includes' => ['Verificación de estructura y fundaciones existentes', 'Planos de ampliación y aprobación cuando corresponde', 'Obra gruesa del sector nuevo', 'Empalme de techos, instalaciones y desagües', 'Terminaciones a tono con la casa actual'],
            'ideal' => ['La familia creció y necesitás un dormitorio o baño más.', 'Querés sumar una planta alta o un estudio.', 'Buscás una galería o área social conectada al patio.', 'Tu terreno tiene lugar y querés aprovecharlo antes que mudarte.'],
            'faqs' => [
                ['¿Cuánto cuesta ampliar una casa?', 'Depende del área a sumar, la estructura existente, si es en planta baja o planta alta, las instalaciones y el nivel de terminación. Relevamos primero y cotizamos por rubro.'],
                ['¿Se puede construir una planta alta sobre mi casa?', 'Depende de la estructura y las fundaciones existentes. Lo verificamos antes de proponer una solución.'],
                ['¿La ampliación necesita permiso municipal?', 'En general sí. Incluimos la documentación necesaria en el alcance o trabajamos sobre los planos que ya tengas.'],
                ['¿Puedo seguir viviendo en la casa durante la obra?', 'Normalmente sí. Planificamos la secuencia para aislar el sector en obra y minimizar polvo y ruido.'],
            ],
            'related' => ['reformas', 'patios', 'tinglados'],
        ],
        'patios' => [
            'name' => 'Patios, decks y pérgolas',
            'short' => 'Veredas, decks, pérgolas y galerías para usar el exterior todo el año.',
            'title' => 'Patios, decks y pérgolas en Paraguay | Obra',
            'description' => 'Construcción de patios, veredas, decks, pérgolas y galerías en Asunción y Gran Asunción. Exteriores integrados a la casa, el quincho o la piscina.',
            'h1' => 'Patios, decks y pérgolas en Paraguay',
            'kicker' => 'Más sombra, circulación y vida al aire libre',
            'image' => 'servicio-cochera.webp',
            'image_alt' => 'Estructura liviana de metal y madera sobre un patio de adoquines',
            'includes' => ['Evaluación de asoleamiento y escurrimiento del agua', 'Contrapiso, vereda o adoquinado', 'Deck de madera o compuesto', 'Pérgola o galería con estructura y cubierta', 'Encuentros con jardín, casa y piscina'],
            'ideal' => ['Querés ganar sombra sin cerrar el patio.', 'Necesitás mejorar la circulación entre casa, quincho y piscina.', 'Buscás renovar un exterior deteriorado.', 'Querés un deck o una galería liviana.'],
            'faqs' => [
                ['¿Qué conviene: deck, piso o adoquinado?', 'Depende del uso, la exposición al agua, el mantenimiento esperado y el soporte existente. Lo evaluamos antes de recomendar.'],
                ['¿Las pérgolas protegen de la lluvia?', 'Una pérgola abierta filtra el sol. Para lluvia hace falta una cubierta y resolver los desagües. El alcance se define según el uso.'],
                ['¿Pueden integrar el trabajo con una piscina?', 'Sí. Coordinamos niveles, bordes, drenajes y superficies antideslizantes desde el inicio.'],
                ['¿Hacen solamente el patio?', 'Sí. Una intervención exterior independiente se cotiza igual, con su alcance por escrito.'],
            ],
            'related' => ['quinchos', 'piscinas', 'muros'],
        ],
        'tinglados' => [
            'name' => 'Tinglados, galpones y cocheras',
            'short' => 'Estructura metálica y cubierta para vehículos, depósito o producción.',
            'title' => 'Construcción de tinglados y galpones en Paraguay | Obra',
            'description' => 'Construcción de tinglados y galpones en Asunción y Gran Asunción: estructura metálica, cubierta, canaletas y piso según el uso residencial o comercial.',
            'h1' => 'Construcción de tinglados, galpones y cocheras en Paraguay',
            'kicker' => 'Cubiertas resueltas para el clima y el uso real',
            'image' => 'servicio-cochera.webp',
            'image_alt' => 'Cochera moderna con estructura metálica y cubierta liviana',
            'includes' => ['Definición de uso, luces y apoyos', 'Fundaciones y estructura metálica', 'Cubierta y aislación según alcance', 'Canaletas y conducción del agua', 'Contrapiso, portones e iluminación'],
            'ideal' => ['Necesitás proteger vehículos del sol y la lluvia.', 'Querés un galpón para depósito, taller o producción.', 'Tu negocio necesita área cubierta para operar.', 'Querés ampliar una galería o un área de trabajo.'],
            'faqs' => [
                ['¿Cuánto cuesta un tinglado o galpón?', 'Depende de las medidas, la luz estructural, el material, la cubierta, la aislación, el piso y los accesos. Cotizamos con un alcance definido.'],
                ['¿Trabajan con estructura metálica?', 'Sí. Evaluamos estructura metálica, de madera o mixta según dimensiones, uso y presupuesto.'],
                ['¿Incluyen canaletas y desagües?', 'Sí. Son parte importante de la solución y se detallan en el alcance.'],
                ['¿Hacen tinglados para empresas?', 'Sí. Coordinamos obras comerciales e industriales livianas con fecha objetivo y etapas.'],
            ],
            'related' => ['patios', 'comerciales', 'muros'],
        ],
        'muros' => [
            'name' => 'Muros perimetrales y cerramientos',
            'short' => 'Muralla, portón y acceso integrados a la propiedad.',
            'title' => 'Muros perimetrales y murallas en Paraguay | Obra',
            'description' => 'Construcción de muros perimetrales, murallas, portones y accesos en Asunción y Gran Asunción para casas, quintas y terrenos.',
            'h1' => 'Muros perimetrales y murallas en Paraguay',
            'kicker' => 'Privacidad y acceso desde el límite del terreno',
            'image' => 'servicio-cochera.webp',
            'image_alt' => 'Acceso residencial con estructura metálica, pavimento y jardín',
            'includes' => ['Medición y verificación de límites', 'Fundaciones y mampostería', 'Revoque, terminación y pintura', 'Previsión de portón y accesos', 'Drenaje y encuentro con vereda o patio'],
            'ideal' => ['Necesitás cerrar un terreno o una quinta.', 'Querés renovar el frente y el acceso de la casa.', 'Buscás integrar muralla, portón y cochera.', 'El proyecto completo necesita resolver perímetro y seguridad.'],
            'faqs' => [
                ['¿Cuánto cuesta construir una muralla?', 'Depende de la longitud, la altura, la fundación, el terreno, la terminación y los accesos. Con esas medidas presupuestamos.'],
                ['¿Incluyen portón?', 'El portón y su automatización pueden coordinarse dentro del proyecto, con provisiones y responsabilidades detalladas.'],
                ['¿Hacen cerramientos para quintas y terrenos grandes?', 'Sí. Evaluamos extensión, accesos y ejecución por etapas.'],
                ['¿Pueden renovar solamente el frente?', 'Sí. Un frente, acceso o tramo específico se cotiza como intervención independiente.'],
            ],
            'related' => ['tinglados', 'quintas', 'casas'],
        ],
        'comerciales' => [
            'name' => 'Obras comerciales',
            'short' => 'Locales, oficinas y consultorios preparados para operar en fecha.',
            'title' => 'Obras comerciales y adecuación de locales en Paraguay | Obra',
            'description' => 'Obras comerciales y adecuación de locales, oficinas y consultorios en Asunción y Gran Asunción: obra civil, instalaciones y terminaciones coordinadas.',
            'h1' => 'Obras comerciales y adecuación de locales en Paraguay',
            'kicker' => 'Un espacio listo para trabajar, en fecha',
            'image' => 'hero-casa.webp',
            'image_alt' => 'Arquitectura contemporánea de ladrillo con galería y amplias aberturas',
            'includes' => ['Relevamiento del local o inmueble', 'Demoliciones, divisiones y obra civil', 'Instalaciones eléctricas, sanitarias y de datos', 'Pisos, cielorrasos, iluminación y terminaciones', 'Planificación por etapas con fecha objetivo'],
            'ideal' => ['Alquilaste un local y necesitás adaptarlo.', 'Querés remodelar una oficina o un consultorio.', 'La operación requiere instalaciones o sectores nuevos.', 'Buscás un solo responsable de obra y terminaciones.'],
            'faqs' => [
                ['¿Qué tipo de obras comerciales realizan?', 'Locales, oficinas, consultorios y espacios operativos. El alcance depende del inmueble, el uso y los requisitos del proyecto.'],
                ['¿Pueden trabajar con una fecha de apertura?', 'Sí. La fecha objetivo se incorpora a la planificación. La viabilidad depende del alcance, los permisos y los tiempos de provisión.'],
                ['¿Trabajan fuera del horario comercial?', 'Se acuerda según el lugar, las restricciones del inmueble y la seguridad de la obra.'],
                ['¿Incluyen mobiliario y cartelería?', 'Podemos coordinar rubros complementarios cuando forman parte del alcance. La propuesta aclara qué provee Obra y qué contratás vos.'],
            ],
            'related' => ['tinglados', 'reformas', 'supervision'],
        ],
        'supervision' => [
            'name' => 'Supervisión y fiscalización de obra',
            'short' => 'Un ingeniero responsable que controla tu obra aunque la ejecute otro.',
            'title' => 'Supervisión y fiscalización de obra en Paraguay | Obra',
            'description' => 'Supervisión, fiscalización y dirección de obra en Asunción y Gran Asunción: control de avances, calidad, certificaciones y pagos con un profesional responsable.',
            'h1' => 'Supervisión y fiscalización de obra en Paraguay',
            'kicker' => 'Alguien de tu lado mirando la obra',
            'image' => 'servicio-cochera.webp',
            'image_alt' => 'Obra en construcción con estructura metálica y piso terminado',
            'includes' => ['Revisión del contrato, planos y presupuesto vigente', 'Visitas de control con informe de avance', 'Verificación de calidad de materiales y ejecución', 'Control de certificaciones y pagos por etapa', 'Recepción final con lista de pendientes'],
            'ideal' => ['Contrataste un maestro de obra y querés control profesional.', 'Vivís lejos de la obra o en el exterior.', 'La obra se atrasó o superó el presupuesto y necesitás ordenarla.', 'El banco o el municipio exigen un profesional responsable.'],
            'faqs' => [
                ['¿Qué diferencia hay entre supervisión y dirección de obra?', 'La supervisión controla que la obra siga el proyecto y el contrato. La dirección técnica además toma decisiones de ejecución y asume la responsabilidad profesional ante el municipio.'],
                ['¿Pueden supervisar una obra que ya empezó?', 'Sí. Hacemos un relevamiento del estado, revisamos lo pagado y lo ejecutado y proponemos un plan de control desde ese punto.'],
                ['¿Con qué frecuencia visitan la obra?', 'Se define según la etapa y el ritmo de la obra, y queda por escrito en la propuesta.'],
                ['¿Cuánto cuesta la supervisión?', 'Depende del tamaño de la obra, la frecuencia de visitas y el alcance del control. Se cotiza aparte de la ejecución.'],
            ],
            'related' => ['presupuesto', 'casas', 'reformas'],
        ],
        'presupuesto' => [
            'name' => 'Presupuesto de obra y cómputo métrico',
            'short' => 'Sabé cuánto cuesta tu proyecto por rubro antes de comprometerte.',
            'title' => 'Presupuesto de obra y cómputo métrico en Paraguay | Obra',
            'description' => 'Presupuesto de obra y cómputo métrico en Paraguay: cantidades, rubros y costos en guaraníes desde tus planos, para comparar propuestas o pedir crédito.',
            'h1' => 'Presupuesto de obra y cómputo métrico en Paraguay',
            'kicker' => 'Números antes de decisiones',
            'image' => 'hero-casa.webp',
            'image_alt' => 'Casa contemporánea terminada, referencia para presupuesto de obra',
            'includes' => ['Revisión de planos y especificaciones', 'Cómputo métrico por rubro', 'Presupuesto detallado en guaraníes', 'Cronograma estimado por etapas', 'Versión apta para presentar al banco'],
            'ideal' => ['Tenés planos y querés saber cuánto cuesta construir.', 'Necesitás un presupuesto para gestionar un crédito de vivienda.', 'Querés comparar propuestas con el mismo alcance.', 'Vas a construir por etapas y necesitás ordenar prioridades.'],
            'faqs' => [
                ['¿Qué necesito para pedir un presupuesto de obra?', 'Planos o croquis con medidas, ubicación del terreno y el nivel de terminación que buscás. Si no tenés planos, empezamos con una estimación por metro cuadrado orientativa.'],
                ['¿El presupuesto sirve para el banco?', 'Sí. Lo preparamos con el detalle por rubro y el cronograma que suelen pedir los bancos y la AFD para créditos de construcción.'],
                ['¿El presupuesto tiene costo?', 'La estimación inicial sobre tus datos se conversa sin compromiso. Un cómputo métrico completo se cotiza según el tamaño del proyecto y te lo confirmamos antes de empezar.'],
                ['¿Puedo construir con ustedes después?', 'Sí. Si contratás la obra llave en mano, el presupuesto pasa a ser la base del contrato.'],
            ],
            'related' => ['casas', 'supervision', 'ampliaciones'],
            'link' => ['site' => 'prestamo', 'text' => 'Si vas a financiar la obra con crédito, en prestamo.com.py explicamos las opciones de bancos y AFD.'],
        ],
    ],

    // Proceso: terreno -> proyecto -> presupuesto -> obra -> entrega
    // Grupos para el menu de servicios y el indice /servicios/
    'groups' => [
        'nueva' => ['name' => 'Construcción nueva', 'services' => ['casas', 'quintas', 'comerciales']],
        'exterior' => ['name' => 'Exteriores y patio', 'services' => ['piscinas', 'quinchos', 'patios', 'muros', 'tinglados']],
        'reforma' => ['name' => 'Reformas y ampliaciones', 'services' => ['reformas', 'ampliaciones']],
        'tecnico' => ['name' => 'Servicios técnicos', 'services' => ['supervision', 'presupuesto']],
    ],
    // Subpaginas por servicio y guias (/credito/, /obras/) quedan pendientes:
    // necesitan datos reales (financiacion AFD verificada, obras concretas) antes de construirse.

    // Subpaginas por servicio (/{servicio}/{sub}/) y guias (/guias/{slug}/, /credito/)
    // Especialidades: app/content/sub/{hub}.php, en el orden de los hubs de arriba.
    'children' => obra_load_content_dir('sub', ['casas', 'quintas', 'piscinas', 'quinchos', 'reformas', 'ampliaciones', 'patios', 'tinglados', 'muros', 'comerciales', 'supervision', 'presupuesto']),
    // Guias: app/content/guides/{slug}.php. El orden fija el menu y el sitemap; una guia nueva sin orden va al final.
    'guides' => obra_load_content_dir('guides', ['costo-casa', 'terreno', 'plazos', 'permisos', 'platea', 'ladrillo-bloque', 'albanil', 'credito']),

    'process' => [
        ['01', 'Terreno y consulta', 'Nos contás qué querés construir, dónde queda el terreno o la casa y cómo pensás financiarlo. Podés mandarnos fotos por WhatsApp.'],
        ['02', 'Proyecto y relevamiento', 'Visitamos el lugar, revisamos planos o los coordinamos, y ordenamos prioridades, rubros y decisiones pendientes.'],
        ['03', 'Presupuesto por escrito', 'Presupuesto por rubro en guaraníes, con trabajos incluidos, exclusiones, provisiones y forma de ejecución.'],
        ['04', 'Obra coordinada', 'Un responsable de obra coordina equipos, materiales y avances. Vos recibís reportes y tomás decisiones con tiempo.'],
        ['05', 'Entrega', 'Recorrido final, lista de pendientes resueltos y documentación de lo ejecutado.'],
    ],

    'home_faqs' => [
        ['¿Cuánto cuesta construir o remodelar en Paraguay?', 'Depende de medidas, estado actual, ubicación, estructura, instalaciones, materiales y terminaciones. Con esos datos preparamos un presupuesto por rubro en guaraníes, sin precios por metro cuadrado aislados.'],
        ['¿El presupuesto tiene costo?', 'La primera conversación y la estimación inicial son sin compromiso. Si el proyecto requiere relevamiento técnico o cómputo métrico completo, te lo confirmamos antes de cualquier visita.'],
        ['¿En qué zonas trabajan?', 'Principalmente en Asunción y Gran Asunción. Para otras zonas del país evaluamos cada caso según tamaño del proyecto y logística.'],
        ['¿Puedo construir con crédito bancario o AFD?', 'Sí. Preparamos el presupuesto y el cronograma con el formato que suelen pedir los bancos y ajustamos la obra a los desembolsos.'],
        ['¿Puedo pedir solamente mano de obra?', 'Podemos evaluar distintas modalidades. La propuesta deja claro quién compra, recibe y controla cada material.'],
        ['¿Dan garantía?', 'Las condiciones de garantía dependen del rubro, los materiales y el contrato, y quedan por escrito en la propuesta final.'],
    ],

    'financing' => [
        'propios' => 'Fondos propios',
        'credito' => 'Crédito bancario o AFD',
        'mixto' => 'Una parte propia y otra con crédito',
        'indefinido' => 'Todavía no lo definí',
    ],
    'terrain' => [
        'si' => 'Sí, ya tengo terreno',
        'no' => 'No, todavía busco terreno',
        'existente' => 'Es una obra sobre una construcción existente',
    ],
];
