<?php
declare(strict_types=1);

// Contenido editorial del sitio. Slugs cortos de un nivel (regla: <=15 caracteres, aptos para
// la ruta visible de Google Ads). El orden define la prioridad en home, footer y sitemap.
// 'link' = un solo enlace contextual por pagina hacia otro sitio del grupo (ver config partner_sites).
return [
    'services' => [
        'casas' => [
            'name' => 'Casas llave en mano',
            'short' => 'Planos, obra gruesa, instalaciones y terminaciones en una sola contratación.',
            'title' => 'Construcción de casas llave en mano en Paraguay | Obra',
            'description' => 'Casas llave en mano en Asunción y Gran Asunción: platea, mampostería, techo, instalaciones y terminaciones con un responsable. Pedí evaluar tu terreno.',
            'h1' => 'Construcción de casas llave en mano en Paraguay',
            'kicker' => 'De un terreno a una casa lista para habitar',
            'image' => 'hero-casa.webp',
            'image_alt' => 'Casa contemporánea de ladrillo visto con galería y jardín, estilo paraguayo moderno',
            'includes' => ['Revisión del terreno, niveles y accesos', 'Planos y aprobación municipal dentro del alcance', 'Platea, mampostería y estructura', 'Techo, instalaciones eléctricas y sanitarias', 'Aberturas, revestimientos y terminaciones', 'Entrega con recorrido final y detalle de lo ejecutado'],
            'ideal' => ['Tenés un terreno y querés una sola empresa a cargo de toda la obra.', 'Querés construir desde cero sin coordinar albañil, electricista y plomero por separado.', 'Necesitás definir etapas y alcance antes de cotizar.', 'Querés comparar propuestas con el mismo alcance y las mismas terminaciones.'],
            'faqs' => [
                ['¿Qué incluye una casa llave en mano?', 'Todo lo necesario para entregarte la casa lista para habitar: planos y aprobación, platea, mampostería, techo, instalaciones, aberturas y terminaciones. La propuesta detalla por escrito qué queda incluido y qué no.'],
                ['¿Cuánto cuesta construir una casa en Paraguay?', 'Depende de los metros cuadrados, el terreno, el sistema constructivo, las instalaciones y el nivel de terminación. Primero relevamos esos datos y después preparamos un presupuesto por rubro en guaraníes.'],
                ['¿Cuánto tarda la obra?', 'El plazo se define con el alcance cerrado y se detalla en la propuesta por etapas. No damos plazos antes de conocer el terreno y el proyecto.'],
                ['¿Puedo construir con crédito bancario o AFD?', 'Sí. Muchos clientes construyen con crédito. Te indicamos qué documentación de obra suele pedir el banco y ajustamos el cronograma a los desembolsos.'],
                ['¿Trabajan con un plano que ya tengo?', 'Sí. Revisamos la documentación existente, definimos qué falta y presupuestamos la ejecución sobre ese proyecto.'],
                ['¿Qué significa llave en mano exactamente?', 'Que contratás un alcance completo con un responsable y recibís la casa terminada. Lo que queda dentro y fuera de ese alcance se escribe antes de empezar, para que no haya sorpresas al entregar.'],
            ],
            'sections' => [
                ['Qué pasa si ya tengo planos', ['Si ya tenés planos, no hace falta empezar de cero. Los revisamos con vos: medidas, niveles, cortes, estructura, instalaciones y especificaciones de terminación. Lo que falta o no cierra se anota antes de presupuestar, no en medio de la obra. Con el plano y la construcción en la misma mesa, cada duda se resuelve una sola vez.', 'Un plano bien resuelto en papel puede necesitar ajustes cuando llega al terreno: una pendiente, un árbol, una medianera o un acceso angosto cambian cómo se ejecuta. Por eso el presupuesto sale del plano y de la visita al lugar, no solo de la carpeta.']],
                ['Construir una casa: en qué orden se hace', ['Construir una casa sigue una secuencia lógica: limpieza y replanteo, fundaciones o platea, mampostería y estructura, techo, instalaciones embutidas, revoques, pisos, aberturas y pintura. Cada etapa apoya a la siguiente, y saltarse el orden suele terminar en rotura de lo ya hecho.', 'En una modalidad llave en mano un solo responsable ordena a los oficios: albañilería, electricidad, sanitaria, techista y terminaciones. Vos decidís materiales y terminaciones con tiempo, y la obra no se frena esperando una definición.']],
                ['Qué mirar al comparar propuestas de construcción', ['Dos presupuestos de construcción de viviendas no se pueden comparar si no incluyen lo mismo. Fijate que ambos indiquen metros cubiertos, sistema constructivo, calidad de aberturas, revestimientos, artefactos y quién provee cada material.', 'Desconfiá de las propuestas que llegan en una sola línea. Un presupuesto útil se lee por rubro, aclara exclusiones y deja claro qué cambia si modificás algo.']],
            ],
            'related' => ['quintas', 'piscinas', 'muros', 'reformas', 'presupuesto'],
            'link' => ['site' => 'arq', 'text' => 'Si solo necesitás el proyecto, los renders o la carpeta municipal, ese trabajo lo hace nuestro estudio en arq.com.py.'],
        ],
        'quintas' => [
            'name' => 'Quintas y casas de campo',
            'short' => 'Casa, quincho, piscina, pozo y cerramiento coordinados por una sola empresa.',
            'title' => 'Construcción de quintas y casas de campo en Paraguay | Obra',
            'description' => 'Construcción y refacción de quintas en Paraguay: casa de campo, quincho, piscina, accesos, pozo y muro perimetral coordinados en un solo proyecto.',
            'h1' => 'Construcción de quintas y casas de campo en Paraguay',
            'kicker' => 'Un conjunto completo, no obras sueltas',
            'image' => 'hero-casa.webp',
            'image_alt' => 'Casa de una planta con galería amplia y jardín arbolado',
            'includes' => ['Plan general de intervención por sectores', 'Casa principal o casa de campo', 'Quincho, galería y áreas exteriores', 'Piscina y circulaciones', 'Muro perimetral, portón y accesos', 'Coordinación de pozo, agua y electricidad'],
            'ideal' => ['Compraste una quinta que necesita una puesta a punto integral.', 'Querés construir una casa de campo desde cero.', 'Tenés varias obras que comparten terreno, agua y electricidad.', 'Querés ejecutar por etapas con una visión completa.'],
            'faqs' => [
                ['¿Pueden encargarse de toda la quinta?', 'Sí. Coordinamos casa, quincho, piscina, exteriores, pozo y cerramientos dentro de un alcance general definido antes de empezar.'],
                ['¿Y si la quinta no tiene agua corriente?', 'Coordinamos la perforación del pozo y la instalación de bomba y tanque como parte del proyecto, para que la obra no dependa de un proveedor suelto.'],
                ['¿Se puede refaccionar una construcción existente?', 'Sí. Primero revisamos el estado visible y la documentación disponible para definir qué evaluación adicional hace falta.'],
                ['¿Cómo se cotiza una quinta completa?', 'Por sectores y rubros. Así entendés prioridades, dependencias y alternativas antes de contratar.'],
                ['¿Conviene construir toda la quinta a la vez?', 'No necesariamente. Lo que conviene es tener el plan general completo y ejecutarlo por etapas, dejando previstos los servicios para lo que viene después.'],
                ['¿Qué se construye primero en una quinta nueva?', 'Lo que sostiene todo: acceso, agua, electricidad y desagües. Después el quincho o la casa, y por último piscina y exteriores.'],
            ],
            'sections' => [
                ['Cómo se planifica una quinta completa', ['Una quinta no se construye de un tirón: se ordena por sectores. La casa, el quincho, la piscina, los accesos, el cerco y los servicios comparten terreno, agua y electricidad, y lo que se decide en uno condiciona a los demás. Por eso primero se hace un plan general y después se ejecuta por etapas.', 'El orden habitual empieza por lo que sostiene todo lo demás: accesos y camino de obra, agua, electricidad y desagües. Luego la casa o el quincho, según cómo uses la quinta, y al final la piscina y los exteriores, que necesitan que lo anterior esté resuelto.']],
                ['Construcción de quintas por etapas', ['Muchas familias empiezan por un quincho con baño para usar el terreno cuanto antes y dejan la casa para después. Funciona bien si desde el principio se dejan previstas las conexiones y el lugar donde va cada cosa, para no romper lo hecho.', 'Lo que suele salir caro es improvisar: un pozo ubicado donde después va la piscina, o un camino que no aguanta un camión. Un plan por sectores evita esas vueltas y te deja decidir qué se hace primero según tus tiempos.']],
                ['Casa de campo, refacción o las dos', ['Si la quinta ya tiene construcciones, la pregunta es qué se recupera y qué se hace nuevo. Para lo existente hay una página de refacción de quintas; para la vivienda nueva, una de casas de campo. En un mismo terreno pueden convivir las dos.']],
            ],
            'related' => ['casas', 'piscinas', 'quinchos'],
            'link' => ['site' => 'pozo', 'text' => 'Si la quinta necesita agua propia, la perforación de pozo artesiano la coordinamos con pozo.com.py.'],
        ],
        'piscinas' => [
            'name' => 'Piscinas de hormigón',
            'short' => 'Piscinas de hormigón armado con vereda, filtrado e iluminación.',
            'title' => 'Construcción de piscinas de hormigón en Paraguay | Obra',
            'description' => 'Construcción de piscinas de hormigón en Asunción y Gran Asunción: excavación, estructura, vereda, filtrado e iluminación. Consultá por tu patio o quinta.',
            'h1' => 'Construcción de piscinas de hormigón en Paraguay',
            'kicker' => 'Una piscina pensada como parte del patio',
            'image' => 'servicio-piscina.webp',
            'image_alt' => 'Piscina de hormigón con vereda clara y vegetación tropical',
            'includes' => ['Evaluación del espacio y acceso para la excavación', 'Excavación y estructura de hormigón armado', 'Instalación hidráulica y sistema de filtrado', 'Terminación interior y bordes', 'Vereda, iluminación y área inmediata'],
            'ideal' => ['Querés una piscina nueva para tu casa o quinta.', 'Necesitás integrar piscina, quincho y circulación exterior.', 'Tu patio tiene accesos o medidas que condicionan la obra.', 'Querés definir equipos y terminaciones antes de ejecutar.'],
            'faqs' => [
                ['¿Cuánto cuesta una piscina de hormigón?', 'Cambia por medidas, profundidad, acceso para excavación, tipo de suelo, terminación, filtrado y obras complementarias. Cotizamos después de conocer el lugar y el alcance.'],
                ['¿Cuándo conviene empezar?', 'La temporada de uso arranca con el calor, así que conviene consultar antes de septiembre para tenerla lista para el verano. Igual construimos todo el año.'],
                ['¿La piscina incluye filtro e iluminación?', 'Sí, podemos integrarlos en el alcance. Cada propuesta especifica equipos, conexiones y terminaciones incluidas.'],
                ['¿Pueden construir piscina y quincho juntos?', 'Sí. Coordinar ambos desde el inicio resuelve niveles, instalaciones, circulación y drenaje como un solo conjunto.'],
                ['¿Piscina y pileta son lo mismo?', 'Sí. En Paraguay se usan las dos palabras para hablar de un vaso para nadar. Lo que importa es el tamaño, la estructura y los equipos, no cómo se le diga.'],
                ['¿Qué tipo de piscina me conviene?', 'Depende del espacio, del uso y del terreno. Hay soluciones para patios chicos, para quintas, para terrenos con desnivel y para renovar una existente. Lo vemos en la visita.'],
            ],
            'sections' => [
                ['Piscinas y piletas: qué conviene definir antes de empezar', ['Piscina o pileta, en Paraguay se usan las dos palabras para lo mismo: un vaso de hormigón armado con filtrado, vereda e iluminación. Lo que cambia de una obra a otra es el tamaño, la profundidad, el acceso para excavar y lo que hay alrededor. Esos datos se ven en una visita, y de ahí sale una propuesta ajustada a tu terreno.', 'La construcción de piscinas de hormigón sigue un orden: excavación, estructura, instalación hidráulica, terminación interior, vereda y equipos. Que el vaso sea de hormigón armado permite darle la forma que el lugar pide y que dure sin fisuras.']],
                ['Antes del calor: cuándo consultar', ['La piscina se usa con el calor, y es cuando más gente quiere una. Consultar antes de que empiece la temporada da tiempo para medir, elegir terminaciones y ejecutar sin apuro. Igual se construye todo el año, y en épocas de lluvia se ajusta el ritmo de excavación.', 'Si ya tenés piscina y pierde agua o tiene el revestimiento gastado, también conviene mirarla antes del verano, cuando hay margen para repararla.']],
                ['Qué tipo de piscina necesitás', ['Para un patio chico hay piscinas compactas; para una quinta, vasos grandes con solárium y quincho; para un terreno con desnivel o vista, piscinas desbordantes; y para las que ya existen, renovación. Cada una tiene su página con lo que hay que saber.']],
            ],
            'related' => ['quinchos', 'quintas', 'patios'],
        ],
        'quinchos' => [
            'name' => 'Quinchos con parrilla',
            'short' => 'Parrilla, mesada, bacha, techo e iluminación integrados a tu patio.',
            'title' => 'Construcción de quinchos con parrilla en Paraguay | Obra',
            'description' => 'Construcción de quinchos con parrilla en Asunción y Gran Asunción: estructura, techo, parrilla, mesada, bacha e instalaciones en una sola obra.',
            'h1' => 'Construcción de quinchos con parrilla en Paraguay',
            'kicker' => 'Donde la casa se encuentra con el patio',
            'image' => 'servicio-quincho.webp',
            'image_alt' => 'Quincho abierto con parrilla de ladrillo, mesa y jardín',
            'includes' => ['Definición de tamaño, ubicación y estilo', 'Estructura y techo (tejas, chapa o madera)', 'Parrilla, mesada y bacha', 'Instalación eléctrica e hidráulica', 'Pisos, iluminación y terminaciones'],
            'ideal' => ['Querés sumar un área de asado a una casa existente.', 'Buscás conectar cocina, galería y patio.', 'Necesitás un quincho para una quinta o casa de fin de semana.', 'Querés hacer quincho y piscina en una misma obra.'],
            'faqs' => [
                ['¿Cuánto cuesta construir un quincho?', 'Depende de las medidas, el tipo de techo, la estructura, la parrilla, las instalaciones y las terminaciones. Con esos datos armamos el presupuesto.'],
                ['¿Puede incluir baño y depósito?', 'Sí. Se pueden sumar ambientes complementarios según espacio, instalaciones y alcance.'],
                ['¿Construyen quinchos en casas ya habitadas?', 'Sí. Planificamos accesos, protección de las áreas existentes y la secuencia de trabajo según el lugar.'],
                ['¿Puedo pedir solamente techo y parrilla?', 'Sí. El alcance puede ajustarse a una intervención puntual siempre que la solución sea técnicamente viable.'],
                ['¿Qué diferencia hay entre un quincho y una galería con parrilla?', 'El quincho es un ambiente propio, con techo, piso y a veces cerramientos. La galería es un espacio abierto pegado a la casa. Lo definimos según cómo lo vas a usar y dónde lo querés.'],
                ['¿Hacen el techo de madera del quincho?', 'Sí. El machimbre y las estructuras de madera son parte de nuestra obra, incluida la protección de la madera y el encuentro con la parrilla y el humo.'],
            ],
            'sections' => [
                ['Cómo se construye un quincho con parrilla', ['Un quincho es más que una parrilla bajo techo. Se piensa el conjunto: dónde va el fuego, cómo sale el humo, cuánto espacio queda para la mesa y la circulación, y qué tan cerca está de la casa. Ubicarlo a favor del viento y con buen acceso a la cocina hace que se use más.', 'La obra sigue un orden: base y piso, estructura, techo, parrilla y mesada, instalaciones y terminaciones. La parrilla se hace de ladrillo refractario o con módulos prefabricados, según el estilo y el uso.']],
                ['Techo de madera, machimbre y otras cubiertas', ['El techo define el clima del quincho. El machimbre y las vigas de madera dan un ambiente cálido y fresco, pero piden buen tratamiento y mantenimiento. La teja y la chapa aíslan y resisten distinto. Lo elegimos con vos según el uso y el presupuesto.', 'Los techos de madera los construimos nosotros como parte de la obra, y por eso hay una página propia para quinchos con techo de madera dentro de este servicio.']],
                ['Qué conviene resolver antes de empezar', ['La ventilación y la salida de humo son lo que más se subestima: una campana o una chimenea mal calculada arruinan el uso. También conviene decidir desde el principio si el quincho lleva baño, bacha, heladera o depósito, porque cada cosa cambia las cañerías y la electricidad.', 'Si la casa está habitada, se planifica el paso de materiales y se protege lo existente. Un quincho bien pensado se usa con calor o con lluvia.']],
            ],
            'related' => ['piscinas', 'patios', 'quintas', 'casas', 'muros'],
            'link' => ['site' => 'carpinteria', 'path' => '/aluminio/', 'text' => 'Si querés cerrar el quincho con aberturas de aluminio o blindex, esas piezas las fabrica carpinteria.com.py y las colocamos dentro de la misma obra.'],
        ],
        'reformas' => [
            'name' => 'Reformas y remodelaciones',
            'short' => 'Reorganizá ambientes, renová instalaciones y terminaciones sobre lo que ya tenés.',
            'title' => 'Reformas y remodelación de casas en Paraguay | Obra',
            'description' => 'Reformas y remodelación de casas en Asunción y Gran Asunción: demoliciones, albañilería, instalaciones y terminaciones con alcance claro y un responsable.',
            'h1' => 'Reformas y remodelación de casas en Paraguay',
            'kicker' => 'Hacé que la casa acompañe una nueva etapa',
            'image' => 'hero-casa.webp',
            'image_alt' => 'Vivienda contemporánea renovada con galería y jardín',
            'includes' => ['Relevamiento de lo existente', 'Demoliciones y retiro de escombros', 'Albañilería e instalaciones nuevas', 'Revestimientos, pisos y pintura', 'Plan de trabajo para reducir molestias si la casa está habitada'],
            'ideal' => ['La distribución actual ya no funciona para tu familia.', 'Querés integrar ambientes o abrir la casa hacia el patio.', 'Compraste una casa y querés renovarla antes de mudarte.', 'Querés poner en valor una casa antes de alquilarla o venderla.'],
            'faqs' => [
                ['¿Cuánto cuesta remodelar una casa?', 'Depende del sector, el estado de la estructura y las instalaciones, las demoliciones y el nivel de terminación. Una visita inicial permite definir el alcance y presupuestar por rubro.'],
                ['¿Se puede remodelar sin salir de la casa?', 'Muchas veces sí, por etapas y aislando sectores. Algunas intervenciones requieren desocupar áreas temporalmente por seguridad.'],
                ['¿Hacen demoliciones y retiro de escombros?', 'Sí, cuando forman parte de la reforma. Quedan detallados en la propuesta.'],
                ['¿Necesito planos para una reforma?', 'Para cambios estructurales o de fachada suele hacer falta documentación municipal. Lo revisamos en el relevamiento y te decimos qué corresponde.'],
                ['¿Cuál es la diferencia entre reforma, refacción y remodelación?', 'En la práctica se usan casi como sinónimos. Refacción suele hablar de reparar y renovar lo existente; remodelación, de cambiar la distribución o el uso de los ambientes. En la visita definimos qué necesita tu casa.'],
                ['¿Qué pasa si aparece algo inesperado al abrir una pared?', 'Se detiene ese frente, se te muestra y se propone una solución con su costo aparte antes de seguir. Por eso el relevamiento previo intenta anticipar lo que se pueda.'],
            ],
            'sections' => [
                ['Cómo se ordena una reforma de casa', ['Una reforma empieza mirando lo que hay: estructura, humedades, instalaciones viejas y qué paredes se pueden tocar. Con ese relevamiento se decide qué se demuele, qué se conserva y qué se rehace. Sin esa mirada previa, la remodelación se llena de sorpresas cuando se abre una pared.', 'Después viene la secuencia: demoliciones y retiro, albañilería, instalaciones nuevas, revoques, pisos y revestimientos, y por último pintura y detalles. Se trabaja sector por sector para poder seguir usando el resto de la casa.']],
                ['Vivir en la casa durante la remodelación', ['Se puede, con planificación. Se aíslan los sectores en obra con cerramientos provisorios, se define qué baño y qué cocina siguen funcionando y se ordenan los horarios. Cuando una intervención toca instalaciones principales, puede haber cortes de agua o luz que se avisan antes.', 'Si la reforma es grande, a veces conviene desocupar una parte por seguridad. Lo hablamos en la visita, sin apuro.']],
                ['Humedad, revoques y refacción de lo viejo', ['Una refacción seria no tapa la humedad con pintura. Se busca el origen: una cañería que pierde, un desnivel del patio, falta de aislación en cimientos o un techo con filtraciones. Recién corregida la causa se reparan revoques y terminaciones.', 'Lo mismo pasa con instalaciones eléctricas y sanitarias antiguas: si las paredes ya están abiertas, es el momento de cambiarlas y no de dejar un parche.']],
            ],
            'related' => ['ampliaciones', 'patios', 'casas', 'comerciales', 'presupuesto'],
            'link' => ['site' => 'arq', 'path' => '/regularizacion/', 'text' => 'Si la construcción existente no tiene planos aprobados, la regularización la hace nuestro estudio en arq.com.py antes o durante la reforma.'],
        ],
        'ampliaciones' => [
            'name' => 'Ampliaciones de vivienda',
            'short' => 'Un dormitorio, una planta alta o un área social nueva sobre la casa actual.',
            'title' => 'Ampliación de casas en Paraguay | Obra',
            'description' => 'Ampliación de casas en Asunción y Gran Asunción: dormitorios, planta alta, galerías y áreas sociales sumados a lo existente, con estructura resuelta.',
            'h1' => 'Ampliación de casas en Paraguay',
            'kicker' => 'Más metros sin mudarte',
            'image' => 'hero-casa.webp',
            'image_alt' => 'Casa ampliada hacia una galería cubierta y jardín',
            'includes' => ['Verificación de estructura y fundaciones existentes', 'Planos de ampliación y aprobación cuando corresponde', 'Obra gruesa del sector nuevo', 'Empalme de techos, instalaciones y desagües', 'Terminaciones a tono con la casa actual'],
            'ideal' => ['La familia creció y necesitás un dormitorio o baño más.', 'Querés sumar una planta alta o un estudio.', 'Buscás una galería o área social conectada al patio.', 'Tu terreno tiene lugar y querés aprovecharlo antes que mudarte.'],
            'faqs' => [
                ['¿Cuánto cuesta ampliar una casa?', 'Depende del área a sumar, la estructura existente, si es en planta baja o planta alta, las instalaciones y el nivel de terminación. Relevamos primero y cotizamos por rubro.'],
                ['¿Se puede construir una planta alta sobre mi casa?', 'Depende de la estructura y las fundaciones existentes. Lo verificamos antes de proponer una solución.'],
                ['¿La ampliación necesita permiso municipal?', 'En general sí. Incluimos la documentación necesaria en el alcance o trabajamos sobre los planos que ya tengas.'],
                ['¿Puedo seguir viviendo en la casa durante la obra?', 'Normalmente sí. Planificamos la secuencia para aislar el sector en obra y minimizar polvo y ruido.'],
                ['¿Cómo sé si mi casa aguanta una planta alta?', 'No se puede saber a simple vista. Se revisan la estructura, las fundaciones y el tipo de mampostería, y de ahí se define si se puede subir, si hace falta reforzar o si conviene ampliar en planta baja.'],
            ],
            'sections' => [
                ['Ampliar una casa: primero la estructura existente', ['Antes de dibujar la ampliación hay que saber sobre qué se apoya. Se revisan fundaciones, estado de las paredes y del techo, y se decide si el sector nuevo trabaja solo o se vincula con la construcción actual. Una planta alta, por ejemplo, exige verificar que lo de abajo la aguante.', 'También se mira el terreno: retiros a medianeras, lugar libre y por dónde entran los materiales. A veces la ubicación más conveniente no es la más obvia.']],
                ['Cómo se une lo nuevo con lo viejo', ['El punto más delicado de una ampliación es el empalme: techos que se encuentran, desagües que se prolongan, instalaciones que se conectan y paredes que se traban sin fisuras. Un empalme mal resuelto se nota en filtraciones y grietas.', 'Las terminaciones se piensan para que el sector nuevo no parezca un agregado: mismos revoques, pisos y aberturas cuando conviene, o un contraste elegido a propósito.']],
                ['Planta baja, planta alta o galería', ['Una ampliación en planta baja es más simple de ejecutar, pero usa patio. La planta alta libera el terreno y pide más estructura. Una galería o un área social cubierta suma metros de uso con una obra más liviana.', 'Contanos qué necesitás: un dormitorio, un baño, un estudio o un espacio para reunirse. Con eso se evalúa la opción que encaja con tu casa y tu terreno.']],
            ],
            'related' => ['reformas', 'patios', 'tinglados', 'casas', 'presupuesto'],
        ],
        'patios' => [
            'name' => 'Patios, decks y pérgolas',
            'short' => 'Veredas, decks, pérgolas y galerías para usar el exterior todo el año.',
            'title' => 'Patios, decks y pérgolas en Paraguay | Obra',
            'description' => 'Construcción de patios, veredas, decks, pérgolas y galerías en Asunción y Gran Asunción. Exteriores integrados a la casa, el quincho o la piscina.',
            'h1' => 'Patios, decks y pérgolas en Paraguay',
            'kicker' => 'Más sombra, circulación y vida al aire libre',
            'image' => 'servicio-cochera.webp',
            'image_alt' => 'Estructura liviana de metal y madera sobre un patio de adoquines',
            'includes' => ['Evaluación de asoleamiento y escurrimiento del agua', 'Contrapiso, vereda o adoquinado', 'Deck de madera o compuesto', 'Pérgola o galería con estructura y cubierta', 'Encuentros con jardín, casa y piscina'],
            'ideal' => ['Querés ganar sombra sin cerrar el patio.', 'Necesitás mejorar la circulación entre casa, quincho y piscina.', 'Buscás renovar un exterior deteriorado.', 'Querés un deck o una galería liviana.'],
            'faqs' => [
                ['¿Qué conviene: deck, piso o adoquinado?', 'Depende del uso, la exposición al agua, el mantenimiento esperado y el soporte existente. Lo evaluamos antes de recomendar.'],
                ['¿Las pérgolas protegen de la lluvia?', 'Una pérgola abierta filtra el sol. Para lluvia hace falta una cubierta y resolver los desagües. El alcance se define según el uso.'],
                ['¿Pueden integrar el trabajo con una piscina?', 'Sí. Coordinamos niveles, bordes, drenajes y superficies antideslizantes desde el inicio.'],
                ['¿Hacen solamente el patio?', 'Sí. Una intervención exterior independiente se cotiza igual, con su alcance por escrito.'],
                ['¿Cuánto mantenimiento pide un deck de madera?', 'Depende de la madera y de cuánto sol y agua recibe. En general requiere revisión y protección periódica. Un deck compuesto pide menos, pero el material y el detalle de instalación son distintos.'],
                ['¿Se puede hacer el patio por etapas?', 'Sí. Lo importante es dejar previstos niveles, desagües y conexiones para lo que viene después, así no se rompe lo ya construido.'],
            ],
            'sections' => [
                ['Cómo se piensa un patio antes de construirlo', ['Un patio se usa según el sol, el agua y los recorridos. Antes de elegir piso o estructura se miran las pendientes, por dónde escurre la lluvia y qué zonas quedan al sol de la tarde. Un contrapiso con la pendiente correcta evita charcos y humedad contra las paredes.', 'Después se ordenan los usos: circulación, estar, cocina exterior, juegos, jardín. No todo tiene que estar terminado de una vez; puede hacerse por etapas si el plano ya prevé lo que viene.']],
                ['Decks y pérgolas: qué se construye', ['El deck se apoya sobre una estructura de vigas y soporta la intemperie según la madera o el material compuesto elegido. La pérgola puede ser de madera o metal, abierta para filtrar el sol o con cubierta para resistir la lluvia. Ambas las construimos nosotros como parte de la obra exterior.', 'Lo importante es el detalle: cómo se fija al piso o a la pared, cómo se trata la madera y cómo se conduce el agua. Ahí se nota la diferencia con el uso.']],
                ['Adoquín, cemento alisado o porcelanato exterior', ['Cada piso tiene su carácter. El adoquín drena bien y se repara por sectores; el cemento alisado da una superficie continua y sobria; el porcelanato exterior es prolijo pero pide un buen antideslizante. Con mucho sol conviene pensar en el calor del material.', 'Elegimos con vos según cómo vas a usar el patio, cuánto mantenimiento querés y cómo se lleva con el resto de la casa.']],
            ],
            'related' => ['quinchos', 'piscinas', 'muros', 'casas', 'ampliaciones'],
        ],
        'tinglados' => [
            'name' => 'Tinglados, galpones y cocheras',
            'short' => 'Estructura metálica y cubierta para vehículos, depósito o producción.',
            'title' => 'Construcción de tinglados y galpones en Paraguay | Obra',
            'description' => 'Construcción de tinglados y galpones en Asunción y Gran Asunción: estructura metálica, cubierta, canaletas y piso según el uso residencial o comercial.',
            'h1' => 'Construcción de tinglados, galpones y cocheras en Paraguay',
            'kicker' => 'Cubiertas resueltas para el clima y el uso real',
            'image' => 'servicio-cochera.webp',
            'image_alt' => 'Cochera moderna con estructura metálica y cubierta liviana',
            'includes' => ['Definición de uso, luces y apoyos', 'Fundaciones y estructura metálica', 'Cubierta y aislación según alcance', 'Canaletas y conducción del agua', 'Contrapiso, portones e iluminación'],
            'ideal' => ['Necesitás proteger vehículos del sol y la lluvia.', 'Querés un galpón para depósito, taller o producción.', 'Tu negocio necesita área cubierta para operar.', 'Querés ampliar una galería o un área de trabajo.'],
            'faqs' => [
                ['¿Cuánto cuesta un tinglado o galpón?', 'Depende de las medidas, la luz estructural, el material, la cubierta, la aislación, el piso y los accesos. Cotizamos con un alcance definido.'],
                ['¿Trabajan con estructura metálica?', 'Sí. Evaluamos estructura metálica, de madera o mixta según dimensiones, uso y presupuesto.'],
                ['¿Incluyen canaletas y desagües?', 'Sí. Son parte importante de la solución y se detallan en el alcance.'],
                ['¿Hacen tinglados para empresas?', 'Sí. Coordinamos obras comerciales e industriales livianas con fecha objetivo y etapas.'],
                ['¿Qué información necesito para pedir un tinglado?', 'Medidas aproximadas, el uso que le vas a dar, la ubicación y el tipo de acceso. Con una foto del lugar por WhatsApp ya podemos empezar a orientarte.'],
                ['¿Se puede ampliar un tinglado después?', 'Sí, si desde el inicio se dejan previstas las fundaciones y la estructura para crecer. Conviene decirlo al presupuestar.'],
            ],
            'sections' => [
                ['Cómo se construye un tinglado', ['Un tinglado se resuelve con la luz libre que necesita el uso: cuántos metros sin columnas, qué altura de paso y qué cargas soporta. De ahí salen las fundaciones, la estructura y la cubierta. Un depósito con autoelevadores no pide lo mismo que una cochera familiar.', 'La secuencia es replanteo, fundaciones, montaje de la estructura, cubierta, canaletas y piso. Es una obra ordenada donde el montaje va fluido si las bases están bien hechas.']],
                ['Cubierta, aislación y desagües', ['En Paraguay mandan el calor y las lluvias fuertes. Una chapa sola calienta; con aislación o una cámara de aire el ambiente se soporta mucho más. Las canaletas y bajadas deben dimensionarse para tormentas y llevar el agua lejos de las bases.', 'Si el espacio va a usarse para trabajar, se piensa también la ventilación natural, la iluminación y la altura de los portones.']],
                ['Galpones, cocheras y usos comerciales', ['La cochera cubierta para uno o varios vehículos es la obra más común en casas. El galpón de depósito, taller o producción suma preguntas: piso reforzado, accesos para camiones, instalación eléctrica y sanitaria. Cada uso define el alcance.', 'Si el tinglado se apoya en una construcción existente o comparte pared con un vecino, se estudian los apoyos y los desagües para no generar problemas.']],
            ],
            'related' => ['techos', 'patios', 'comerciales', 'muros', 'casas', 'quintas'],
        ],
        'techos' => require __DIR__ . '/content/hub/techos.php',
        'muros' => [
            'name' => 'Muros perimetrales y cerramientos',
            'short' => 'Muralla, portón y acceso integrados a la propiedad.',
            'title' => 'Muros perimetrales y murallas en Paraguay | Obra',
            'description' => 'Construcción de muros perimetrales, murallas, portones y accesos en Asunción y Gran Asunción para casas, quintas y terrenos.',
            'h1' => 'Muros perimetrales y murallas en Paraguay',
            'kicker' => 'Privacidad y acceso desde el límite del terreno',
            'image' => 'servicio-cochera.webp',
            'image_alt' => 'Acceso residencial con estructura metálica, pavimento y jardín',
            'includes' => ['Medición y verificación de límites', 'Fundaciones y mampostería', 'Revoque, terminación y pintura', 'Previsión de portón y accesos', 'Drenaje y encuentro con vereda o patio'],
            'ideal' => ['Necesitás cerrar un terreno o una quinta.', 'Querés renovar el frente y el acceso de la casa.', 'Buscás integrar muralla, portón y cochera.', 'El proyecto completo necesita resolver perímetro y seguridad.'],
            'faqs' => [
                ['¿Cuánto cuesta construir una muralla?', 'Depende de la longitud, la altura, la fundación, el terreno, la terminación y los accesos. Con esas medidas presupuestamos.'],
                ['¿Incluyen portón?', 'El portón y su automatización pueden coordinarse dentro del proyecto, con provisiones y responsabilidades detalladas.'],
                ['¿Hacen cerramientos para quintas y terrenos grandes?', 'Sí. Evaluamos extensión, accesos y ejecución por etapas.'],
                ['¿Pueden renovar solamente el frente?', 'Sí. Un frente, acceso o tramo específico se cotiza como intervención independiente.'],
                ['¿Cómo sé dónde termina mi terreno?', 'Con los documentos del inmueble y, si hace falta, una mensura. Verificá los límites antes de levantar el muro; la obra se ejecuta sobre esa línea.'],
                ['¿Se puede hacer la muralla por tramos?', 'Sí. Se ejecuta por etapas, empezando por el frente o por el lado más urgente, dejando previstos pilares y encadenados para continuar.'],
            ],
            'sections' => [
                ['Muro perimetral: qué se construye', ['Un muro perimetral empieza bajo tierra. Se replantean los límites, se hace la fundación y recién después se levanta la mampostería, con pilares y encadenados que le dan rigidez. Por eso verificá los límites del terreno antes de empezar, con tu escritura o tu mensura, y coordiná con los vecinos si el muro va en medianera.', 'La altura, el espesor y el tipo de ladrillo o bloque dependen de la longitud y del uso. Una muralla de fondo no pide lo mismo que un frente con portón y cochera.']],
                ['Murallas, portones y accesos', ['El frente es la cara de la propiedad. Ahí se integran el muro, el portón peatonal y vehicular, los pilares de acceso, los medidores y el buzón. Conviene resolverlo todo junto para que las terminaciones y los niveles coincidan.', 'Si el portón va a automatizarse, la electricidad y los apoyos se dejan previstos antes de revocar.']],
                ['Drenaje, suelo y seguridad', ['En suelos arcillosos y con lluvias fuertes un muro necesita buen drenaje y fundaciones que no se muevan. Un muro de contención o un cerco en desnivel exige un cálculo específico. Lo evaluamos en la visita antes de proponer una solución.', 'La seguridad también se resuelve con la obra: altura, terminación superior, iluminación exterior y visibilidad desde la calle.']],
            ],
            'related' => ['tinglados', 'quintas', 'casas', 'patios', 'comerciales'],
        ],
        'comerciales' => [
            'name' => 'Obras comerciales',
            'short' => 'Locales, oficinas y consultorios preparados para operar en fecha.',
            'title' => 'Obras comerciales y adecuación de locales en Paraguay | Obra',
            'description' => 'Obras comerciales y adecuación de locales, oficinas y consultorios en Asunción y Gran Asunción: obra civil, instalaciones y terminaciones coordinadas.',
            'h1' => 'Obras comerciales y adecuación de locales en Paraguay',
            'kicker' => 'Un espacio listo para trabajar, en fecha',
            'image' => 'hero-casa.webp',
            'image_alt' => 'Arquitectura contemporánea de ladrillo con galería y amplias aberturas',
            'includes' => ['Relevamiento del local o inmueble', 'Demoliciones, divisiones y obra civil', 'Instalaciones eléctricas, sanitarias y de datos', 'Pisos, cielorrasos, iluminación y terminaciones', 'Planificación por etapas con fecha objetivo'],
            'ideal' => ['Alquilaste un local y necesitás adaptarlo.', 'Querés remodelar una oficina o un consultorio.', 'La operación requiere instalaciones o sectores nuevos.', 'Buscás un solo responsable de obra y terminaciones.'],
            'faqs' => [
                ['¿Qué tipo de obras comerciales realizan?', 'Locales, oficinas, consultorios y espacios operativos. El alcance depende del inmueble, el uso y los requisitos del proyecto.'],
                ['¿Pueden trabajar con una fecha de apertura?', 'Sí. La fecha objetivo se incorpora a la planificación. La viabilidad depende del alcance, los permisos y los tiempos de provisión.'],
                ['¿Trabajan fuera del horario comercial?', 'Se acuerda según el lugar, las restricciones del inmueble y la seguridad de la obra.'],
                ['¿Incluyen mobiliario y cartelería?', 'Podemos coordinar rubros complementarios cuando forman parte del alcance. La propuesta aclara qué provee Obra y qué contratás vos.'],
                ['¿Qué necesito para que me presupuesten un local?', 'Fotos, medidas o plano, la actividad que va a haber y qué querés cambiar. Si el contrato de alquiler tiene condiciones sobre obras, contanos también.'],
                ['¿Hacen obras en oficinas o consultorios ocupados?', 'Sí, con un plan por sectores y horarios. Depende de las restricciones del edificio y del tipo de actividad.'],
            ],
            'sections' => [
                ['Cómo se adapta un local, oficina o consultorio', ['Un local alquilado casi nunca llega listo. Hay que ordenar la distribución, levantar o demoler divisiones, resolver las instalaciones eléctricas, sanitarias y de datos, y terminar pisos, cielorrasos e iluminación. Un consultorio suma requisitos de higiene y de instalaciones específicas.', 'Antes de empezar conviene revisar qué permite el contrato de alquiler y qué hay que consultar con el propietario o el municipio. Eso lo confirmás vos con cada entidad; nosotros ordenamos la obra.']],
                ['Trabajar con una fecha de apertura', ['Si tu negocio tiene una fecha objetivo, la obra se planifica hacia atrás: qué rubros son críticos, qué materiales tardan en llegar y qué trabajos pueden hacerse en paralelo. La fecha es una meta que se cuida, no una promesa que se firma sin conocer el local.', 'Coordinamos con proveedores de mobiliario, cartelería y equipamiento para que lleguen cuando el espacio está listo para recibirlos.']],
                ['Obra comercial con el local en funcionamiento', ['A veces la obra se hace con el negocio abierto o en horarios reducidos. Se acuerdan sectores, horarios de ruido y limpieza diaria. En locales de centros comerciales o edificios suele haber normas internas que hay que consultar antes.', 'La idea es que el cliente que entra no vea el desorden, y que el equipo de obra no interrumpa la operación.']],
            ],
            'related' => ['tinglados', 'reformas', 'supervision', 'ampliaciones', 'presupuesto'],
            'link' => ['site' => 'arq', 'path' => '/comercial/', 'text' => 'Si el local necesita proyecto, distribución y diseño interior, ese trabajo lo hace nuestro estudio en arq.com.py.'],
        ],
        'supervision' => [
            'name' => 'Supervisión y fiscalización de obra',
            'short' => 'Un ingeniero responsable que controla tu obra aunque la ejecute otro.',
            'title' => 'Supervisión y fiscalización de obra en Paraguay | Obra',
            'description' => 'Supervisión, fiscalización y dirección de obra en Asunción y Gran Asunción: control de avances, calidad, certificaciones y pagos con un profesional responsable.',
            'h1' => 'Supervisión y fiscalización de obra en Paraguay',
            'kicker' => 'Alguien de tu lado mirando la obra',
            'image' => 'servicio-cochera.webp',
            'image_alt' => 'Obra en construcción con estructura metálica y piso terminado',
            'includes' => ['Revisión del contrato, planos y presupuesto vigente', 'Visitas de control con informe de avance', 'Verificación de calidad de materiales y ejecución', 'Control de certificaciones y pagos por etapa', 'Recepción final con lista de pendientes'],
            'ideal' => ['Contrataste un maestro de obra y querés control profesional.', 'Vivís lejos de la obra o en el exterior.', 'La obra se atrasó o superó el presupuesto y necesitás ordenarla.', 'El banco o el municipio exigen un profesional responsable.'],
            'faqs' => [
                ['¿Qué diferencia hay entre supervisión y dirección de obra?', 'La supervisión controla que la obra siga el proyecto y el contrato. La dirección técnica además toma decisiones de ejecución y asume la responsabilidad profesional ante el municipio.'],
                ['¿Pueden supervisar una obra que ya empezó?', 'Sí. Hacemos un relevamiento del estado, revisamos lo pagado y lo ejecutado y proponemos un plan de control desde ese punto.'],
                ['¿Con qué frecuencia visitan la obra?', 'Se define según la etapa y el ritmo de la obra, y queda por escrito en la propuesta.'],
                ['¿Cuánto cuesta la supervisión?', 'Depende del tamaño de la obra, la frecuencia de visitas y el alcance del control. Se cotiza aparte de la ejecución.'],
                ['¿Qué revisa un ingeniero civil en una obra de casa?', 'Fundaciones, armaduras, hormigonado, mampostería, techos, instalaciones y el cumplimiento del proyecto. Deja informes por visita con lo observado y lo que hay que corregir.'],
                ['¿Sirve una supervisión si el constructor es otro?', 'Sí, para eso existe. Trabajamos con el contrato y los planos que ya tengas y controlamos que se cumplan.'],
            ],
            'sections' => [
                ['Ingeniero civil: qué controla en tu obra', ['El ingeniero civil revisa que la obra respete el proyecto, el contrato y las buenas prácticas: armaduras antes de hormigonar, medidas de fundaciones, ejecución de mampostería, pendientes y encuentros de techos. Es quien puede decirte si algo se hace bien o si hay que corregirlo a tiempo.', 'También controla lo administrativo: avance real contra lo cobrado, materiales entregados y certificaciones por etapa. Así cada pago tiene un respaldo en obra.']],
                ['Cuándo conviene tener un ingeniero civil', ['Conviene desde el principio si vas a construir con un maestro de obra y querés una mirada técnica, si vivís lejos, si el banco lo pide o si la obra tiene estructura importante. También si ya empezó y sentís que algo no cierra.', 'No hace falta para cualquier arreglo chico. Sí vale la pena en fundaciones, losas, estructuras y obras donde un error es caro de reparar.']],
                ['Fiscalización de obra: cómo se trabaja', ['Se hacen visitas en los momentos clave y cada una deja un informe con fotos, observaciones y pendientes. Las decisiones de ejecución las toma quien dirige la obra; la fiscalización verifica y advierte.', 'Si la ejecución la hace otro constructor, la supervisión funciona igual. Lo importante es que quien controla no dependa de quien ejecuta.']],
            ],
            'related' => ['presupuesto', 'casas', 'reformas', 'ampliaciones', 'tinglados'],
        ],
        'presupuesto' => [
            'name' => 'Presupuesto de obra y cómputo métrico',
            'short' => 'Sabé cuánto cuesta tu proyecto por rubro antes de comprometerte.',
            'title' => 'Presupuesto de obra y cómputo métrico en Paraguay | Obra',
            'description' => 'Presupuesto de obra y cómputo métrico en Paraguay: cantidades, rubros y costos en guaraníes desde tus planos, para comparar propuestas o pedir crédito.',
            'h1' => 'Presupuesto de obra y cómputo métrico en Paraguay',
            'kicker' => 'Números antes de decisiones',
            'image' => 'hero-casa.webp',
            'image_alt' => 'Casa contemporánea terminada, referencia para presupuesto de obra',
            'includes' => ['Revisión de planos y especificaciones', 'Cómputo métrico por rubro', 'Presupuesto detallado en guaraníes', 'Cronograma estimado por etapas', 'Versión apta para presentar al banco'],
            'ideal' => ['Tenés planos y querés saber cuánto cuesta construir.', 'Necesitás un presupuesto para gestionar un crédito de vivienda.', 'Querés comparar propuestas con el mismo alcance.', 'Vas a construir por etapas y necesitás ordenar prioridades.'],
            'faqs' => [
                ['¿Qué necesito para pedir un presupuesto de obra?', 'Planos o croquis con medidas, ubicación del terreno y el nivel de terminación que buscás. Si no tenés planos, empezamos con una estimación por metro cuadrado orientativa.'],
                ['¿El presupuesto sirve para el banco?', 'Sí. Lo preparamos con el detalle por rubro y el cronograma que suelen pedir los bancos y la AFD para créditos de construcción.'],
                ['¿El presupuesto tiene costo?', 'La estimación inicial sobre tus datos se conversa sin compromiso. Un cómputo métrico completo se cotiza según el tamaño del proyecto y te lo confirmamos antes de empezar.'],
                ['¿Puedo construir con ustedes después?', 'Sí. Si contratás la obra llave en mano, el presupuesto pasa a ser la base del contrato.'],
                ['¿Qué diferencia hay entre presupuesto y cómputo métrico?', 'El cómputo es la medición de cantidades; el presupuesto es esa medición con los costos aplicados. Uno sin el otro queda incompleto.'],
                ['¿Por qué dos presupuestos del mismo plano dan distinto?', 'Por las terminaciones supuestas, lo incluido o excluido, la provisión de materiales y cómo se midió. Leerlos por rubro muestra dónde está la diferencia.'],
            ],
            'sections' => [
                ['Cómputo métrico: qué es', ['El cómputo métrico es la medición ordenada de todo lo que hay que construir: metros cuadrados de mampostería, metros cúbicos de hormigón, kilos de hierro, metros de cañería, cantidad de aberturas. Se saca del plano, rubro por rubro, y es la base sobre la que se ponen los costos.', 'Un presupuesto sin cómputo es una estimación. Con cómputo, cada línea tiene una cantidad detrás y podés ver qué cambia si modificás una medida o una terminación.']],
                ['Cómo se lee un presupuesto de obra por rubro', ['Un presupuesto por rubro separa los grandes capítulos: trabajos preliminares, fundaciones, estructura, mampostería, techo, instalaciones, revoques, pisos, aberturas, pintura y limpieza. Cada rubro indica qué incluye, quién provee el material y qué queda afuera.', 'Al comparar dos propuestas, hacelo rubro contra rubro. Una diferencia grande casi siempre está en algo que uno incluye y el otro no.']],
                ['Presupuesto para el banco o para decidir', ['Si vas a pedir un crédito, el presupuesto tiene que mostrar el detalle por rubro y un cronograma por etapas, porque los desembolsos se atan al avance. Consultá con tu banco el formato exacto que piden.', 'Si todavía estás decidiendo, un presupuesto ordenado te permite priorizar: qué se hace ahora, qué queda para después y qué se puede simplificar sin comprometer la estructura.']],
            ],
            'related' => ['casas', 'supervision', 'ampliaciones', 'reformas', 'tinglados'],
            'link' => ['site' => 'prestamo', 'text' => 'Si vas a financiar la obra con crédito, en prestamo.com.py explicamos las opciones de bancos y AFD.'],
        ],
    ],

    // Proceso: terreno -> proyecto -> presupuesto -> obra -> entrega
    // Grupos para el menu de servicios y el indice /servicios/
    'groups' => [
        'nueva' => ['name' => 'Construcción nueva', 'services' => ['casas', 'quintas', 'comerciales']],
        'exterior' => ['name' => 'Exteriores y patio', 'services' => ['piscinas', 'quinchos', 'patios', 'muros']],
        'cubiertas' => ['name' => 'Techos y cubiertas', 'services' => ['techos', 'tinglados']],
        'reforma' => ['name' => 'Reformas y ampliaciones', 'services' => ['reformas', 'ampliaciones']],
        'tecnico' => ['name' => 'Servicios técnicos', 'services' => ['supervision', 'presupuesto']],
    ],
    // Subpaginas por servicio y guias (/credito/, /obras/) quedan pendientes:
    // necesitan datos reales (financiacion AFD verificada, obras concretas) antes de construirse.

    // Subpaginas por servicio (/{servicio}/{sub}/) y guias (/guias/{slug}/, /credito/)
    // Especialidades: app/content/sub/{hub}.php, en el orden de los hubs de arriba.
    'children' => obra_load_content_dir('sub', ['casas', 'quintas', 'piscinas', 'quinchos', 'reformas', 'ampliaciones', 'patios', 'tinglados', 'techos', 'muros', 'comerciales', 'supervision', 'presupuesto']),
    // Guias: app/content/guides/{slug}.php. El orden fija el menu y el sitemap; una guia nueva sin orden va al final.
    'guides' => obra_load_content_dir('guides', ['costo-casa', 'terreno', 'plazos', 'permisos', 'platea', 'ladrillo-bloque', 'albanil', 'credito', 'costo-quincho', 'costo-piscina', 'techo-losa-chapa', 'elegir-constructora', 'costo-ampliacion', 'costo-muro-perimetral', 'costo-tinglado', 'humedad-paredes', 'impermeabilizar-losa']),

    'process' => [
        ['01', 'Terreno y consulta', 'Nos contás qué querés construir, dónde queda el terreno o la casa y cómo pensás financiarlo. Podés mandarnos fotos por WhatsApp.'],
        ['02', 'Proyecto y relevamiento', 'Visitamos el lugar, revisamos planos o los coordinamos, y ordenamos prioridades, rubros y decisiones pendientes.'],
        ['03', 'Presupuesto por escrito', 'Presupuesto por rubro en guaraníes, con trabajos incluidos, exclusiones, provisiones y forma de ejecución.'],
        ['04', 'Obra coordinada', 'Un responsable de obra coordina equipos, materiales y avances. Vos recibís reportes y tomás decisiones con tiempo.'],
        ['05', 'Entrega', 'Recorrido final, lista de pendientes resueltos y documentación de lo ejecutado.'],
    ],

    'home_faqs' => [
        ['¿Cuánto cuesta construir o remodelar en Paraguay?', 'Depende de medidas, estado actual, ubicación, estructura, instalaciones, materiales y terminaciones. Con esos datos preparamos un presupuesto por rubro en guaraníes, sin precios por metro cuadrado aislados.'],
        ['¿El presupuesto tiene costo?', 'La primera conversación y la estimación inicial son sin compromiso. Si el proyecto requiere relevamiento técnico o cómputo métrico completo, te lo confirmamos antes de cualquier visita.'],
        ['¿En qué zonas trabajan?', 'Principalmente en Asunción y Gran Asunción. Para otras zonas del país evaluamos cada caso según tamaño del proyecto y logística.'],
        ['¿Puedo construir con crédito bancario o AFD?', 'Sí. Preparamos el presupuesto y el cronograma con el formato que suelen pedir los bancos y ajustamos la obra a los desembolsos.'],
        ['¿Puedo pedir solamente mano de obra?', 'Podemos evaluar distintas modalidades. La propuesta deja claro quién compra, recibe y controla cada material.'],
        ['¿Dan garantía?', 'Las condiciones de garantía dependen del rubro, los materiales y el contrato, y quedan por escrito en la propuesta final.'],
    ],

    'financing' => [
        'propios' => 'Fondos propios',
        'credito' => 'Crédito bancario o AFD',
        'mixto' => 'Una parte propia y otra con crédito',
        'indefinido' => 'Todavía no lo definí',
    ],
    'terrain' => [
        'si' => 'Sí, ya tengo terreno',
        'no' => 'No, todavía busco terreno',
        'existente' => 'Es una obra sobre una construcción existente',
    ],
];
